### ISSUE TITLE
Testsystem behind a proxy

### ISSUE THREAD

**Issue by Affenpilot** [PAYONE-GmbH/magento-1#103]
Greetings,
We are running a Magento 1.9.3.2 test system behind a proxy environment.  I know that I can enable the Proxy-Mode in the global properties of the payone module, but it doesn´t work.
After debugging, I find out that the function `doRequest` in the `Payone_Api_Adapter_Http_Curl` class was the problem. 
So I added our custom proxy settings in the curl options with hardcoded settings:
`curl_setopt($curl, CURLOPT_PROXY, 'proxy');`
`curl_setopt($curl, CURLOPT_PROXYPORT, 'port');`
And it works!

It is possible to set a custom proxy in the Payone module? Or can you add this option?
After calling with the Payone Support, I hope you can help me.

**Comment by fjbender** [comment]
The "proxy mode" is somewhat misleading, it is concerned with receiving the transaction status notification from our systems.

I think, however, that this is quite an edge case and I can't really dedicate resources to that right now. I'll put this on this wishlist. If you have an idea how to solve this elegantly, pull requests are very welcome! :)

Cheers
Florian

**Comment by Affenpilot** [comment]
Hi florian,

I want to create a pull request for this issue but I get a permission denied.
can you help me about this misstake?

**Comment by fjbender** [comment]
Hi,

you'll have to fork our module on github and then create the pull request in the github web interface. We then can test and review it and merge it into master. You can't push directly to our repository. See: https://gist.github.com/Chaser324/ce0505fbed06b947d962

Thanks for your contribution! :)

**Comment by Affenpilot** [comment]
sorry for the confusing second commit. I selected the wrong branch. This was the reason for the revert commit.

**Comment by Schrank** [comment]
Cool feature! I love to look into the communication of php with whatever API, e.g. payone with [Charles](https://www.charlesproxy.com/) or Wireshark. So this is a good thing! :-)
