### ISSUE TITLE
ratepay.js same function name like Ratepay Magento Extension

### ISSUE THREAD

**Issue by bambamboole** [PAYONE-GmbH/magento-1#107]
We just had the problem that the function `ratepayRateCalculatorAction` in the `ratepay.js` file is the same like in the Original Ratepay Magento Extension and the file is also loaded when Ratepay by Payone isn't activated.
It's bad practice to define non prefixed global javascript functions.
That issue breaks the checkout if you are using the normal Ratepay Magento Extension next to the Payone Magento Extension.

Please prefix function names or better write javascript modules instead of global functions.

**Comment by fjbender** [comment]
This should be fixed in #115. Can you confirm?
