### ISSUE TITLE
Repeated / recurring authorization

### ISSUE THREAD

**Issue by cuprumova** [PAYONE-GmbH/magento-1#109]
Hello,

could you please advice how could i implement repeated / recurring authorization for some old orders? My purpose is to have possibility to invoice such orders later that in the allowed by default time period (for Paypal 29 days, for credit cards 7-28 days)? Is it possible to use some existing method of some existing Payone module class, passing there order parameters?

It's not possible to send completely same parameters as by purchase again as, for example, for credit cards this information is not stored in Magento, but it's already present on Payone side. So i believe that i would need to send only order id, transaction id and so on (without detailed information which is not possible to retrieve from Magento). If i could get some example how i could implement this, i would be thankful. As i understand, i should check somewhere here:

```
class Payone_Core_Model_Service_InitializePayment
...
public function execute(Mage_Sales_Model_Order_Payment $payment)
{

...

$service = $this->getFactory()->getServicePaymentPreauthorize($config);

...
}
```

Other payment gateways have some kind of reauthorization functionality, but your technical support told me that it's possible in this case to do only authorization again and this allows to do capture in the later time period. Thank you for your help!

**Comment by fjbender** [comment]
We didn't really design the Magento integration with this use case in mind. I guess for some payment methods, you can just recreate the authorization (for instance with credit card using the pseudocardpan), but for others that require user authentication it's not possible (e.g. PayPal).

You'd just grab the pseudo card data from somewhere and then build a new authorization using the service factory. I don't see a way to recreate the authorization with just passing an existing order.

Best
Florian

**Comment by cuprumova** [comment]
Hi Florian,

thank you for your answer!

Where could i find more information about pseudocardpan? Technical documentation information.

Thank you,
Anastasia.

**Comment by fjbender** [comment]
For some basic infos, see: https://github.com/fjbender/simple-php-integration

If you contact me at integrations@bspayone.com I'll send you the full API docs.

**Comment by cuprumova** [comment]
hi Florian,

thank you! Sorry for the late answer. It could be i need more information not only about this topic, i will send question then directly to this email address.

Regards,
Anastasia.
