### ISSUE TITLE
Sofortüberweisung not working with Magento 1.9.3.0

### ISSUE THREAD

**Issue by tobiasteatox** [PAYONE-GmbH/magento-1#12]
There seems to be an error with sofortüberweisung and the latest version of magento. When placing an order via sofortüberweisung, sofort.com prints out the following error message. 

"... Der übergebene Input-Hash stimmt nicht mit dem von uns berechneten Input-Hash überein. Wenn Sie der Shopbetreiber sind, überprüfen Sie bitte, ob das in Ihrem Shopsystem gespeicherte Projektpasswort mit dem Projektpasswort in den Projekteinstellungen Ihres Anbietermenüs übereinstimmt"

**Comment by fjbender** [comment]
Hi,

This is a known issue with mage 1.9.3.0. Redirect URLs are now double encodes, which leads to special chars being lost and the hash being invalid. We'll release a patch asap.

**Comment by tobiasteatox** [comment]
Hi fjbender, 

thanks for the quick response! Is there workaround for the moment? 

Thanks in advance

**Comment by fjbender** [comment]
Nope, sorry, it's a Magento change, we can't do anything about it.

**Comment by tobiasteatox** [comment]
Until there is a real fix for this issue the Quick & Dirty way is to remove the encodeURI function from the opcheckout.js

```
nextStep: function(transport){
if (transport) {
	var response = transport.responseJSON || transport.responseText.evalJSON(true) || {};

	if (response.redirect) {
	    this.isSuccess = true;
	    location.href = response.redirect;
	    return;
	}
	if (response.success) {
	    this.isSuccess = true;
	    location.href = this.successUrl;
	}
```

**Comment by fjbender** [comment]
Fixed with bb19424

**Comment by gndk** [comment]
Problem not fixed. Fresh installation of Magento 1.9.3.7 and Payone 9b2292d

Same error. 

"Es ist ein Fehler aufgetreten
Bei der Verarbeitung Ihrer Zahlung ist leider ein Fehler aufgetreten. Bitte kehren Sie zum Shopsystem zurück.

Der übergebene Input-Hash stimmt nicht mit dem von uns berechneten Input-Hash überein. Wenn Sie der Shopbetreiber sind, überprüfen Sie bitte, ob das in Ihrem Shopsystem gespeicherte Projektpasswort mit dem Projektpasswort in den Projekteinstellungen Ihres Anbietermenüs übereinstimmt."

**Comment by fjbender** [comment]
@gndk I just tested the same revision in a fresh 1.9.3.7 and can successfully process a Sofort transaction. Please contact our Technical Support Team to gather more details about this issue.
