### ISSUE TITLE
Unset RatePay shopId/config crashes shop

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#120]
When RatePay is as a payment type activated, but no shopID is set, then no rate_pay_config is saved to database and therefore 

https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Payment/Method/Ratepay.php#L230

returns `null` instead of an array.

Unfortunately

    Warning: Invalid argument supplied for foreach()  in /var/www/app/code/community/Payone/Core/Model/Payment/Method/Ratepay.php on line 231

Is not very helpful especially because 

    \Payone_Core_Model_Config_Payment_Method_Interface::setRatepayConfig

 can't be found to be called in the source code (because it is hidden behind magic method variables)

So I recommend to add a check and a helpful warning here. And (even better) a check when the config is saved so it is not possible to save ratepay without an added shop id

**Comment by fjbender** [comment]
We'll make the Shop-ID mandatory so the payment method can't be saved incorrectly.

**Comment by fjbender** [comment]
This has been fixed with #130
