### ISSUE TITLE
Einzelartikelübermittlung: Rundungsfehler am Beispiel RatePay

### ISSUE THREAD

**Issue by riconeitzel** [PAYONE-GmbH/magento-1#121]
Hallihallohallöchen,

wir haben aktuell das Problem, dass bei Bezahlung via RatePay die Einzelartikel übertragen werden müssen. Die interne Berechnung von Magento funktioniert dabei bekanntermaßen weitläufig mit 4 Nachkommastellen, was zu teilweise eklatanten Rundungsfehlern führen kann.

Wir haben dazu ein entsprechendes PDF mit Musterrechnungen erstellt: http://r.b71a.de/D4TpJ56VZd.pdf

Die linke Dokumenthälfte zeigt die Berechnung in Magento, die rechte die vermutliche Berechnung auf PayOne-Seite. In unserem Beispiel kommen wir so auf eine Differenz zwischen Magento-Gesamtbetrag und PayOne-Gesamtbetrag von 26ct.

Aufgrund dieser Differenz wird der Zahlungsvorgang via Payone + RatePay dann abgebrochen.

Würde RatePay an dieser Stelle den Gesamtbetrag von Magento zusammen mit den Einzelartikeln übernehmen, würde dieses Problem nicht bestehen. 

Ein ähnlich gelagertes Problem gibt es bei PayPal (direkt, nicht via PayOne!) im Zusammenspiel mit der Einzelartikelübermittlung. Dort wurde ein Schalter eingebaut, der diese Funktion deaktivieren kann.

Mit diesen Voraussetzungen ist es also nach aktuellem Stand unmöglich, mit Standardkomponenten RatePay via PayOne als Zahlungsoption anzubieten.

Unsere Lösungsskizze sieht vor, dass die RatePay Gegenstelle nicht nur die Einzelartikel übernimmt und daraus die Gesamtsumme bildet, sondern wahlweise:
A.) die Berechnungsgenauigkeit auf 4-Nachkomma-Stellen erweiterbar macht (Konfigurationswert im PayOne Dashboard?!) - quasi analog zu Magento rechnet "Magentokompatibilitätsmodus"
oder
B.) die von Magento errechnete Gesamtsumme für den Bezahlvorgang übernimmt ohne eine Neuberechnung durchzuführen.

Wir sind auch für andere Vorschläge gerne offen. Aber eine Aussage am Telefon "Das Problem kennen wird, wir bekommen das auch häufiger von Händlern mit, wir bitten auch immer darum, dass uns Lösungsvorschläge mitgeteilt werden, aber die melden sich dann nicht. Das zu lösen ist aber nicht unser Problem, sondern das Problem liegt bei Magento" hilft natürlich nicht.

Verständlich, dass man sich hier aus der Affaire ziehen will, aber dann darf der Verkauf nicht sagen: "Joah - das ist alles kein Problem, da gibts auch ne Extension, das ist quasi fast kein Aufwand." wenn faktisch am Ende klar ist, dass bspw. RatePay im Zusammenhang mit einem Standard-Magento gar nicht eingesetzt werden **kann**.

**Comment by fjbender** [comment]
Moin,

danke für die ausführliche Reproduktion und Analyse. Das hilft uns sicherlich, das Problem einmal grundlegend anzugehen.

Wir müssen nur mal schauen, welche Lösung da nachher gangbar ist.

Ich finde Lösung A grundsätzlich sehr charmant und würde die bevorzugen. Ich habe da allerdings die Befürchtung, dass wir damit eine riesige interne Story aufmachen und mit Fertigstellung in einem nicht akzeptablen Zeitraum zu rechnen ist.

Bei Lösung B haben wir dann das Problem, dass wahrscheinlich RatePay sagt "Ne, der Warenkorb passt nicht zur Summe" und wir da dann nochmal die selbe Geschichte mit einem anderen Ansprechpartner haben. 

Wir brauchen also eine Lösung C, die einerseits nicht zu aufwändig ist, und andererseits komplett in unserem Modul zu machen ist, da das die Komponente in der Kette ist, die am schnellsten anzupassen ist. Alternativ wäre eine Lösung D, die das Verhalten direkt in Magento fixt. So eine Lösung habe ich nicht in der Tasche. 

Ein Ansatz wäre, da wir ja in unserem Payone-Warenkorb sowieso nur die Nettopreise haben wollen, nochmal einen Switch einzubauen, der die Gesammtsumme nochmal neu berechnet. Voraussetzung ist, dass wir darauf vertrauen können, dass die einzelnen Warenkorbelemente die richtigen Nettopreise haben und richtig auf zwei Nachkommastellen gerundet sind. Wir würden dann einfach den Gesamtbetrag der Transaktion aus den Nettopreisen bestimmen und nicht den Grand Total aus Magento nehmen, wie aktuell. Damit hätten wir zumindest einen konsistenten Warenkorb, wissen aber nicht, ob die Gesamtsumme stimmt. Ich würde also von `\Payone_Core_Model_Mapper_ApiRequest_Payment_Authorize_Abstract::mapDefaultAuthorizeParameters` losgehen (dort wird der `amount` Parameter über `$order->getGrandTotal()` gesetzt) und in `\Payone_Core_Model_Mapper_ApiRequest_Payment_Authorize_Abstract::mapInvoicingParameters` (da werden die Warenkorbelemente dem Request hinzugefügt) "irgendwie" schauen, dass hinterher alles passt. Fühlt sich alles etwas frickelig an, könnte aber ein gangbarer Weg werden.

Kannst du ungefähr nachvollziehen, was ich meine?

**Comment by Celldweller** [comment]
Ratepay sagte mir heute im Telefonat, dass sie von vornherein eine Toleranz von 3 Cent berücksichtigen. Das Problem scheint hier also derzeit eher das Payone-Modul zu sein, dessen Toleranz vermutlich 0 ist.

Zu Lösung B:
Grundsätzlich kann ich als Händler ansonsten nur davon ausgehen, dass Ratepay ein großes Interesse daran hat, dass der Workflow reibungslos funktioniert. Vielleicht ist Ratepay hinsichtlich Lösung B also flexibler als gedacht?

**Comment by fjbender** [comment]
Das ist gut zu wissen. Ich prüfe die Lösung B mal mit unseren Plattform-Gurus.

**Comment by fjbender** [comment]
Ich habe die Methode B mal mit Product und der Entwicklung evaluiert. tl;dr: Plattformseitig können wir kurz- und mittelfristig nichts machen und müssen uns auf eine Lösung "vor" unserer API konzentrieren.

Zum Hintergrund: Natürlich sind auch wir an einem reibungslosen Workflow beim Händler interessiert. Die Regel an unserer API ist aber relativ einfach: Der übergebene Warenkorb muss zum übergebenen Amount passen. Das liegt daran, dass wir den Warenkorb ja nicht nur an (in diesem Fall) RatePay weitergeben, sondern auch ggf. selbst etwas damit tun. Viele Händler nutzen z.B. die Rechnungserstellung über unsere Plattform. Hier ist es natürlich wichtig, dass Summe und Warenkorb zusammenpassen, sonst stimmt am Ende die Rechnung nicht. Selbst eine Abweichung im Centbereich kann hier nicht im Interesse des Händlers sein. Wir können an dieser Stelle allerdings nicht sinnvoll die Händler segmentieren.

@riconeitzel Kannst du mir mal timestamp und MID einer betroffenen Transaktion geben? Ich möchte mal ein paar Sachen ausprobieren und das so nah wie möglich an eurem Request nachstellen.

**Comment by Schrank** [comment]
@fjbender MID finde ich leider nicht. Da es keine Bestellung gibt, gibt es keine Transaktionen und die MID scheint weder in der Quote-Tabelle noch sonst irgendwo zu finden sein.

Was ich anbieten kann:
Timestamp: 2017-11-22 18:06:55
Reference: STAGEBT-6394852
Der Käufer dürfte "Fabian Blechschmidt" sein.

Ich schick dir gleich noch ne Mail mit dem Log Eintrag.

Schönes Wochende!

**Comment by fjbender** [comment]
Moin,

danke für den Log-Eintrag. Ich habe die Transaktion rausgesucht und sehe dort folgendes Bild:

```
amount=10416
[...]
no[1]=1
no[2]=1
no[3]=1
no[4]=1
no[5]=1
pr[1]=1890
pr[2]=9900
pr[3]=0
pr[4]=395
pr[5]=-1768
[...]
```

Die Positionen 1-3 sind "normale" Artikel, Position 4 ist der Versand und Position 5 ist ein Gutschein o.ä. Summiere ich die Artikelpositionen bekomme ich einen Gesamtwert der Bestellung von 10417 Cent, es werden aber nur 10416 Cent übermittelt. Die Einzelpreise der Artikel sehen für mich gut aus, weil "glatt". Der Gutschein/Rabatt ist hier scheinbar das Problem.

Was für ein Gutschein/Rabatt ist das genau? Tritt das Problem auch ohne Gutschein/Rabatt auf?

**Comment by Schrank** [comment]
Das ist ein 15% Gutschein, der mit vier Nachkommastellen innerhalb Magentos das Rundungsproblem verursacht.

Die Rundungsprobleme in Magento können wir leider nicht ohne weiteres lösen.

**Comment by fjbender** [comment]
Hmmja. Aber damit wissen wir immerhin, dass "normale" Artikel in eurem eigentlich kein Problem Problem sind. Oder hat @riconeitzel da noch etwas in Petto? In Ricos Beispiel war ja auch die Vermutung, dass die regulären Artikelpositionen auch falsch übertragen werden, dafür hätte ich gern idealerweise dann auch nochmal ein Beispiel.

Wir könnten uns also beim "Reparieren" des Warenkorbs auf Warenkörbe mit prozentualen Gutscheinen beschränken, oder?

**Comment by Schrank** [comment]
Ich Unterstelle, alles was prozentual gerechnet wird, macht ggf. Probleme, d.h. Custom Options, Bündelprodukte(?), Rabatte auf Artikel und Warenkörbe, Versandkosten die Prozentual berechnet werden

**Comment by fjbender** [comment]
Die Vermutung habe ich auch. Ich bräuchte trotzdem noch Feedback von dir @riconeitzel, ob bei regulären Artikelpositionen auch noch etwas schief geht.

**Comment by Schrank** [comment]
Schlimmer. Wir haben einen reproduzierbaren Fall mit fixem Rabatt:
2x Artikel 12€, Versandkosten 3€, Rabatt -33€ Gesamt: 24€.

Wir erzeugen zwei Rechnungen, die erste sollte 12+3-1,5€ sein = 13,5€, wird auch als amount übertragen und die Produkte 1200, 300, -151 - BUMS kaputt.

Gleiches gilt auch bei Gutschriften, wenn man nur eine Rechnung erzeugt :-/

Bisher habe ich keinen Fall für Artikelpositionen und leider auch keine Zeit rum zu probieren.

**Comment by riconeitzel** [comment]
@fjbender was @Schrank sagt (er hat mit mir und sascha daran gearbeitet)

**Comment by fjbender** [comment]
Okay, danke.

Ich hab euer Beispiel mal nachgestellt, und bekomme (wenig überraschend) das selbe Resultat:

![image](https://user-images.githubusercontent.com/7370694/34812657-ea94de52-f6a6-11e7-804c-4d098cd8c921.png)

Ich unterstelle hier mal, dass von diesem Problem nicht nur wir betroffen sind. Unser Modul rechnet ja an dieser Stelle gar nicht selbst. Wahrscheinlich sind also alle payment Module davon betroffen. Ob es dann trotzdem klappt, hängt von der "Gnade" der API ab.

Ich habe die Befürchtung, dass wir hier keine technische Lösung haben werden. Wir werden also eine kommunikative Lösung erfinden müssen, die u.a. damit anfängt, dass der Vertrieb bei Magento 1 und Zahlungsarten, die eine Warenkorbübermittlung erfordern, dahin berät, dass es hier zu Problemen mit Gutscheinen und anderen Rechenoperationen kommt.

**Comment by thampe** [comment]
Hallo zusammen,

ich wollte mal Fragen ob es hier ggf. schon neue Entwicklungen gibt? Aktuell betreue ich auch einen Shop der von diesem Problem betroffen ist. 

Die vorgeschlagenen technischen Lösungen sind doch unabhängig davon, dass *alle* Zahlungsanbieter betroffen sind, weiterhin theoretisch durchführbar oder etwa nicht?

**Comment by phoenix-schwarz** [comment]
Das Problem ist an dieser Stelle ja nicht die Magento-Rundung, sonder die Rundung auf den einzelnen Positionen beim Zahlungsanbieter. Sobald ich mehr als 1 Produkt habe und auf Einzelpositionsebene runden muss für die Übermittlung kommen diese Differenzen zustande. Ja, wir haben diese Problematik auch in einigen Projekten. Meines Erachtens nach ist der einzig gangbare Weg der, dass die Zahlungsanbieter die Warenkörbe auch mit 4 Nachkommastellen annehmen. In internationalen Shops mit Cross-Border Trade und unterschiedlichen steuerlichen Regelungen geht das sonst immer auf die Bretter. Bay PayPal gibt es das Problem übrigens auch, wenn man den Warenkorb übermittelt.

**Comment by Schrank** [comment]
Du meinst es vermutlich genau so, aber nur zur Klarstellung: Nur weil Paypal das nicht klarkriegt, heißt dass nicht, dass das ok ist.

**Comment by phoenix-schwarz** [comment]
Ich finde es alles andere als OK. Für mich sind 4 Nachkommastellen die einzig sinnvolle Lösung.

**Comment by dennismax** [comment]
Wir haben es folgendermaßen gelöst:

- Extension so umgebaut, dass bei der Übertragung an PayOne die Menge auf 1 gesetzt wird
- der Text wird dabei neu berechnet und mit "Menge: <ursprüngliche Menge>" ergänzt. Der Artikeltext wird dabei so gekürzt, dass die Mengenangabe sicher mit auf der Rechnung erscheint.
- dadurch werden die Preise pro Zeile korrekt abgebildet und übertragen.
- Vorteil: die Änderung wird nicht in Magento selbst gemacht, d.h. die Bestellung / Warenkorb / Konto etc. sind alle mit der ursprünglichen Menge versehen. Nur die Rechnung hat die Texterweiterung. 

Damit fahren wir sehr gut, obwohl wir eine Kalkulationssoftware betreiben, die Produkte mit einem Stückpreis von unter 0,000001ct möglich machen (Druckprodukte).

**Comment by fjbender** [comment]
@dennismax Das klingt sehr gut, vielen Dank für die Idee! Kannst du uns dafür einen PR oder zumindest einen groben Ansatz zur Verfügung stellen?

**Comment by thampe** [comment]
Hallo zusammen,

gibt es hier ggf. neue Entwicklungen?

**Comment by hreinberger** [comment]
Hi @thampe 
leider aktuell noch nicht, aber wir haben das Thema intern nochmal angestoßen und schauen mal, ob @dennismax s Vorschlag gangbar wäre. Falls ja, könnten wir das auf alle Zahlarten ausweiten.

**Comment by hreinberger** [comment]
Hallo zusammen,
wir haben gerade https://github.com/PAYONE-GmbH/magento-1/pull/322 gemerged und würden uns über Feedback freuen! In unseren internen Tests sehen die Ergebnisse gut aus. Danke an @dennismax!
