### ISSUE TITLE
Unused / Unnecessary Code

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#132]
The support just told us that direct authorization is not supported for advance payment. Hence, the observer [`payone_core/observer_transactionStatus_invoiceCreate::onPaid`](https://github.com/PAYONE-GmbH/magento-1/blob/9b2292d9acdec88a7d0ada9d8bb8d33a82fbd919/app/code/community/Payone/Core/Model/Observer/TransactionStatus/InvoiceCreate.php#L82) should be removed completely. Because this observer only creates an invoice for advance payment orders if the autorization method is direct authorization (which is not supported).

In theory, it would be great if the invoice would be created independent of the authorization type, but this is probably nothing you want to do...

**Comment by fjbender** [comment]
I don't think we should remove it completely. As I see it, the `onPaid` observer also is concerned with authorization payments other than advance payment and marks the invoice as paid.

**Comment by sprankhub** [comment]
Ah sorry, you are right. It indeed does other things as well. But at least it should be updated. It says "Advance Payment create Invoice if request-type is authorization", which is not supported as the support told me... But it would definitely be nice if there was an option to authorize advance payment orders directly, so that an invoice is created automatically...

**Comment by fjbender** [comment]
Advance Payment authorization has to be introduced on our platform first. I suppose once it's there, we'll need the code in this observer again, so I'd rather not remove it now just to re-implement it when the authorization feature is available for Advance Payment again.

**Comment by tniebergall** [comment]
@fjbender should we close this issue or leave it to discuss the independent generation if an invoice?

**Comment by fjbender** [comment]
Feature not supported on platform.
