### ISSUE TITLE
Amazon Pay & Facebook Inapp Browser vertragen sich nicht

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#138]
"Browser not supported. This Browser is not supported. Open this page in your device's browser to use your Amazon account, or return to the site to continue to XXX without using your Amazon account."

Wäre ja auch zu schön gewesen... Schade, da für viele Shops Facebook einen signifikanten Anteil des Traffics ausmacht und Amazon Pay vor allem für mobile Conversions wie gemacht ist.

Ich habe den Amazon Pay Button jetzt per User-Agent/HTTP-Header Erkennung ausgeblendet (HTTP_USER_AGENT = "FBAN/" für iOS und HTTP_X_REQUESTED_WITH = "com.facebook." für Android), um Frustration bei den Besuchern und Bestellabbrüche zu verhindern. Wäre vielleicht auch eine sinnvolle Ergänzung für die Extension.

**Comment by fjbender** [comment]
Das klingt für mich erstmal eher nach einer Meldung von Amazon als von uns - ich bin mir nicht sicher, ob wir das beeinflussen können. Leider kann ich das bei mir grad nicht testen, da sich der Facebook InApp Browser weigert, eine Verbindung durch das VPN zu unseren Testshops herzustellen.

Habe das aber mal grade mit Thomann ausprobiert und da bekomme ich im InApp Browser vom Facebook Messenger nach dem Login bei Amazon nur eine weiße Seite.

Kannst du für deine Anpassung einen PR erstellen?

**Comment by gndk** [comment]
Ja ist eine Meldung von Amazon und Ihr habt keinen Einfluss drauf. Nur für die User Experience wäre es eben besser wenn die Zahlungsart dann gar nicht angeboten wird.

Ja, mache ich gleich.

**Comment by gndk** [comment]
PR #143

**Comment by gndk** [comment]
Solved by #147
