### ISSUE TITLE
Amazon Pay in der Kasse

### ISSUE THREAD

**Issue by borishaefele** [PAYONE-GmbH/magento-1#153]
Hallo, kann man bitte Amazon Pay so einstellen, dass man es nicht nur als Express Checkout Button im Warenkorb implementieren kann, sondern so wie alle Zahlarten auch in der "normalen" Kasse? Danke

**Comment by fjbender** [comment]
So wie uns Amazon Pay dargestellt wurde, ist das eigentlich nicht vorgesehen. Ist das bei anderen Amazon Pay Integrationen so eingebaut?

**Comment by borishaefele** [comment]
Ja, z.B. https://www.engelhorn.de macht das auch so…

____________________________

Dr. Boris Häfele | Roast Market 
Co-CEO & Founder 
boris.haefele@roastmarket.de
Moselstraße 27
60329 Frankfurt am Main
Tel: +49 (0) 69 34876162
www.roastmarket.de

**Comment by gndk** [comment]
Ich wollte das ursprünglich auch so haben, habe aber schnell gemerkt, dass der eigentliche Vorteil von Amazon Pay ist, dass eben keine Adressdaten eingegeben werden müssen. = höhere CR

**Comment by fjbender** [comment]
Den Vorteil sehe ich nämlich so auch, aber wir besprechen das Thema nochmal mit Amazon.

**Comment by sprankhub** [comment]
Der eigentliche Vorteil ist sicherlich, dass Adressdaten übernommen werden. Aber ich finde es jetzt auch nicht soo uninteressant, nur die Payment Daten zu übernehmen...

@fjbender Wann können wir mit einer aktuellen Info rechnen?

**Comment by sprankhub** [comment]
Bump :-)

**Comment by fjbender** [comment]
Hier warten wir noch auf Feedback von Amazon. Die reine Übernahme von Paymentdaten klappt auf deren Seite noch nicht.

**Comment by sprankhub** [comment]
Irgendwelche Neuigkeiten?

**Comment by fjbender** [comment]
Ich habe von Amazon in dieser Richtung noch nichts gehört.

**Comment by borishaefele** [comment]
Hi, gibt's hier irgendwelche Neuigkeiten von Amazon in der Zwischenzeit? Ist ja jetzt schon ne Weile her. Wäre für Kunden extrem wichtig, da Amazon Pay sehr intensiv genutzt wird.

**Comment by sprankhub** [comment]
Was ist denn hieraus geworden, @fjbender?

**Comment by fjbender** [comment]
Moin, leider sieht unsere Anbindung an Amazon Pay die reine Payment-Funktion nicht vor. Es muss immer auch mit der Adressübernahme gearbeitet werden. :/
