### ISSUE TITLE
Fehler bei Kreditkarten Zahlart - Cannot read property 'value' of null

### ISSUE THREAD

**Issue by luxmedia** [PAYONE-GmbH/magento-1#155]
Im Checkout Prozess im Bereich der Zahlungsart ist der Radio-Button bei "Kreditkarte" nicht sichtbar und im Formular (hosted iframe) fehlt das Eingabefeld für die Prüfnummer. Die Eingabefelder für das Datum werden jedoch geladen. Zudem erscheint immer beim Wechsel des Kredikarten-Typs folgender Fehler in der Konsole:

`
Uncaught TypeError: Cannot read property 'maxlength' of undefined
    at M (payone_hosted_min.js:33)
    at Payone.ClientApi.HostedIFrames.setCardType (payone_hosted_min.js:38)
    at HTMLSelectElement.document.getElementById.onchange (creditcard.js:97)
M	@	payone_hosted_min.js:33
setCardType	@	payone_hosted_min.js:38
document.getElementById.onchange	@	creditcard.js:97
`

Das Problem betrifft die derzeit aktuelle Version von Payone (3.7.8) sowie Magento 1.8.1.0.

Grüße
Volker Lux

**Comment by fjbender** [comment]
Hier könnte wahrscheinlich am ehesten unser Technischer Support helfen. Bitte einmal unter 0431/25968-500 oder tech.support@bspayone.com melden. Falls die das Problem nicht lösen können, schaue ich gern nochmal drauf.

**Comment by tniebergall** [comment]
@luxmedia hab ihr eventuell Templates des Moduls überschrieben? Es gab in der Version 3.7.8 einige BCs.

**Comment by agierloff** [comment]
Hallo,
wir können das Problem der fehlenden Prüfnummer nachvollziehen. 
Wir fahren bei einem Kunden von uns Magento 1.9.2.0 mit der Payone Version 4.1.4.
Bei einem anderen Magento 1.9.3.8 mit Payone Version 4.1.1

Wenn wir das Modul so konfigurieren, dass die hosted-iframe Lösung für die Kredikarte aktiviert ist und gleichzeitig die Kreditkarten Einstellung "Prüfe Kartenprüfnummer" auf "Nein" steht, wird das Feld im Frontend nicht korrekt ausgeblendet. Das Input Iframe wird (korrekterweise) nicht gefüllt. Der Rest wird allerdings angezeigt.

![auswahl_071](https://user-images.githubusercontent.com/22540888/38495394-ac5f38f6-3bf9-11e8-99b1-6c71b464f99c.png)

Ein Switchen der Kreditkarte führt dann zu dem oben genannten Fehler 

![auswahl_073](https://user-images.githubusercontent.com/22540888/38495483-05e30ee8-3bfa-11e8-83ce-4ad4d7af29b4.png)

Ist die Prüfung der Kreditkartennummer aktiviert, gibt es keinen Fehler.
Wir konnten den Fehler in beiden Shops feststellen.

Viele Grüße,
Josh

**Comment by fjbender** [comment]
Wurde mit #194 gefixt.
