### ISSUE TITLE
Not compatible with onestepcheckout

### ISSUE THREAD

**Issue by gulshan-streammarket** [PAYONE-GmbH/magento-1#156]
We are using your extension but this is not working with [onestepcheckout ](https://marketplace.magento.com/onestepcheckout-idev-onestepcheckout.html)developed by IDEV.
Is it possible for you to make this extension compatible with onestepcheckout.

Thanks

**Comment by fjbender** [comment]
@gulshan-streammarket Can you be more specific on "is not working"? I'd like to have an exact angle here on which to look.

**Comment by gulshan-streammarket** [comment]
@fjbender the main issue come up with payment methods that take input from the customer while payment step. For example, CC has form with input fields and giropay have two fields. It seems with onestepchecout PAYONE module is unable to get that field values to send it to PAYONE gateway. Hope this will help you to identify the issue. Thanks

**Comment by fjbender** [comment]
@gulshan-streammarket Unfortunately, we're unable to obtain a license for this module so can't check the exact problems. Sorry for this. Maybe IDEV support can contact us and work something out.

**Comment by madismanni** [comment]
Hi!

Please contact support@onestepcheckout.com and we will inspect the issue. Normally payone should be compatible with onestepcheckout.com module, we have a patch for it.

**Comment by madismanni** [comment]
Unfortunately, we're unable to obtain a license for this module so can't check the exact problems. Sorry for this. Maybe IDEV support can contact us and work something out.

?? I have not received such request, can you please contact support@onestepcheckout.com ?

**Comment by Backenkoehler** [comment]
Any updates here? We right now have problems with sofortüberweisung (payone) and OneStepCheckout

**Comment by madismanni** [comment]
Hi!

If you have issues please write description of exact issue to
support@onestepcheckout.com and make sure you have a valid support and
update plan. Support will debug your issue. Such issues need to be debugged
individually.
*Best regards,*
*Madis*
