### ISSUE TITLE
Amazon Payment  Array Key not set "port"

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#158]
Falsche Uhrzeit für einen PR :-/

2018-02-07T22:53:58+00:00 ERR (3): Notice: Undefined index: port  in /var/www/htdocs/app/code/community/Payone/Core/Block/Adminhtml/System/Config/Form/Field/AmazonConfig.php on line 37

    $element->setData('value', 'https://' . $url['host'] . (isset($url['port']) ? ':' . $url['port'] : ''));

vs Original (da fehlt das isset)

    $element->setData('value', 'https://' . $url['host'] . ($url['port'] ? ':' . $url['port'] : ''));

**Comment by sprankhub** [comment]
Schon gefixt: https://github.com/PAYONE-GmbH/magento-1/pull/152 ;-)

**Comment by fjbender** [comment]
Fixed with #152.
