### ISSUE TITLE
Amazon Pay Daten werden nicht übernommen

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#159]
Moin, wenn ich auf getConfigutation klicke bei Amazon Pay, wird zwar der Request gemacht (steht im Log), aber die Felder für die Seller und Client ID bleiben leer.

Ich habe das jetzt direkt in die DB gehackt und teste mal weiter. Aber irgendwas hakt da noch.

**Comment by sprankhub** [comment]
Ich glaube @norgeindian hatte ein ähnliches Problem. Weiß aber nicht mehr, woran es bei ihm lag...

**Comment by gndk** [comment]
Ich hatte das Problem auch, lag bei mir daran, dass die .sql-upgrade Dateien fehlerhaft waren und ich die entsprechenden Spalten in der DB manuell anlegen musste. Danach gings.  Siehe #136

**Comment by fjbender** [comment]
@Schrank Waren die Felder bei dir in der DB vorhanden? Gabs im getconfiguration Request irgendwelche Fehler?

**Comment by Schrank** [comment]
@fjbender Der Shop war kaputt, d.h. zuerst warten die Felder nicht da, aber selbst nachdem sie da waren und der Cache gelöscht war, wurden sie nicht befüllt - keine Ahnung warum. Aber wenn ich der einzige mit dem Problem bin, machen wir das Ticket einfach zu :)
