### ISSUE TITLE
Answer from Server with coding problem

### ISSUE THREAD

**Issue by Nasatya** [PAYONE-GmbH/magento-1#16]
Hello,

the extension is sending this response asnwer to Payone:

ï»¿TSOK

Could you please help me why this happens. I was reading its UTF-8 problem, but i could find the file that would have the wrong encoding. The right response should be without the "ï»¿" and now the whole Payment is not working accordingly.

https://en.wikipedia.org/wiki/Byte_order_mark

Thank you very much for your help.

**Comment by fjbender** [comment]
The ï»¿ usually appears when a BOM is sent but the content is believed to be ISO-8859 encoded. Please make sure your server sends the right encoding header when the Payone platform pushes the transaction status.

**Comment by fjbender** [comment]
No response for 14 days.
