### ISSUE TITLE
duplicate header 'Content-Type'

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#163]
"Get configuration" für Amazon Pay fliegt mir mit meinem Apache um die Ohren.

    FastCGI: comm with server "/Applications/MAMP/fcgi-bin/php5.6.32.fcgi" aborted: error parsing headers: duplicate header 'Content-Type'

I add a patch with all setHeads fixed I found:

[content-type.txt](https://github.com/PAYONE-GmbH/magento-1/files/1740557/content-type.txt)

**Comment by fjbender** [comment]
We'll look at the patch and apply it. Thanks!

**Comment by fjbender** [comment]
@Schrank we couldn't reproduce this issue (maybe it's MAMP only?) but have applied the patch anyway, see #164. Can you confirm this fixes the issue on your side?

**Comment by Schrank** [comment]
I think it happens with php in cgi mode, not with fpm and not with apache module.

Problem fixed!
