### ISSUE TITLE
Magento patch SUPEE 10570 cause display error

### ISSUE THREAD

**Issue by Sveni81** [PAYONE-GmbH/magento-1#170]
On the Orderdetailspage in the left menü will be html printed out. The patch correct diffrent output threatment which could cause the problem.

**Comment by Sveni81** [comment]
![bildschirmfoto 2018-03-01 um 11 26 19](https://user-images.githubusercontent.com/25319974/36839823-694aa61a-1d43-11e8-8c4a-038dc0d0f3d8.png)

**Comment by sprankhub** [comment]
Fixed in https://github.com/PAYONE-GmbH/magento-1/commit/c1ba6b8962efe4fdf8b3684c8f6185354245f4c1.
