### ISSUE TITLE
PAYONE API certificate update

### ISSUE THREAD

**Issue by gulshan-streammarket** [PAYONE-GmbH/magento-1#178]
Hello,

We have received a newsletter from PAYONE team to update API certificate. They also have mentioned "Server systems which are using cURL (e.g. PHP with libcurl) or OpenSSL are usually not affected.". We just want to make sure whether this module will be affected by this or not.

Thanks

**Comment by fjbender** [comment]
The module will not be affected. In this implementation, we trust on the system wide list of CAs. As our certificate is and always will be issued by a large CA, it will continue to work without any problems.

Best
Florian

**Comment by gulshan-streammarket** [comment]
Many Thanks
