### ISSUE TITLE
Invalid argument supplied for foreach CcHostedTranslations.php

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#18]
In version 3.7.0, I get the following error/warning in the system.log:

    2016-12-07T06:38:41+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in app/code/community/Payone/Core/Model/Config/General/CcHostedTranslations.php on line 34

The reason should be the following:

- We did not configure any translations.
- app/code/community/Payone/Core/Model/Config/General/CcHostedTranslations.php line 34 iterates over all given translations.
- If you check the calls of `_formatTranslationArray` in the same class, it will be called (among others) with `unserialize($this->cc_translation_months)`.
- The `cc_translation_months` are not set anywhere. The default value is `''`.
- `unserialize('')` results in `false`.
- Hence, the foreach will be called with a false resulting in the logged warning.

Not sure how you want to fix it, but a simple check of the `$aTranslations` parameter should be enough.

**Comment by fjbender** [comment]
@sprankhub Should be a simple fix, but just to be sure the bug is not located elsewhere: What's the value for the path payone_general/cc_hosted_translations/cc_translation_months in your core_config_data table? For me its an empty serialized Array `a:0:{}`, for you it should be empty or the key non-existant.

**Comment by sprankhub** [comment]
mysql> SELECT * FROM `core_config_data` WHERE `path` = 'payone_general/cc_hosted_translations/cc_translation_months';
    Empty set (0.01 sec)

I guess this is because I never saved the config since these new config values are present.

Thanks for the fix!
