### ISSUE TITLE
Wrong Exception for Some Shopgate Orders

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#181]
In https://github.com/PAYONE-GmbH/magento-1/commit/7c7ebdde9e3ebc36f1df8e842b0f19981db4e487 and https://github.com/PAYONE-GmbH/magento-1/commit/c3b4c237deaeed2e34fcd00081f357033c1bb853, we theoretically fixed the issue that the `exception.log` is cluttered with entries like this:

    2018-03-12T09:46:32+00:00 ERR (3): 
    Payone_Core_Exception_OrderNotFound: Could not find an order for reference "SG0123456789". in /var/www/share/roastmarket.de/htdocs/app/code/community/Payone/Core/controllers/TransactionStatusController.php:67

Unfortunately, the log entry still appears. The issue is that the transaction status could be received before the Shopgate order has been imported. Hence, `Payone_Core_Helper_Compatibility::isExternalOrderReference` returns false. In this method, we currently check if there is a Shopgate order in Magento with the given reference. I suggest to use a much simpler check. We could simply check if the order number begins with "SG". I think it is safe enough to do this. This CAN go wrong if a shop defined custom order numbers and let them begin with "SG" as well, but I guess this is rather rare. What do you think? If you would like to have a safer way, we could check for "SG" at the beginning AND a reference length of 12. I think all Shopgate references are 12 chars long.

**Comment by fjbender** [comment]
I suppose this should be safe enough. Would you provide a PR and adapt your code accordingly?

Thanks

**Comment by sprankhub** [comment]
Yes, I will. Which option do you prefer @fjbender? Just checking for "SG" prefix or checking the prefix PLUS checking the reference length?

**Comment by fjbender** [comment]
I'll check with Shopgate if the order number length is somewhat stable and then make a decision.

**Comment by fjbender** [comment]
Unfortunately, there's no feedback from Shopgate yet.

**Comment by fjbender** [comment]
@sprankhub Shopgate confirmed that they're going to retain the SG prefix and the length of the order number, so it should be sufficient to test for that.
