### ISSUE TITLE
Notice: unserialize() in Model/Domain/Protocol/TransactionStatus.php

### ISSUE THREAD

**Issue by phoenix-schwarz** [PAYONE-GmbH/magento-1#182]
We are having the following issue several times a day in the logs:

Notice: unserialize(): Error at offset 543 of 1115 bytes  in /var/www/project/htdocs/app/code/community/Payone/Core/Model/Domain/Protocol/TransactionStatus.php on line 314

Could you please let us know any possible reason? For me this means, that we have invalid serialized data for whatever reason.

see: https://davidwalsh.name/php-serialize-unserialize-issues

**Comment by fjbender** [comment]
Hi,

Thank you for your contribution in #183.

However, before merging the PR, I'd like to find out why the message appears in the first place. Do you have any access to the "invalid" string that is supposed to be unserialized at that point?

Thanks
Florian

**Comment by phoenix-schwarz** [comment]
Yes, I have a log with a few cases. As it is sensitive data, I would prefer to send you an e-mail with a few samples.

**Comment by phoenix-schwarz** [comment]
BTW: I think that the issue is related to characters like: ø and å as all the samples are containing characters like this.

**Comment by phoenix-schwarz** [comment]
https://stackoverflow.com/questions/2853454/php-unserialize-fails-with-non-encoded-characters

**Comment by phoenix-schwarz** [comment]
I anonymized the string:

`a:37:{s:3:"key";s:32:"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";s:8:"txaction";s:9:"appointed";s:8:"portalid";s:7:"XXXXXXX";s:3:"aid";s:5:"XXXXX";s:12:"clearingtype";s:2:"cc";s:14:"notify_version";s:3:"7.4";s:6:"txtime";s:10:"1521525598";s:8:"currency";s:3:"DKK";s:6:"userid";s:9:"1XXXXXXXX";s:10:"accessname";s:0:"";s:10:"accesscode";s:0:"";s:5:"param";s:0:"";s:4:"mode";s:4:"live";s:5:"price";s:6:"352.90";s:4:"txid";s:9:"264438520";s:9:"reference";s:9:"SDK127812";s:14:"sequencenumber";s:1:"0";s:7:"company";s:0:"";s:9:"firstname";s:10:"CXXXXXXXX ";s:8:"lastname";s:6:"XXXXX ";s:6:"street";s:10:"Rødbyvej 4";s:3:"zip";s:4:"4XXX";s:4:"city";s:8:"RXXXXXXX";s:5:"email";s:28:"XXXXXXXXX__XXXXX@hotmail.com";s:7:"country";s:2:"DK";s:16:"shipping_company";s:0:"";s:18:"shipping_firstname";s:10:"CXXXXXXXX ";s:17:"shipping_lastname";s:6:"KXXXX ";s:15:"shipping_street";s:10:"Rødbyvej 4";s:12:"shipping_zip";s:4:"4XXX";s:13:"shipping_city";s:8:"RXXXXXXX";s:16:"shipping_country";s:2:"DK";s:14:"cardexpiredate";s:4:"2109";s:8:"cardtype";s:1:"V";s:7:"cardpan";s:16:"4XXXXXxxxxxxXXXX";s:7:"balance";s:1:"0";s:10:"receivable";s:4:"0.00";}`

**Comment by phoenix-schwarz** [comment]
The question is are those orders processed correctly or not?

**Comment by fjbender** [comment]
Great, many thanks. We'll hopefully figure out a way around this. I'll validate as well whether the transaction processing is affected by this or not (as first sight it looks good, but I'll make sure).

**Comment by fjbender** [comment]
We solved this by switching to JSON with #187. Can you confirm this solution?

**Comment by phoenix-schwarz** [comment]
I'll check, but the code for me looks good, except my comment to use `@unserialize` etc, to avoid further Notices in the logs
