### ISSUE TITLE
Sofortüberweisung and Credit Card don'tt work

### ISSUE THREAD

**Issue by atsareva** [PAYONE-GmbH/magento-1#189]
Hi guys!

**Preconditions**

- Magento 1.9.3
- Ubuntu 16.04 lts
- Percona
- Apache

I've configured the next payment methods 

1. PayPal
2. Rechnung (Invoice)
3. Lastschrift (debit)
4. Sofortüberweisung
5. Kreditkarte (Credit Card)
6. Vorkasse (Advance Payment)

and all works fine except **Sofortüberweisung** and **Kreditkarte** methods.

**Sofortüberweisung**
Customer is redirected to the https://www.sofort.com/payment/multipay/error url with error
> The transmitted input hash does not correspond to the input hash calculated by us. If you are the shop operator, please check the project password in your shop system. It must match the project password in your merchant menu.

Regarding **Kreditkarte**
I see the next error in the exception.log

> 2018-03-24T15:03:19+00:00 ERR (3):
> exception 'Payone_Core_Exception_PaymentMethodConfigNotFound' with message 'Payment method configuration for method "payone_creditcard" not found.' in /var/www/textil-one.loc/public_html/app/code/community/Payone/Core/Helper/Config.php:140
> Stack trace:
> #0 /var/www/textil-one.loc/public_html/app/code/community/Payone/Core/Model/Payment/Method/Abstract.php(203): Payone_Core_Helper_Config->getConfigPaymentMethodByOrder(Object(Fooman_EmailAttachments_Model_Order))
> #1 /var/www/textil-one.loc/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(328): Payone_Core_Model_Payment_Method_Abstract->getConfigPaymentAction()
> #2 /var/www/textil-one.loc/public_html/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
> #3 /var/www/textil-one.loc/public_html/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
> #4 [internal function]: Mage_Sales_Model_Order->place()

As I understand this happens due to '**payone_customer**' because it's empty, but I don't now which data should be there.

Please help me :)

Thanks,
Alona Tsarova

**Comment by fjbender** [comment]
Hi Alona,

this doesn't really look like a module bug to me. Have you talked to our Technical Support team already?

**Comment by fjbender** [comment]
Hi,

in my test setup, the payone_customer table is empty too and credit card works, so I suppose this is a configuration error. If the error persists after Tech Support has checked your configuration, I'll take another look :)

**Comment by atsareva** [comment]
Okay, thank you!
