### ISSUE TITLE
Failed opening Hint.php

### ISSUE THREAD

**Issue by jg-development** [PAYONE-GmbH/magento-1#190]
Hi,
I have a Problem with the Payone Core Version 3.7.8 and Magento 1.9.3.8.
I am getting sometimes errors like these:
```
13877863-2018-03-28T22:25:59+00:00 DEBUG (7): Time for Answering HTTPRequest: 0.17383289337158203 from the url: /checkout/cart/add/uenc/xxx,/product/24697/form_key/xxx/
13877864:2018-03-28T22:26:01+00:00 ERR (3): Warning: include(Payone/Core/Model/Config/Protect/Hint.php): failed to open stream: No such file or directory  in xxx/htdocs/lib/Varien/Autoload.php on line 94
13877865:2018-03-28T22:26:01+00:00 ERR (3): Warning: include(): Failed opening 'Payone/Core/Model/Config/Protect/Hint.php' for inclusion (include_path='xxx/htdocs/app/code/local:xxx/htdocs/app/code/community:xxx/htdocs/app/code/core:xxx/htdocs/lib:.:/usr/local/lib/php')  in xxx/htdocs/lib/Varien/Autoload.php on line 94
```
Often after a add product to basket call, but not always. I am currently not able to reproduce this issue, but maybe you can find a way to reproduce it.
As far as I can see the hint.php should only be loaded in the admin section but the extension is trying to load it in the frontend.
Greetings Jan

**Comment by fjbender** [comment]
Hi,

This is really odd and I can't reproduce it as well. Is there any way to obtain a stack trace?

**Comment by jg-development** [comment]
Hi,
I will see, that I install a log entry with a stack trace this week.

**Comment by jg-development** [comment]
Hi, this seems to be an error only with hhvm and not php7, so I think I will close this.
Thanks Jan
