### ISSUE TITLE
HTML-Code in Bestellansicht-Tabs nach SUPEE-10570

### ISSUE THREAD

**Issue by nofrillswebdesign** [PAYONE-GmbH/magento-1#195]
Mit dem letzten Patch, SUPEE-10570, wird der Inhalt von Admin-Tabs escaped, so dass in den Payone-Tabs der Bestellansicht der HTML-Code des 'span' statt dem kleinen Logo angezeigt wird.
Mage/Adminhtml/Block/Widget/Tabs.php - Zeilen 292 & 294

**Comment by fjbender** [comment]
Das wurde bereits mit #180 gefixt.
