### ISSUE TITLE
Fatal Error in Cart

### ISSUE THREAD

**Issue by mSengera** [PAYONE-GmbH/magento-1#200]
Hey,
i have following Error on Cart page:

Parse error: syntax error, unexpected '[' in /app/code/community/Payone/Core/Model/Payment/Method/Abstract.php on line 229

Best regards,
Marvin Sengera

**Comment by fjbender** [comment]
Which version are you using? In https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Payment/Method/Abstract.php#L229 I can't find any '['. Additionally, which PHP version are you using?

**Comment by mSengera** [comment]
Hey,
we use the Payone 4.1.4 release.
Further we use PHP 5.6.

I can't find an additional '[' in our code, too.

**Comment by fjbender** [comment]
I can't reproduce the error on any Magento version with either v4.1.4 or the current master on a PHP 5.6 system. :disappointed: The entire block (lines 223-233) was introduced with 502818215854ef877898ba4ff85e0d2464b78e26. Can you comment out this block and try again?

**Comment by mSengera** [comment]
Now i get following Error:
Parse error: syntax error, unexpected '[' in /var/www/vhosts/mein-teller.de/httpdocs/dev/app/design/frontend/base/default/template/payone/core/amazon/pay/shortcut.phtml on line 30

**Comment by mSengera** [comment]
Ok i fixed this error on my own.

Change Line 30 from
$returnUrl = Mage::getUrl('payone_core/amazonpay/checkout', ['_nosid' => true, '_forced_secure' => true)];
to
$returnUrl = Mage::getUrl('payone_core/amazonpay/checkout', array('_nosid' => true, '_forced_secure' => true));

**Comment by mSengera** [comment]
I had checked the server again...

I'm sorry. We run following PHP Version: 

PHP Version 5.3.10-1ubuntu3.26

**Comment by fjbender** [comment]
From the [PHP Documentation](http://php.net/manual/en/language.types.array.php)
> As of PHP 5.4 you can also use the short array syntax, which replaces array() with [].

We require at least PHP 5.4 (which itself is really, really old).
