### ISSUE TITLE
Cron job was running for more than one hour

### ISSUE THREAD

**Issue by gulshan-streammarket** [PAYONE-GmbH/magento-1#201]
We have seen cronjob timeline and found cronjob payone_core_cronjob_transactionstatus_process was running for more than one hour. Also executed successfully.
![cron was running for more thank hour](https://user-images.githubusercontent.com/32667915/39238140-1a41cd5e-489b-11e8-9b26-6eca75081823.png)

**Comment by fjbender** [comment]
Okay, that is weird. Has anyone else ever seen this behavior?

**Comment by gulshan-streammarket** [comment]
We have got the issue, the cron jobs were affected by some other cron job changing time zone at run time. It's not a module's bug.
Thanks
