### ISSUE TITLE
PayPal Express in Cart - Skip Review Page

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#204]
It is possible to show a PayPal Express button on the cart page by activating `payone_general/payment_paypal_express_checkout/paypal_express_checkout_visible_on_cart`. When clicking it and completing the payment at PayPal, the user is redirected to a review page at the shop, where he needs to submit the order. My customer wants to skip the review page. The order should directly be submitted and the user should be redirected to the checkout success page directly after he returns from PayPal.
I have my doubts that this is permitted by law, but I am not a lawyer :-)

Is that currently possible somehow? If not, is that planned? If not, do you have any hints how this could be achieved?

**Comment by sprankhub** [comment]
Pity. Most of the shops I know only have one shipping option anyway, so this should be possible. One could have a configuration option to select the default shipping option for PPE as well. I will get back to the customer and see if he wants to have this implemented.

**Comment by sprankhub** [comment]
Are you sure you do not want to implement that? :-)

**Comment by fjbender** [comment]
Yes - the requirements document from when we first introduced PayPal Express stated, that Terms & Conditions, Widerrufsbelehrung etc. have to be displayed before finalizing the transaction.

I see how this would speed up the checkout process and increase convenience for buyers, but it would pose a risk for merchants not familiar with legal requirements. Sorry.
