### ISSUE TITLE
CRIT (2): Not valid template file:adminhtml/base/default/template/payone/core/payment/method/form/amazonpay.phtml

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#207]
CRIT (2): Not valid template file:adminhtml/base/default/template/payone/core/payment/method/form/amazonpay.phtml

I'm getting a lot of these errors in my system.log. The file doesn't exist in the repo but its called somewhere. I'm using Magento 1.9.3.8 and Payone 9e2aef2

I can only find the frontend calls in app/code/community/Payone/Core/Block/Payment/Method/Info/AmazonPay.php and app/code/community/Payone/Core/Block/Payment/Method/Form/AmazonPay.php.

Any idea?

**Comment by gndk** [comment]
I guess thats where its coming from (Admin create order): https://screencast.com/t/KcSm82HRI

But Amazon Pay shouldn't even appear there as its not possible for the Admin to create an order using Amazon Pay.

**Comment by fjbender** [comment]
Thanks. We'll fix this.
