### ISSUE TITLE
Subscriptions / Recurring Payments

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#218]
A customer wants to offer subscriptions for many products. Does the PAYONE Magento plugin offer some form of recurring payment support?

**Comment by fjbender** [comment]
Currently I don't know of any customer using our extension this way, sorry. In theory it should be possible to use the pseudo card numbers, stored IBANs, invoice information and the like to create a recurring payment module using our code for communication to the Payone API.
