### ISSUE TITLE
AdBlocker blockt pay1.js - chaotisches Verhalten

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#219]
Ich habe PrivacyBadger installiert, was vieles wegblockt, unter anderem manchmal die pay1.js (heißt die so?).

Das führet zu komischem Verhalten. Bei einem Kunden nimmt das System zwar die richtige Payment-Methode denkt aber trotzdem, dass es Nachnahme ist und fügt Gebühren hinzu.

Heute beobachtet mit 4.1.6: Man kommt durch den Checkout, im Review fliegt einem aber das System um die Ohren mit `"Payment method configuration for method "payone_advance_payment" not found."` (alle anderen Methoden gehen auch nicht).

Das erste Problem ist, dass gefühlt _ALLE_ Formularfelder des Payments mitgeschickt werden, d.h. auch etliche "payone_method_config_id" und Kreditkartenkonfiguration, obwohl es Vorkasse ist.
Das zweite Problem habe ich nicht analysiert.

Der einfachste Weg das Problem zu lösen wäre, die pay1.js nicht extern nachzuladen - was das Updaten sicher erheblich schwieriger macht. Bessere Ideen sind willkommen.

**Comment by Schrank** [comment]
Ich habe eine (die auch doof ist, aber besser): Man lädt die pay1.js auf dem Server via PHP und "cacht" sie. So wird sie aktualisiert, aber von der gleichen URL geladen.

**Comment by fjbender** [comment]
Meinst du dieses JS https://secure.pay1.de/client-api/js/v1/payone_hosted_min.js ? Ich würde mich schwer damit tun, die im Shop zu cachen.

Grundsätzlich sollte das im Algorithmus von PrivacyBadger aber auch nicht besonders auffallen. Interessanterweise setzen wir aber ein PHPSESSID Cookie, das wir IMHO nicht brauchen. Vielleicht wird das als Tracking-Cookie interpretiert. Ich schaue mal, ob wir verhindern können, dass das gesetzt wird (zumindest bei aktiviertem DNT Flag).

**Comment by Schrank** [comment]
Genau das. Und wenn ihr den Cookie nicht braucht, lasst ihn einfach immer weg 😊 Es gibt bestimmt TrackingBlocker Benutzer da draußen ohne DNT.

**Comment by fjbender** [comment]
Wir haben jetzt immerhin eine Story für unsere Entwicklung - die Prio ist allerdings nicht so hoch gesetzt worden (aber es geht voran).

**Comment by fjbender** [comment]
Soo, ich habe mich jetzt mit einem unserer Entwickler hier ganz schön lange durchgewühlt und wir können es nicht systematisch reproduzieren. Auf manchen Systemen wird das Cookie gesetzt, auf manchen nicht. Wir haben einige Logs durchwühlt, fanden aber keinen passenden `Set-Cookie` Header, um es auf einen speziellen Request gegen secure.pay1.de einzugrenzen.

Hast du zufällig herausgefunden, bei welchem Request genau das Cookie gesetzt wird?
