### ISSUE TITLE
AmazonPay: Adresse im Checkout unbekannt -> auch in Warenkorbpreisregeln

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#220]
Wir haben eine Warenkorbpreisregel für kostenlosen Versand nach Deutschland:

![image](https://user-images.githubusercontent.com/379680/41812828-d2d11ede-772a-11e8-9876-9e68a0c16c16.png)

Diese ist auf Deutschland eingeschränkt. Im AmazonPay Checkout ist aber die Adresse unbekannt, daher auch das Land und damit greift die Regel nicht.

Ich habe keine Idee wie man das fixen kann. Irgend eine Chance an die Adresse zu kommen?

P.S.
Magento steigt hier aus, weil die Address leer ist. Kein Land, keine Straße, etc. (woher auch... ist ja alles im iframe):

    \Mage_SalesRule_Model_Validator::processFreeShipping
    public function processFreeShipping(Mage_Sales_Model_Quote_Item_Abstract $item)
    {
        $address = $this->_getAddress($item);
        $item->setFreeShipping(false);

        foreach ($this->_getRules() as $rule) {
            /* @var $rule Mage_SalesRule_Model_Rule */
            if (!$this->_canProcessRule($rule, $address)) {
                continue;
            }

**Comment by fjbender** [comment]
Eigentlich haben wir die Adresse nachdem `\Payone_Core_Model_Service_Amazon_Pay_Checkout::confirmSelection` (https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php#L113) ausgeführt wurde. Wie ich das sehe, sollte das beim Wechsel in den finalen Schritt passieren.

Vielleicht schreiben wir diese Info "zu spät" an Magento, sodass die Regeln bereits gelaufen sind?

**Comment by Schrank** [comment]
Genau, wir reduzieren den Versand, da brauchen wir die Adresse :-)

**Comment by fjbender** [comment]
Das ist klar ;) Weißt du, wann genau `processFreeShipping` aufgerufen wird, idealerweise verglichen zu `confirmSelection` von uns?

**Comment by Schrank** [comment]
processFreeShipping wird während des add to Cart aufgerufen und wenn ich die Warebkorbseite lade (also lange vor dem Checkout)

confirmSelection wird vor dem letzten Schritt aufgerufen, also nach Adress und Paymenteingabe und DANACH kommt processFreeShipping, aber leider ist die Adresse leer. Die billing-Address sieht genau so aus. Leer. Kein Name, Street, etc.

![bildschirmfoto 2018-06-27 um 13 00 07](https://user-images.githubusercontent.com/379680/41970155-156dd03e-7a0a-11e8-9398-4b58fa885eb1.png)
![bildschirmfoto 2018-06-27 um 13 00 13](https://user-images.githubusercontent.com/379680/41970154-154fcdd2-7a0a-11e8-8bd9-4d1873fe44c8.png)

**Comment by Schrank** [comment]
Warte! Danach kommt noch ein Aufruf von processFreeShipping - ich melde mich :D

**Comment by Schrank** [comment]
Ok, EIGENTLICH sollte es klappen. Aber Magento "cacht" in `\Mage_SalesRule_Model_Rule::$_validatedAddresses` ob die Validierung durchlief. Beim ersten Versuch fehlt die Adresse, beim zweiten ist sie da, aber da ist das Kind schon in den Brunnen gefallen.

Ich habe jetzt 2h geschaut, WO dieser Eintrag in `\Mage_SalesRule_Model_Rule::$_validatedAddresses` gemacht wird und finde es nicht. Die einzige Stelle, die in die Property schreibt wird laut xdebug nicht angesprungen.

Direkt am Anfang von `\Mage_SalesRule_Model_Validator::_canProcessRule` steigt unsere Regel beim zweiten Mal aus, wenn sie eigentlich durchlaufen würde.

**Comment by fjbender** [comment]
Danke dir für die detaillierte Recherche!

Ich kippe das mal bei unser Entwicklung ein und schaue, dass wir da etwas machen können.

**Comment by fjbender** [comment]
Moin @Schrank, wir haben das "einfach" mit einer Codebewegung in #239 gelöst und es klappt dann auch mit der Warenkorbregel.

Willst du das nochmal kurz gegentesten? Wir konnten da keine weiteren Merkwürdigkeiten feststellen.
