### ISSUE TITLE
Missing Event checkout_submit_all_after For PayPal Express In Cart

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#223]
For nearly all payment methods, the event `checkout_submit_all_after` is dispatched. The event is used by various extensions like [Bubble_StockMovements](https://github.com/jreinke/magento-stock-movements/blob/9597d2de4db2f3445447c59e4bb1d29240d29452/app/code/community/Bubble/StockMovements/etc/config.xml#L46-L53). Unfortunately, if the customer uses PayPal Express directly in the cart, the event is not dispatched, which leads to issues with such extensions.

Is there any reason why you do not throw the event in this case? Could you add it?

By the way, I saw that the event is already explicitely dispatched for [Amazon Pay](https://github.com/PAYONE-GmbH/magento-1/blob/15a67dfa6e6f8bf754e74cef61e9e5f32ba1f057/app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php#L364-L367)...

**Comment by fjbender** [comment]
It was probably just forgotten. We'll add it.

**Comment by sprankhub** [comment]
Awesome. Should work I think. We can give you feedback after a new release has been created with this fix.

**Comment by shimonah** [comment]
This event is missing in magento 2.3.5-p1 version.
