### ISSUE TITLE
Amazon Pay broken by basket-amount check

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#230]
88a0ad850f75f6cbd79b2d6fa8a75ce7adbe239c breaks Amazon Pay for me (Line 315-319 in app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php). The same check does not cause problems for PayPal. 

Mage 1.9.3.9 + Payone 4.1.7

I commented out the check for Amazon for the time being but this is obviously just a temporary solution.

Any ideas how to investigate this?

**Comment by fjbender** [comment]
Amazon Pay was green in our tests for 4.1.7. However, I have some customers reporting issues with Amazon Pay since then.

I'm not quite sure what the angle here could be, to be honest. I suppose that we somehow can't validate the grand total of the order through the session. Do you have any way of tracing the `PayoneGenericpaymentSubtotal` in the checkout session?

**Comment by sprankhub** [comment]
I have exactly the same issue. Upgrading from PAYONE 4.1.6. to 4.1.7 breaks Amazon Pay. The customer gets the message "Sorry, your transaction with Amazon Pay was not successful. Please try again.".

**Comment by sprankhub** [comment]
I debugged the issue. In our shop, `Payone_Core_Model_Service_Amazon_Pay_Checkout::chooseMethod ` is never called, so that `PayoneGenericpaymentGrandTotal` is not set in the session at all, so that the check fails.

**Comment by sprankhub** [comment]
@fjbender any idea when you can check / fix this issue?

**Comment by fjbender** [comment]
Apparently, `chooseMethod` is only called when there is exactly one shipping option available (https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php#L183). 

@sprankhub Is there more or less than one shipping method available in your setup?

**Comment by sprankhub** [comment]
I debugged that as well. `$shippingRatesCount` is indeed 1, but obviously, the shipping method is already set correctly (`$this->quote->getShippingAddress()->getShippingMethod() === $params['shippingMethodCode']`). This **may** be related to the extension [https://github.com/ffuenf/Ffuenf_CheckoutHideShipping](Ffuenf_CheckoutHideShipping), which sets a shipping method on the quote quite early. In any case, setting the grand total on the session has to be done no matter which other conditions apply.

**Comment by fjbender** [comment]
I agree. Will file this as a bug. As of now, I can't say how long it's going to take. I assume this shouldn't be too much work, though.

**Comment by sprankhub** [comment]
Any update @fjbender?

**Comment by hreinberger** [comment]
Hi @sprankhub,
we're currently testing out https://github.com/PAYONE-GmbH/magento-1/pull/242 which looks promising. If you want to, try it out yourself, so we have a real world example.

**Comment by fjbender** [comment]
Fixed with #242
