### ISSUE TITLE
Payone transaction error (Failed reason -911)

### ISSUE THREAD

**Issue by zaietsv** [PAYONE-GmbH/magento-1#232]
Payone module occasionally cancels an order bacause of **Failed reason -911**  API responce http://screenshots.collabstar.com/vza/8f714f2b.png. Then it switches order again to a processed status and completes successfull payment http://screenshots.collabstar.com/vza/a79a0fd5.png . It is not possible neither create an invoice nor shipment after the order is canceled. We need to close these ordres directly in a database.
As a result, a store sales statistic is wrong because an ordered item is canceled in the store but it is delivered in fact.

**Comment by fjbender** [comment]
Can you give me the transaction ID for one affected transaction so I can simulate the behavior?

Thanks.

**Comment by zaietsv** [comment]
If you mean Txid, it is txid | 281846060

**Comment by zaietsv** [comment]
Please, explain me, what does it mean "Failed reason -911" ? Thank you.

**Comment by fjbender** [comment]
Thanks. This is a rare issue on our platform itself and not a module bug.
Please contact our Technical Support Team and refer to the issue SUPP-11474.

Thanks
Florian

**Comment by zaietsv** [comment]
Yes, you are quite right: this issue is very rare and very unpleasant because requires direct DB invasion. I think, the module might to have some protect mechanism to avoid of orders cancellation.
