### ISSUE TITLE
Masterpass checkout button shortcut broken

### ISSUE THREAD

**Issue by mad-develop** [PAYONE-GmbH/magento-1#233]
I had some PHP errors with the Masterpass Shortcut inside the cart/minicart.

```
PHP Fatal error:  Call to a member function getMode() on null in 
./app/code/community/Payone/Core/Block/Mastercard/Masterpass/Shortcut.php on line 119
```

The problem seems to occur, when masterpass is not configured. 
The getMasterpassLibraryUrl function fails cause $config is null
.\app\code\community\Payone\Core\Block\Mastercard\Masterpass\Shortcut.php
Line 115 - 123

Magento Version: 1.9.3.9

Solution:
check config in _beforeToHtml() like its done in the Paypal Express module
File:
```
protected function _beforeToHtml()
{
	$result = parent::_beforeToHtml();
	$quote = Mage::getSingleton('checkout/session')->getQuote();

	// check payment method availability
	$methodInstance = Mage::helper('payment')->getMethodInstance($this->_paymentMethodCode);
	if (!$methodInstance || !$methodInstance->isAvailable($quote)) {
		$this->_shouldRender = false;
		return $result;
	}
        
	return $result;
}
```

**Comment by fjbender** [comment]
Thanks for the feedback, we should have fixed this already in 819e1823db8cb2cec677e63ebf360a00883e0e06, however, the Pull Request is still pending for QA approval.
