### ISSUE TITLE
Payone API error (Failed reason -911)

### ISSUE THREAD

**Issue by zaietsv** [PAYONE-GmbH/magento-1#235]
Hello!
There is a new incident with Payone API error (Failed reason -911). It looks similar to an issue https://github.com/PAYONE-GmbH/magento-1/issues/232 . Please, pay an attention that it is the second payment failure within last week.
The new failed transaction ID is txid | 282524922

**Comment by zaietsv** [comment]
PS: Please, find a solution, before closing this task like previous.

**Comment by fjbender** [comment]
@zaietsv Which version of the extension are you using? The logs show that you're sending a version identifier 3.4.15 which is very old (>2 years). 

I tried to reproduce your issue with the current version, and it doesn't appear there. While we didn't address this issue specifically in the past, it seems that we became more tolerant about the `failedcause` parameter.

**Comment by zaietsv** [comment]
I have updated the module. Ocassionally our sales are down twice. Let's observe for some time. I'll inform you about unexpected cases.
