### ISSUE TITLE
Credit Card Data Not Saved

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#237]
Even though we configured that payment data should be saved for credit card payments (`payone_payment/template_creditcard/customer_form_data_save`), the data is not saved. The customer needs to enter it again and again. Any idea why this is the case? Are there any requirements, which need to be fulfilled?

**Comment by fjbender** [comment]
To be honest, I think that feature is a stub. It was introduced before I started working on the Magento module.

We seem to store some encrypted data in the `payone_customers` table, but don't seem to use it anywhere except `\Payone_Core_Block_Payment_Method_Form_Creditcard` but not in full.

From the pre-github era I found out that this feature was introduced before "hosted iFrame" was implemented, so it was probably designed with the AJAX credit card check mode in mind.

**Comment by sprankhub** [comment]
Thanks for the response. Not the response I wanted to hear, but still ;-)

So... PAYONE does not support the storage of credit card data for future orders!?

**Comment by fjbender** [comment]
Sorry to disappoint. 

You'd be able to build a DIY solution taking the data from the `payone_customer` table. I think the `pseudocardpan` parameter is stored in there which can be used for future orders. We don't have the feature on our roadmap and it probably would take quite some time to get it prioritized.

**Comment by sprankhub** [comment]
I *heard* that it works when using the AJAX request type and not the hosted iframe option. Questions:

1. Is it correct that credit card data is saved and can be re-used when using the AJAX request type?
2. What is the official recommendation for the two request types? When should I use AJAX, when should I use hosted iframe?

**Comment by fjbender** [comment]
I can't confirm for sure, that credit card data (card tokens, to be exact) are saved in the encrypted bits of the `payone_customer` table as I haven't figured out how to decrypt them manually. I tried to use it that way with no success, however.

Generally, whether you'll have to use AJAX or hosted iframe depends on your level of PCI compliance. Merchants with the "standard" level of PCI compliance (i.e. the "couple-of-questions-and-you're-done-mode") are required to use the hosted iframe mode (this would apply to most merchants).

**Comment by sprankhub** [comment]
Could you please

1. confirm that credit card data is definitely saved and re-used when using the AJAX mode?
2. try to get credit card storage / re-usage implemented when using the hosted iframe option as well?

IMHO, this is a quite important feature, which makes the extension much more valuable.

Thanks!

**Comment by sprankhub** [comment]
Any update @fjbender?

**Comment by sprankhub** [comment]
Any update?

**Comment by hreinberger** [comment]
I did some research on this. We do store card data for customers in the `payone_customer` table in the `customer_data` field. I triggered an order using hosted iFrame and decrypted the value using [this script](http://magetricks.com/tricks/decrypt-any-md5-hashed-value-stored-in-magentos-db).

The available info includes the credit card type, truncated cardpan, pseudocardpan (yay) and cc owner. However, the expiry date doesn't seem to be saved when using hosted iFrame. Using this info, we could re-use saved card data. We'll check if we can store the expiry date with the other data and put a feature to save the credit card data for registered users and hosted iFrame on the roadmap.

**Comment by sprankhub** [comment]
Awesome news! Looking forward to it. Hope this is not a "some time in the future", but a "we want to implement that in the next month" thing :-)

**Comment by sprankhub** [comment]
Awesome news - thanks @hreinberger! Do you have a screenshot available how this feature looks like?

**Comment by hreinberger** [comment]
Hi @sprankhub 
this is what it looks like when using hosted iFrame:
![grafik](https://user-images.githubusercontent.com/40197225/46612365-9a185000-cb10-11e8-84dc-d5a8d5c36f51.png)

**Comment by sprankhub** [comment]
Awesome, thanks! When can we expect a new release with this feature?
