### ISSUE TITLE
MySQL protocol tables getting big. Safe to delete older data?

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#238]
I noticed the tables payone_protocol_api and payone_protocol_transactionstatus getting quite big (240 and 110mb).

Is it safe to delete data older than, lets say, 30 days in them? Any reason not to?

Maybe a possible feature to add.

**Comment by fjbender** [comment]
It should be safe to delete any data related to orders that have been completely processed and won't generate any credit memos or the like anymore.
