### ISSUE TITLE
CC Type Auto Recognition

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#244]
We currently use the hosted iframe option and enabled the option `payone_general/payment_creditcard/cc_type_auto_recognition`. It is a nice feature! However, it does not really help. Even though it is enabled, the CC type is requested from the customer first and then the CC number is requested. This means that the customer will always select the type first and then enter his number. It would be much better if the order would be switched, so that the auto recognition really helps. Do I miss something or could that be changed?

**Comment by hreinberger** [comment]
Hi @sprankhub, 
I agree, it's a nice feature, but it's not very visible in the frontend. Of course you could always customize your template to tell the customer that he or she only needs to input the card number, but maybe we can find a simple solution to make this feature more visible.
@fjbender any ideas?

**Comment by hreinberger** [comment]
Hi @sprankhub, I like your suggestion. That should be easy enough to do without breaking compatibility for custom templates.

**Comment by sprankhub** [comment]
Is the auto recognition good enough, so that one could disable the CC type dropdown? IMHO, setting it automatically and having a possibility to change it manually does not make any sense if the auto recognition works good enough.

**Comment by hreinberger** [comment]
So in our latest release we improved this feature by rearranging the card type selector. We also made the selector optional for maximum convenience. There's a new configuration toggle for the card type, so a merchant with custom or exotic card types can still leave the card type selector in for maximum compativility.  Thanks for your input, that helped a ton!

**Comment by sprankhub** [comment]
Thanks! We just updated and it seems to work. Would it make sense to show / respect the option "Hide the credit card type selector" only if the option "Enable Credit Card type auto recognition" is enabled? Otherwise, it probably does not work, right?
