### ISSUE TITLE
Payone_creditcard duplicted records

### ISSUE THREAD

**Issue by zaietsv** [PAYONE-GmbH/magento-1#249]
After update a Payone module generates in a some unknown way duplicated records of a "creditcard" payment method. Sometimes it is unable to extract the payment method data by id because there are two different ids for the same method http://screenshots.collabstar.com/vza/2441e4b9.png . These exceptions are registered in payone_protocol_transactionstatus/processing_error [local@localhost] http://screenshots.collabstar.com/vza/2cea02f4.png As a result it is impossible to generate an invoice and complete the order. It still remains in a status "New Paid".

**Comment by fjbender** [comment]
From which version to which did you update?

Does it help to manually set the `payone_config_payment_method_id` in the `sales_flat_order_payment` table to the new corresponding id?

**Comment by zaietsv** [comment]
As it has been mentioned in https://github.com/PAYONE-GmbH/magento-1/issues/235, the previous version was 3.4.15 . Now I have deleted the duplicated records and I am waiting for positive results.

**Comment by zaietsv** [comment]
Feedback: I have changed all old ids to new Ids. It seems working as well new as old orders http://screenshots.collabstar.com/vza/106a74b0.png

**Comment by fjbender** [comment]
Good to hear it's working now.
