### ISSUE TITLE
Unable to create orders at multistore view

### ISSUE THREAD

**Issue by zaietsv** [PAYONE-GmbH/magento-1#251]
It is impossible to made orders at multistore view because Payone stores a parameter payone_config_payment_method.mode as "null" at multistore configuration http://screenshots.collabstar.com/vza/8fda9e5d.png . Then reads it as empty string instead of "live" or "test" and fails it's own validation http://screenshots.collabstar.com/vza/00cfafe6.png .

**Comment by zaietsv** [comment]
And now I know exactly that your update has been failed down to 50% our sales within last 8 days. Thank you for this!

**Comment by fjbender** [comment]
Sorry that the update broke the multistore config.

In my configuration, the `payone_config_payment_method.mode` is `NULL` for all scopes except default. However, multistore works with that in my system.

**Comment by zaietsv** [comment]
This one works after distributing columns values "payone_config_payment_method.mode" and "payone_config_payment_method.aid" values to all rows http://screenshots.collabstar.com/vza/318d0c3d.png
