### ISSUE TITLE
An order is paid, but an invoice still waiting for payment

### ISSUE THREAD

**Issue by zaietsv** [PAYONE-GmbH/magento-1#254]
Hello!
There are several orders for today where orders are paid, but invoices are still pending for payment.
For example http://screenshots.collabstar.com/vza/42d55822.png and 
http://screenshots.collabstar.com/vza/fb1a8096.png
It is not possible to capture these invoices from admin account due an error 
[950: Desired status change not possible for this payment process] - An error occured while processing this transaction (wrong parameters).
http://screenshots.collabstar.com/vza/6c8b371b.png http://screenshots.collabstar.com/vza/a37ac70d.png

The question is what we need to do to capture these invoices and to prevent such situations in future?

**Comment by fjbender** [comment]
This depends on the exact circumstances of the transaction and you configuration. I wouldn't suspect a module bug here at first sight. Our Technical Support Team will gladly check your setup and see were things go wrong.

**Comment by zaietsv** [comment]
Hello! Thank you for your support! Please, specify which way I can give you an access credentials. I currently able to provide you an admin account and in a brief time to create a secure filesystem access.

**Comment by fjbender** [comment]
Please contact our Technical Support team at tech.support@bspayone.com or by phone +49 431 25968-500, they'll walk you through the process. Here at Github we can only provide assistance for general module bugs.

**Comment by zaietsv** [comment]
Hello again! After communication with payone support I have revised our cronjobs schedule and i can assume that "payone_core_cronjob_transactionstatus_process" really has ocassional delays in it's execution.
http://screenshots.collabstar.com/vza/fd126807.png http://screenshots.collabstar.com/vza/7c99d1a8.png

Could you, please, advice possible causes of a such Payone module behavior and places, where I need to debug?

**Comment by fjbender** [comment]
I can only assume it would be fruitful to start from `\Payone_Core_Model_Cronjob_TransactionStatus_Worker` and work your way down from there. The actual work is being done in `\Payone_Core_Model_Service_TransactionStatus_Execute`

**Comment by zaietsv** [comment]
Today there was a new case, when an invoice hasn't been created while execution of an payone cron task "payone_core_cronjob_transactionstatus_process" http://screenshots.collabstar.com/vza/e80de821.png . This invoice is h=depicted at the next screnshot http://screenshots.collabstar.com/vza/4a35ec1e.png .
I have managed to set up different logs in the Payone module and to capture a place, where the error occurs. It is situated at class Payone_Core_Model_Observer_TransactionStatus_InvoiceCreate public function onPaid() line 101. Sometimes there comes an empty invoice from downstream methods. It has not neither ID, nor IncrementId, nor a valid state. Therefore, Magento unable to save the invoice and breaks next operations execution.
There is a scheme, where you can to compare both successfull and unsuccessfull workflows http://screenshots.collabstar.com/vza/1209caca.png . A successful workflow ends with an invoice state change from 1 (pending) to 2 (paid). Otherwise, unsuccessfull workflow unable to change the invoice state since it does not exists http://screenshots.collabstar.com/vza/1209caca.png
Maybe it will help us to step forward and to find a solution.

**Comment by zaietsv** [comment]
At present time I am debugging this place http://screenshots.collabstar.com/vza/42eff07f.png But you also could to made your contribution in your module whatever you have any ideas.

**Comment by fjbender** [comment]
Thank you for the detailed insights, this is very helpful!

I suppose this will probably go in the direction of #119, which has been haunting us for quite some time. In #119 we identified DB deadlocks to be the cause for this. Is this consistent with your findings?

**Comment by zaietsv** [comment]
Yes, a task #119 has the same origin. I think, it is not depends on db locks. There are some cases when Config loads payment methods in "store" scope, but searches a method by Id from website scope. For example, our store view 1 uses a store method number 99, but the module searches a website method number 98
http://screenshots.collabstar.com/vza/715a9095.png
Of course, there is possible a revert situation, where it loads "website" scope, but searches for "store" scope

**Comment by zaietsv** [comment]
I have some ideas about the cache behavior. I have created an extension which fixes this issue, as I hope. Now it requires some tests at a live environment.

**Comment by fjbender** [comment]
That sounds promising! Would you share the extension with us so the community can help you in validating your findings?

**Comment by zaietsv** [comment]
There is a method Payone_Core_Model_Factory->getConfigProxyMode() which always calls a null-store configuration which falls back to a website configuration. If a configuration cache is clear at that moment, it caches this website configuration under a cache key "store_1_payone_config_cache". Every next method wich calls a "1-store" configuration obtains a cached "null-store" configuration since the first store cache key has the same name "store_1_payone_config_cache". It is not completely wrong, since most of fields has the same values in differnt configurations. 
But concerning to a payment method id value, it is different for the website and for the store. Every method calling a payment-id for a particular store obtains a different Id for website. At that moment appears an error message "Error during service execution, set status to error with message Payment method configuration with id "99" not found." . The script stops an invoice generation because it unable to extract a properly payment method Id.
How could you fix it? You need to create an unique cache-key name for null-store calls (i.e. website-config calls). Let it be "store_NULL_payone_config_cache" or "store_website_payone_config_cache" . Therefore all you need is to rewrite Payone_Core_Model_Service_InitializeConfig->getConfigCacheId() and Payone_Core_Model_Service_InitializeConfig->getConfigRegistryKey().
`<?php
/**
 * Created by IntelliJ IDEA.
 * User: vza
 * Date: 18.08.18
 * Time: 0:42
 */

class Lindenvalley_Payone_Core_Model_Service_InitializeConfig extends Payone_Core_Model_Service_InitializeConfig
{
    const NULL = 'NULL';

    /**
     * Returns a separate registry key for a "null" store config.
     * A parent method could occasionally override cached store configuration with a parent website configuration.
     * Usually it occurs under a registry key 'payone_core_config_1', where 1 is default store id.
     * @param int|null $storeId
     * @return string
     */
    public function getConfigRegistryKey($storeId = null)
    {
        if ($storeId === null) {
            $storeId = $this->getStoreId();
        }

        if ($storeId === null) {
            $storeId = self::NULL;
        }

        $cacheId = sprintf(self::CONIG_REGISTRY_KEY, $storeId);
        return $cacheId;
    }

    /**
     * Returns a separate cache id for a "null" store config.
     * A parent method could occasionally override cached store configuration with a parent website configuration.
     * Usually it occurs under a cache id 'store_1_payone_config_cache', where 1 is default store id.
     * @param int|null $storeId
     * @return string
     */
    public function getConfigCacheId($storeId = null)
    {
        if ($storeId === null) {
            $storeId = $this->getStoreId();
        }

        if ($storeId === null) {
            $storeId = self::NULL;
        }

        $cacheId = sprintf(self::CONFIG_CACHE_ID, $storeId);
        return $cacheId;
    }
}`

**Comment by zaietsv** [comment]
@janteuber haven't you really resolved the issue before closing it?

**Comment by janteuber** [comment]
Hello @zaietsv ,
Thanks for your reply.

Since the M1 is now EOL, we are focusing on resolving only acute bugs that is reported directly by an actual merchant.
Therefore, I am now closing all very old issues on Github. If a merchant has an urgent issue, please create a ticket with the merchant's details at tech.support@payone.com.

Thanks a lot

**Comment by zaietsv** [comment]
Ah I can understand the strategy: it is better to wait four years and then simply close a task without resolving it. Let me inform you that we rejected the Payone extension some time ago due of multiple bugs and support quality.
