### ISSUE TITLE
Bug bei abgebrochener Bezahlung

### ISSUE THREAD

**Issue by mcandian** [PAYONE-GmbH/magento-1#257]
Hallo,

wir haben aktuell ein Problem bei abgebrochenen Bezahlungen (zum Beispiel bei Giropay oder Sofort), die erneut bestellt werden.

**Voraussetzungen**
- E-Mailbestätigung bei der Registrierung

**Reproduktionsschritte**
1. Zur Kasse gehen mit "Bestellen und Registrieren"
2. Bei Zahlungsarten Giropay oder Sofort auswählen
3. Bestellung absenden
4. Bei Giropay oder Sofort die Zahlung abbrechen
5. Wieder zu Kasse gehen, jetzt aber mit Gast
6. Bestellung absenden

**Problem**
Bei der zweiten Bestellung sehen die Daten zum Benutzerkonto so aus:
![result](https://user-images.githubusercontent.com/32956732/44018357-c3f7b07a-9edb-11e8-85fc-ee06ea672931.png)

**Mögliches Problem**
Bei der Wiederherstellung der Bestellung als Warenkorb steht in der Bestellung eine customer_id. Dadurch wird die zweite Bestellung als angemeldeter Benutzer gewertet, auch wenn man bei der Kasse "Als Gast" auswählt. Da der Benutzer aber nicht eingeloggt ist (weil er dies vorher noch bestätigen muss), werden wohl keine Daten von dem registrierten Benutzer geladen.

**Mögliche Lösung**
Bei der Wiederherstellung der Bestellung als Warenkorb müsste man pürfen, ob bei der Bestellung die Auswahl "Registrieren und Bestellen" ausgewählt wurde und ob der Benutzer eine E-Mail bestätigen muss. Dann wird die customer_id entfernt und der Warenkorb gilt als der eines Gastes.

**Comment by hreinberger** [comment]
Hallo @mcandian,

vielen Dank für die ausführliche Beschreibung! Ich habe mal versucht, das Verhalten nachzustellen. Allerdings unterscheidet sich das Verhalten bei mir (Magento 1.9.3.9, Version 4.1.7 des Moduls, keine weiteren Module aktiv, Standardtemplate).

Breche ich bei Sofort den Kauf ab (über den "Abbrechen und zurück zum Händler" Link), lande ich erneut im Checkout. Dann bestelle ich als Gast, gebe meine Daten ein und ziehe den Kauf durch. Bei mir werden in der Bestellung dann die Gastdaten gespeichert, ein Kundenaccount wird mit diesen Daten aber nicht angelegt und die Bestellung geht durch. Gleichzeitig gibt es einen Kundenaccount, der aber unbestätigt ist. 

Hier kann es natürlich sein, dass unsere Konfigurationen sich unterscheiden oder das Phänomen nur in bestimmten Versionen auftritt. Bitte wenden Sie sich einmal an die Kollegen vom Tech Support unter tech.support@bspayone.com mit einem Link zu diesem Issue und einem Konfigurationsexport aus dem Backend (PAYONE -->Konfiguration --> Konfiguration exportieren). Die Kollegen können dann näher in die Analyse einsteigen.

viele Grüße!
