### ISSUE TITLE
Unnecessary Template Changes

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#263]
In https://github.com/PAYONE-GmbH/magento-1/commit/25ad01cd76284e454b7f530138eabead45f6203b#diff-e389e00935af25b1a4260a721cc08ef7, all (or at least many) PayPal Express templates have been changed to PAYONE-specific templates. I compared the PAYONE templates with the ones from `base/default`. The only difference is the type hint (a comment!). With that change, you break many themes, which have customised the PayPal express templates. I will send a PR fixing this behaviour shortly.

**Comment by fjbender** [comment]
Seems also unnecessary to me, we'll fix this.

**Comment by fjbender** [comment]
#266 should fix this

**Comment by fjbender** [comment]
Is #266 fine now? Thanks for your help on this!

**Comment by sprankhub** [comment]
Added my review now @fjbender.
