### ISSUE TITLE
Wrong Creditmemo Amount

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#267]
My customer says that after updating to 4.2.0, the amounts refunded at PAYONE when creating creditmemos are wrong. An example TXID would be 291841823. Even though just a small amount of the order has been refunded in Magento (1 of 5 products), the whole order amount has been refunded at PAYONE. The PAYONE tech support says that they can only see the full refund amount on PAYONE side.

This issue happens with multiple payment methods (PayPal, Amazon Pay).

**Comment by fjbender** [comment]
I tried to reproduce this with PayPal in various settings (preauth/capture/debit, auth/debit, both with and without basket submission) but the debit amounts were always correct. I was using Magento 1.9.3.9 and Payone 4.2.0, the same as your customer. Anything that might be different in your setup?

**Comment by sprankhub** [comment]
Nothing that I know of. I sent some screenshots and the config export to the technical support. Hope they can help.

**Comment by sprankhub** [comment]
I found the issue. You introduced this in https://github.com/PAYONE-GmbH/magento-1/commit/402ddd969099af93b10f1d6573791fbdc54cd89f:

https://github.com/PAYONE-GmbH/magento-1/blob/bf11526559ed6e91b071ddf0df145a56babd3226/app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Debit.php#L124-L127

So if you set the option `payone_general/global/currency_convert` to `1`, the full order amount will always be refunded instead of the specified amount, which may be smaller. I am sure you can reproduce the issue with this setting @fjbender.

In my case, this is a one currency shop, so that I can simply set the option to `0` as a workaround, but you should definitely fix this issue!

**Comment by sprankhub** [comment]
I found the issue. In https://github.com/PAYONE-GmbH/magento-1/commit/402ddd969099af93b10f1d6573791fbdc54cd89f, you introduced this:

https://github.com/PAYONE-GmbH/magento-1/blob/bf11526559ed6e91b071ddf0df145a56babd3226/app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Debit.php#L124-L127

So if you set the config `payone_general/global/currency_convert` to `1`, the grand total will always be used and not the respective amount, which may be smaller. I am sure you can reproduce the issue with this setting @fjbender. Since we only have one currency, setting this to `0` should work for us as a workaround, but you should definitely fix this issue!

**Comment by sprankhub** [comment]
I found the issue. In https://github.com/PAYONE-GmbH/magento-1/commit/402ddd969099af93b10f1d6573791fbdc54cd89f, you introduced this:

https://github.com/PAYONE-GmbH/magento-1/blob/bf11526559ed6e91b071ddf0df145a56babd3226/app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Debit.php#L124-L127

So if you set the config `payone_general/global/currency_convert` to `1`, the grand total will always be used and not the respective amount, which may be smaller. I am sure you can reproduce the issue with this setting @fjbender. Since we only have one currency, setting this to `0` should work for us as a workaround, but you should definitely fix this issue!

**Comment by sprankhub** [comment]
I found the issue. In https://github.com/PAYONE-GmbH/magento-1/commit/402ddd969099af93b10f1d6573791fbdc54cd89f, you introduced this:

https://github.com/PAYONE-GmbH/magento-1/blob/bf11526559ed6e91b071ddf0df145a56babd3226/app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Debit.php#L124-L127

So if you set the config `payone_general/global/currency_convert` to `1`, the grand total will always be used and not the respective amount, which may be smaller. I am sure you can reproduce the issue with this setting @fjbender. Since we only have one currency, setting this to `0` should work for us as a workaround, but you should definitely fix this issue!

**Comment by sprankhub** [comment]
I found the issue. In https://github.com/PAYONE-GmbH/magento-1/commit/402ddd969099af93b10f1d6573791fbdc54cd89f, you introduced this:

https://github.com/PAYONE-GmbH/magento-1/blob/bf11526559ed6e91b071ddf0df145a56babd3226/app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Debit.php#L124-L127

So if you set the config `payone_general/global/currency_convert` to `1`, the grand total will always be used and not the respective amount, which may be smaller. I am sure you can reproduce the issue with this setting @fjbender. Since we only have one currency, setting this to `0` should work for us as a workaround, but you should definitely fix this issue!

**Comment by fjbender** [comment]
Many thanks! We'll fix this.

**Comment by fjbender** [comment]
I think we'll hit a brick wall here with multiple refunds, due to a Magento Core bug.

In `app/code/core/Mage/Sales/Model/Order/Creditmemo/Total/Tax.php` it says:

```php
    public function collect(Mage_Sales_Model_Order_Creditmemo $creditmemo)
    {
        // FB: some stuff left out
        $order = $creditmemo->getOrder();

        /** @var $item Mage_Sales_Model_Order_Creditmemo_Item */
        foreach ($creditmemo->getAllItems() as $item) {
            $orderItem = $item->getOrderItem();
            if ($orderItem->isDummy()) {
                continue;
            }
            $orderItemTax     = $orderItem->getTaxInvoiced();
            $baseOrderItemTax = $orderItem->getBaseTaxInvoiced();
            $orderItemHiddenTax = $orderItem->getHiddenTaxInvoiced();
            $baseOrderItemHiddenTax = $orderItem->getBaseHiddenTaxInvoiced();
            $orderItemQty     = $orderItem->getQtyInvoiced();

            if (($orderItemTax || $orderItemHiddenTax) && $orderItemQty) {
                /**
                 * Check item tax amount
                 */

                $tax            = $orderItemTax - $orderItem->getTaxRefunded();
                // FB: this should be
                // $baseTax = $baseOrderItemTax - $orderItem->getBaseTaxRefunded();
                $baseTax        = $baseOrderItemTax - $orderItem->getTaxRefunded();
                $hiddenTax      = $orderItemHiddenTax - $orderItem->getHiddenTaxRefunded();
                $baseHiddenTax  = $baseOrderItemHiddenTax - $orderItem->getBaseHiddenTaxRefunded();
```

This results in wrong amounts from the second credit memo onwards, which will get rejected by the Payone API.

We're not inclined to provide a workaround here, as it will surely get veeeery messy.

We'd probably merge #280 anyway. I think there should be a bug report filed with Magento for the Core issue.

**Comment by sprankhub** [comment]
Getting this into the M1 core is probably desperate. But I opened a pull request for the Magento LTS project at least (see above).

Good news: This is already fixed in the [M2 core](https://github.com/magento/magento2/blob/d7012b2ca1495676478d8afed8bf016ccd03bc8a/app/code/Magento/Sales/Model/Order/Creditmemo/Total/Tax.php#L45).
