### ISSUE TITLE
Transactionstatus 404 When Using Store Codes In Urls

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#269]
If you activate the option `web/url/use_store` / "Add Store Code to Urls", the transaction status does not work correctly. So for example, let us consider you have a store with code `de` and one with code `en`. Then the DE store - given the above mentioned configuration - runs under https://www.store.com/de/. Hence, the transaction status would need to be sent to https://www.store.com/de/payone_core/transactionStatus. However, the `de` in the URL is omitted and the transaction status is sent to https://www.store.com/payone_core/transactionStatus, which leads to a 404 page.

On a very first view, I could not see where the URL for the transaction status is generated. Could you please check and fix?

**Comment by fjbender** [comment]
The Transaction Status URL is not set in the plugin, but in the Payone Merchtant Interface in the payment portal configuration (PMI > Konfiguration > Zahlungsportale > Zahlungsportal > Erweitert). It should be set to https://www.store.com/de/payone_core/transactionStatus there.

**Comment by sprankhub** [comment]
Ahh sorry for that! Then I would need to create two payment portals - one for DE and one for EN and set the URLs accordingly, right?

**Comment by sprankhub** [comment]
I cannot edit the URL in the payment portal settings. All fields are disabled...? Do I need to delete the portal and create a new one?

**Comment by fjbender** [comment]
You can create two payment portals, but perhaps it works also when using the same URL for both sub-shops.
You shouldn't delete the portal, that'll basically destroy a lot of open transactions. Maybe you don't have the sufficient rights to change the URL (e.g. when your customer created a second account for you). Our service team should be able to help with that.
