### ISSUE TITLE
Do Not Use MyISAM as Table Engine

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#273]
Currently, the table `payone_payment_ban` uses `MyISAM` as a table engine, which is superseded by `InnoDB`. Please change the engine of the table to `InnoDB`.

https://github.com/PAYONE-GmbH/magento-1/blob/bf11526559ed6e91b071ddf0df145a56babd3226/app/code/community/Payone/Core/sql/payone_core_setup/mysql4-upgrade-4.1.1-4.1.2.php#L106
https://github.com/PAYONE-GmbH/magento-1/blob/bf11526559ed6e91b071ddf0df145a56babd3226/app/code/community/Payone/Core/sql/payone_core_setup/upgrade-4.1.1-4.1.2.sql#L13

**Comment by fjbender** [comment]
Thanks, we'll take a look. Should be a no-brainer, I guess.
