### ISSUE TITLE
Include CSS Only If Needed

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#274]
Currently, the CSS files `payone/core/amazonpay_button.css` and `payone/core/masterpass.css` are included on every page:

https://github.com/PAYONE-GmbH/magento-1/blob/bf11526559ed6e91b071ddf0df145a56babd3226/app/design/frontend/base/default/layout/payone/core.xml#L172-L173

First, I think they should only be included if the respective payment method is active. Second, I am not sure if the CSS is really needed on every page.

**Comment by hreinberger** [comment]
sounds reasonable, we'll have a look. thanks!
