### ISSUE TITLE
Broken JS Reference If Payolution Not Used

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#276]
https://github.com/PAYONE-GmbH/magento-1/commit/dbc695d08fd2036f9593becaf662dff9def7fc58 leads to a broken JS reference if Payolution is not used:

    <script type="text/javascript" src="https://www.shop.com/js/"></script>

**Comment by sprankhub** [comment]
Status? This is clearly a bug.

**Comment by fjbender** [comment]
@T-Kuchel Can you look into this?

**Comment by T-Kuchel** [comment]
Confirmation! It is a bug > **clearly**. We will fix it!

**Comment by T-Kuchel** [comment]
fixed with  [#298](https://github.com/PAYONE-GmbH/magento-1/pull/298)
