### ISSUE TITLE
PHP Warning on Creditcard CVC Length

### ISSUE THREAD

**Issue by Backenkoehler** [PAYONE-GmbH/magento-1#285]
We currently have a lot of warnings:
PHP Warning:  in_array() expects parameter 2 to be array, null given in app/code/community/Payone/Core/Block/Payment/Method/Form/Creditcard.php on line 528

We are on Version 4.2.0. Can please take a look, I know it's not really a bug but pretty annoying in development and if you run automated tests.

**Comment by fjbender** [comment]
@hreinberger see https://github.com/PAYONE-GmbH/magento-1/blob/e48b3fdad3268bb44421019e3a3b35cc8c292858/app/code/community/Payone/Core/Block/Payment/Method/Form/Creditcard.php#L525-L531

This was introduced with e5e8a80bf40d1ad97182ee9db1041ed766f881e1 from MAGE-365. Should be easy to check `$hidden` for `NULL`.

**Comment by hreinberger** [comment]
This should be fixed by #289
