### ISSUE TITLE
Amazonpay Controller - totals collected flag

### ISSUE THREAD

**Issue by axe1987** [PAYONE-GmbH/magento-1#288]
Hallo,

ich versuche das Payone Modul (version 4.2.1) in eines unserer Magento Systeme zu integrieren.
Leider habe ich ein paar Probleme damit.

Ich habe eine Warenkorbpreisregel das Produkte ab Warenkorbwert 500 jeweils 5% erhalten.
Die Anzeige im Magento Warenkorb ist soweit korrekt.

Produkt A mit Preis 599 erhält den 5% Rabatt (29,95).
Gehe ich in den Amazon Checkout dann erhält das Produkt aber den doppelten Rabatt (59,9).

Ich konnte das Problem soweit debuggen das ich jetzt weiß woran es liegt.
Der AmazonpayController holt sich in der progressAction via _initCheckout die Quote.
Diese ist ja schon in der DB und die totals wurden schon collected.

In der Model Funktion von confirmSelection (Payone_Core_Model_Service_Amazon_Pay_Checkout) wird dann wieder das TotalsCollectedFlag auf false gesetzt. Damit wird die Quote neu berechnet und der Rabatt wird nochmal drauf gerechnet.

Wenn ich die Zeile $this->quote->setTotalsCollectedFlag(false); auskommentiere (Zeile 152), dann habe ich die richtige Berechnung und ich kann die Bestellung erfolgreich durchführen (alles in Sandbox natürlich).

Daher meine Frage. Warum wird dort das TotalCollectedFlag wieder auf false gesetzt.

Beste Grüße
axe1987

**Comment by fjbender** [comment]
Danke für die ausführliche Analyse! 
@hreinberger Sieht auf den ersten Blick für mich auch merkwürdig aus. Kannst du mit Vincent mal drauf schauen?

**Comment by hreinberger** [comment]
schauen wir uns an!

**Comment by hreinberger** [comment]
hmmmm also ich kann das Thema mit dem aktuellen master auf einem Magento 1.9.10 bisher nicht reproduzieren. Das habe ich gemacht:

- Warenkorbregel mit den Bedingungen WENN "Zwischensumme größer gleich als 500" DANN 5% Prozentualer Rabatt je Artikel
- Artikel mit Preis >500€ in den Warenkorb legen und Warenkorb anzeigen
- Rabatt wird im Warenkorb berechnet
- Amazon Pay Button betätigen und Checkout abschließen

Ergebnis: In allen Bestellschritten und an unserer API werden immer die richtigen Preise und Rabatte genutzt. @axe1987 habe ich etwas übersehen?

**Comment by axe1987** [comment]
Ein Unterschied ist noch das wir Magento Version 1.9.3.0 nutzen.

Wenn es nicht an der Magento version liegt, muss ich schauen ob wir irgendwelche Plugins im Einsatz haben die an der Berechnung mitwirken.
Sind da irgendwelche Probleme bekannt @hreinberger ?

Grüße axe1987

**Comment by hreinberger** [comment]
Hi @axe1987 
auch mit einem 1.9.3.0 kann ich das Verhalten nicht nachstellen. Dann sollten wir individueller in die Analyse einsteigen. 

Bitte schicke einmal einen Konfigurationsexport aus dem Magento Backend (PAYONE --> Konfiguration --> Konfiguration exportieren) an die Kollegen vom Tech Support (tech.support[ät]bspayone.om). Verweise dabei gerne auf diesen Thread. Im Konfigurationsexport steckt neben der Konfig des Moduls auch eine Liste mit installierten Drittmodulen. Eventuell finden die Kollegen da noch Hinweise auf Inkompatibilitäten.

**Comment by axe1987** [comment]
Habe die Konfigurationsdatei an Payone gesendet.
Sobald ich mehr weiß aktualisiere ich den Thread.

Grüße
axe1987

**Comment by axe1987** [comment]
Hallo,

ich habe ein paar weitere Informationen.
In dem erwähnten Checkout.php (Payone_Core_Model_Service_Amazon_Pay_Checkout) in der confirmSelection Methode auf Zeile 146 wird folgendes gemacht:
```
        $this->quote->getPayment()->importData([
            'method'                          => $paymentMethodCode,
            'payone_config_payment_method_id' => $this->config->getId(),
            'checks'                          => [],
        ]);
```
Danach stimmen unter anderem die Einzelpreise nicht mehr.
Ich habe Produkte im Warenkorb mit Sonderpreisen. Gebe ich mir die Quote Items vor dem Aufruf der oben erwähnten Zeilen aus, dann stimmen die Einzelpreise noch (auch die Quote im allgemeinen stimmt noch).
Aber danach sind es komplett andere Preise.


```
Ausgabe Amazonpay Cart
Art-Nr | Stück | Einzelpreis | Gesamtpreis
------ | ------ | ----------- | -------------
1      | 4      | 34,9        | 139.60
2      | 4      | 27,9        | 111.60
3      | 1      | 499         | 499.0
     
Ausgabe Magento Cart
Art-Nr | Stück | Einzelpreis | Gesamtpreis
------ | ------ | ----------- | -------------
1      | 4      | 48,9        | 195.6
2      | 4      | 33,9        | 135.6
3      | 1      | 499         | 499.0

Magento Preise in den Artikelinformationen im Backend:

Art-Nr | Preis    | Sonderpreis
------ | -------- | --------
1      | 80.5000  | 48.9000
2      | 51.5000  | 33.9000
3      | 628.0000 | 499.0
```

Das Verhalten ist mir nicht bei Artikeln aufgefallen die keinen Sonderpreis haben. Allerdings ist dieses Verhalten auch nicht bei allen Artikeln mit Sonderpreisen zu beobachten.

Wie gesagt die Preise ändern sich in der Quote erst nach dem oben erwähnten Aufruf.

Dort wird folgendes Event geworfen: `sales_quote_payment_import_data_before`
Ich habe auch geprüft, wir fangen dieses Event nicht ab. Ich finde nur in Payone/Core/etc/config.xml dieses Event.


Das mit den Rabatten ist immer noch offen, aber lösen müsste ich beide Probleme.

Grüße
Axe1987

**Comment by axe1987** [comment]
> > Hallo,
> > ich habe ein paar weitere Informationen.
> > In dem erwähnten Checkout.php (Payone_Core_Model_Service_Amazon_Pay_Checkout) in der confirmSelection Methode auf Zeile 146 wird folgendes gemacht:
> > ```
> >         $this->quote->getPayment()->importData([
> >             'method'                          => $paymentMethodCode,
> >             'payone_config_payment_method_id' => $this->config->getId(),
> >             'checks'                          => [],
> >         ]);
> > ```
> > Danach stimmen unter anderem die Einzelpreise nicht mehr.
> > Ich habe Produkte im Warenkorb mit Sonderpreisen. Gebe ich mir die Quote Items vor dem Aufruf der oben erwähnten Zeilen aus, dann stimmen die Einzelpreise noch (auch die Quote im allgemeinen stimmt noch).
> > Aber danach sind es komplett andere Preise.
> > ```
> > Ausgabe Amazonpay Cart
> > Art-Nr | Stück | Einzelpreis | Gesamtpreis
> > ------ | ------ | ----------- | -------------
> > 1      | 4      | 34,9        | 139.60
> > 2      | 4      | 27,9        | 111.60
> > 3      | 1      | 499         | 499.0
> >      
> > Ausgabe Magento Cart
> > Art-Nr | Stück | Einzelpreis | Gesamtpreis
> > ------ | ------ | ----------- | -------------
> > 1      | 4      | 48,9        | 195.6
> > 2      | 4      | 33,9        | 135.6
> > 3      | 1      | 499         | 499.0
> > 
> > Magento Preise in den Artikelinformationen im Backend:
> > 
> > Art-Nr | Preis    | Sonderpreis
> > ------ | -------- | --------
> > 1      | 80.5000  | 48.9000
> > 2      | 51.5000  | 33.9000
> > 3      | 628.0000 | 499.0
> > ```
> > Das Verhalten ist mir nicht bei Artikeln aufgefallen die keinen Sonderpreis haben. Allerdings ist dieses Verhalten auch nicht bei allen Artikeln mit Sonderpreisen zu beobachten.
> > Wie gesagt die Preise ändern sich in der Quote erst nach dem oben erwähnten Aufruf.
> > Dort wird folgendes Event geworfen: `sales_quote_payment_import_data_before`
> > Ich habe auch geprüft, wir fangen dieses Event nicht ab. Ich finde nur in Payone/Core/etc/config.xml dieses Event.
> > Das mit den Rabatten ist immer noch offen, aber lösen müsste ich beide Probleme.
> > Grüße
> > Axe1987
> 
> Habe mehr Informationen:
> Das Problem scheint zu sein das AmazonPay den Preis des konfigurierbaren Artikel zu nehmen, anstatt des einfachen Artikels.
> Ist das Magento Standard?
> Im Magento Cart im normalen Checkout wird der simple Preis genommen.
> 
> Da scheinen wir also ein Modul zu haben was darin rumspielt.
> Melde mich wieder
> 
> Grüße Axe

**Comment by axe1987** [comment]
So habe das mit den Preisen jetzt raus.
Der Shop hat die getFinalPrice methode überschrieben um die Preise der einfachen Artikel zu nutzen.
Diese aber beschränkt auf bestimmte URLs, da musste ich nur die Payone URL für amazonpay eintragen dann ging es.
Also ein Fehler bei uns.
Ich denke ich finde das mit den Rabatten auch bei uns.

Werde das aber dann noch hier rein posten, vll hilft es jemand anderen in ähnlicher Situation.

Grüße axe1987

**Comment by hreinberger** [comment]
Ich schließe das Issue hier mal wegen Inaktivität. Sollte das Problem auch mit der aktuellen Version noch bestehen, einfach nochmal melden.
