### ISSUE TITLE
Duration support Payone extension for Magento 1.x

### ISSUE THREAD

**Issue by quintessence-vogt** [PAYONE-GmbH/magento-1#291]
Dear Payone Team,

we are pleasantly using your Payone extension for many years in our Magento Shop (1.9.1.0). 

Since Magento has announced that they will stop supporting Magento 1.x mid 2020 we have to decide what to do. There is the option that an external company (https://mage-one.com/) takes care of the Magento 1.x core regarding security issues, however this does not cover the extensions. Could you please tell me, how long Payone will support the Magento 1.x Payone extension regarding security issues?

If you have any questions please don't hesitate to ask.

Thank you very much and best regards

Alexander Fischer

**Comment by quintessence-vogt** [comment]
Hi,

thanks for the quick reply! We are using Magento Community Edition (not Enterprise) 1.9.1.0. Does this change anything regarding your reply? 

You said that you will provide security updates as long as enough merchants will be using the integration. Could you please tell me how long  in advance you will inform us, before the security support will be stopped? Since migrationg from Magento 1.x to another shop plattform is very time consuming and will take 1 - 2 years it is very important to know the timeframe.

Thanks and best regards!

**Comment by fjbender** [comment]
We'll support the corresponding CE as well.

I can't pinpoint a timeframe as of now. We're aware that migrating will take a lot of time and effort for our merchants, thus we'll at least plan 12 months in advance.

**Comment by quintessence-vogt** [comment]
Thanks alot!

**Comment by quintessence-vogt** [comment]
One more question: All payment options (including Paypal and Amazon Pay) will be supported, correct?

**Comment by fjbender** [comment]
Correct, unless the vendors somehow prohibit usage with legacy systems. This is currently not the case.
