### ISSUE TITLE
Security issues since Release 3.4.5?

### ISSUE THREAD

**Issue by user-1982** [PAYONE-GmbH/magento-1#293]
Has there been any security fixes since release 3.4.5? 

https://github.com/PAYONE-GmbH/magento-1/releases provides only information beginning with 3.5.9. As far as I can see there has been no security issues since then.

Thanks!

**Comment by fjbender** [comment]
We didn't have any security issues in the past. However, PCI DSS regulation has changed, so very old versions might not be PCI compliant.

**Comment by quintessence-vogt** [comment]
Thanks for the quick reply! Who could tell me if version 3.4.5 ist still compliant? Technical e-commerce support from the page: https://www.bspayone.com/DE/de/contact-germany ?

**Comment by user-1982** [comment]
Thanks for the quick reply! Who could tell me, if version 3.4.5 is still compliant, technical e-commerce support on page https://www.bspayone.com/DE/de/contact-germany ?

**Comment by fjbender** [comment]
Yes, they can check your page directly and see whether you have the correct setup.
