### ISSUE TITLE
Error on Checkout Page with customer accounts 

### ISSUE THREAD

**Issue by jhoelzl** [PAYONE-GmbH/magento-1#295]
Hello,

i am using Payone Module Version 4.2.0 with Magento CE 1.9.3.9.

Sometimes, with certain customer accounts, on checkout page (using Fireckout or Standard Onepage Checkout) this error occurs in system.log:

> 2018-11-14T12:27:45+00:00 ERR (3): Warning: in_array() expects parameter 2 to be array, null given  in app/code/community/Payone/Core/Block/Payment/Method/Form/Creditcard.php on line 528

I also bypassed all custom design/template changes, but issue remains.
However, when i process the checkout as a guest customer (not logged in), the checkout page works.

Any suggestions?
Regards,
Josef

**Comment by sprankhub** [comment]
Duplicate of #285.

**Comment by jhoelzl** [comment]
Nice, thanks!
