### ISSUE TITLE
Error on Checkout for logged in customers

### ISSUE THREAD

**Issue by jhoelzl** [PAYONE-GmbH/magento-1#296]
Hello,

i am currently testing the Payone 4.2.0 module on Magento CE 1.9.3.9.
When i perform the checkout as a guest user, the Payone creditcard payment method (i acitvated VISA and Mastercard) is shown and i can generate an order.
However, when do the checkout with an user account, the checkout site is broken and a Magento error report is generated:

> a:5:{i:0;s:50:"Die angeforderte Zahlungsart ist nicht verfügbar.";i:1;s:5816:"#0 /magento_shop/app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('Die angefordert...')
> #1 /magento_shop/app/code/core/Mage/Sales/Model/Quote/Payment.php(218): Mage_Payment_Model_Info->getMethodInstance()
> #2 /magento_shop/app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php(186): Mage_Sales_Model_Quote_Payment->getMethodInstance()
> #3 /magento_shop/app/design/frontend/base/default/template/tm/firecheckout/checkout/payment/methods.phtml(65): Payone_Core_Block_Checkout_Onepage_Payment_Methods->getSelectedMethodCode()
> #4 /magento_shop/app/code/core/Mage/Core/Block/Template.php(241): include('/home/devxxabn/...')
> #5 /magento_shop/app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('frontend/base/d...')
> #6 /magento_shop/app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
> #7 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
> #8 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
> #9 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('methods', true)
> #10 /magento_shop/app/design/frontend/base/default/template/tm/firecheckout/checkout/payment.phtml(65): Mage_Core_Block_Abstract->getChildHtml('methods')
> #11 /magento_shop/app/code/core/Mage/Core/Block/Template.php(241): include('/home/devxxabn/...')
> #12 /magento_shop/app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('frontend/base/d...')
> #13 /magento_shop/app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
> #14 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
> #15 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
> #16 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('payment.method', true)
> #17 /magento_shop/app/design/frontend/base/default/template/tm/firecheckout/checkout-2columns.phtml(74): Mage_Core_Block_Abstract->getChildHtml('payment.method')
> #18 /magento_shop/app/code/core/Mage/Core/Block/Template.php(241): include('/home/devxxabn/...')
> #19 /magento_shop/app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('frontend/base/d...')
> #20 /magento_shop/app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
> #21 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
> #22 /magento_shop/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
> #23 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
> #24 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
> #25 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
> #26 /magento_shop/app/design/frontend/venedor/default/template/page/1column.phtml(85): Mage_Core_Block_Abstract->getChildHtml('content')
> #27 /magento_shop/app/code/core/Mage/Core/Block/Template.php(241): include('/home/devxxabn/...')
> #28 /magento_shop/app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('frontend/venedo...')
> #29 /magento_shop/app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
> #30 /magento_shop/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
> #31 /magento_shop/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
> #32 /magento_shop/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
> #33 /magento_shop/app/code/local/TM/FireCheckout/controllers/IndexController.php(179): Mage_Core_Controller_Varien_Action->renderLayout()
> #34 /magento_shop/app/code/core/Mage/Core/Controller/Varien/Action.php(418): TM_FireCheckout_IndexController->indexAction()
> #35 /magento_shop/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
> #36 /magento_shop/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
> #37 /magento_shop/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
> #38 /magento_shop/app/Mage.php(683): Mage_Core_Model_App->run(Array)
> #39 /magento_shop/index.php(114): Mage::run('as_de', 'store')
> #40 {main}";s:3:"url";s:14:"/firecheckout/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"as_de";}

The tricky thing is that not all user accounts are affected by this issue. So i also truncated the mysql table `core_session` and all related customer quotes, but error still appears.

Also by using the Magento standard checkout (URL "checkout/onepage" instead of "firecheckout") the error remains.

**Comment by hreinberger** [comment]
Hi @jhoelzl 
first of all, firecheckout is unfortunately not supported out of the box, since our credit card flow requires two steps, which would have to be bound to only one submit event in a one page checkout. So erratic behavior is more or less expected with 3rd party checkouts.

I can't reproduce your behavior with the standard checkout either, so this could be related to an individual configuration in your shop. It would be best to get in touch with our tech support (tech.support[at]bspayone.com) so our colleagues there can sort out any misconfigurations with you.

**Comment by jhoelzl** [comment]
Hello @hreinberger,
thanks for your feedback. I did the custom changes which are recommended on Firecheckout website: https://templates-master.com/knowledgebase/faq/payone_core/

I know it worked some time before, so i do not think it has something to do with Firecheckout because i have not changed the module version of both modules (Payone and Firecheckout). 

Okay, i will get in touch with the tech support!
Regards,
Josef

**Comment by jhoelzl** [comment]
Ich konnte den Fehler finden. Bei manchen Kunden war in der mysql-Datenbank für das Attribute "payone_last_payment_method" eine Zahlungsart gespeichert, die es nicht mehr gibt. Beim Aufruf der Bestellseite wurde dann immer diese Zahlungsart geladen. Da diese jedoch nicht mehr verfügbar war, kam es zu diesem Fehler.

Eventuell könnte man das im Payone Modul noch verbessern? Also zuerst prüfen, ob die Zahlungsart überahupt nocht exitstiert, dann erst laden.

LG mastermind

**Comment by sprankhub** [comment]
Ich glaube, das Problem hatte ich auch mal. Wäre cool, wenn die PAYONE Extension beim Löschen einer Zahlungsart die Referenzen in der Quote auch löscht.

**Comment by T-Kuchel** [comment]
fixed with > [PR #299](https://github.com/PAYONE-GmbH/magento-1/pull/299)
