### ISSUE TITLE
Fehlende Übersetzung

### ISSUE THREAD

**Issue by axe1987** [PAYONE-GmbH/magento-1#300]
In der Version 4.2.1 wurde anscheinend der String "Payment has been processed." nicht in der Übersetzungsdateien (De) übersetzt.

Nur als Hinweis :)

Grüße axe1987

**Comment by fjbender** [comment]
@T-Kuchel Kannst du das kurz in der Übersetzungsdatei ergänzen (lassen)?

**Comment by axe1987** [comment]
Noch eine kleine Anmerkung.
Ich glaube "Bestellung aufgeben" ist nicht so passend.
Ist nach deutschem Recht nicht "Jetzt kaufen" oder "Zahlungspflichtig bestellen" passender?

**Comment by T-Kuchel** [comment]
Hallo @axe1987 ,

stimmt! Passen wir an > [PR #301 ](https://github.com/PAYONE-GmbH/magento-1/pull/301)

Beste Grüße

**Comment by T-Kuchel** [comment]
fixed with #301
