### ISSUE TITLE
PPE: Call to a member function getItems() on null

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#302]
We use Tideways and sometimes see the above mentioned error. The stack trace is:

    1...
    /var/www/shop/htdocs/app/code/community/Payone/Core/Model/Service/Paypal/Express/Checkout.php:219
    2Payone_Core_Model_Service_Paypal_Express_Checkout::returnFromPaypal
    /var/www/shop/htdocs/app/code/community/Payone/Core/controllers/PexpressController.php:101
    3Payone_Core_PexpressController::returnAction
    /var/www/shop/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php:418
    4Mage_Core_Controller_Varien_Action::dispatch
    /var/www/shop/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php:254
    5Mage_Core_Controller_Varien_Router_Standard::match
    /var/www/shop/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php:172
    6Mage_Core_Controller_Varien_Front::dispatch
    /var/www/shop/htdocs/app/code/core/Mage/Core/Model/App.php:365
    7Mage_Core_Model_App::run
    /var/www/shop/htdocs/app/Mage.php:686
    8Mage::run
    /var/www/shop/htdocs/index.php:83

Unfortunately, I do not know how this can be reproduced. Could you check it anyway?

Magento 1.9.3.10, Payone_Core 4.2.0.

**Comment by fjbender** [comment]
I'm not sure about being able to debug the issue in the module, but I'd find an entry point by checking whether the API response was valid and contained all expected fields. Maybe it's also an error handling issue.

**Comment by sprankhub** [comment]
Here you go:

    2018-12-03T10:04:34+00:00 DEBUG (7): WX1A17A9EPEDUQHA

Looking forward to your feedback!

**Comment by fjbender** [comment]
Thanks for that! Indeed, the Response doesn't contain all needed parameters. This is probably due to the api_version parameter missing in the getexpresscheckoutdetails request you send. I can't reproduce that here in a quick test.

**Comment by sprankhub** [comment]
I shortly checked the code and cannot see where the `api_version` parameter is set for this PPE call at all. How can we further debug the issue?

**Comment by fjbender** [comment]
`api_version` wasn't the issue, I checked and I was in error. I dove deeper in the logs of the `workorderid` you provided and compared them to a reference PayPal Express transaction. Seems to me that the user either wasn't redirected to PayPal or (and this is more likely) didn't sign into PayPal correctly resp. didn't complete the checkout there. I'd suppose it's a fraud pattern, or weird user behavior.

**Comment by sprankhub** [comment]
Fraud patterns or weird user behaviors still should not result in an uncaught error, right? ;-) So could you check if you can reproduce the issue by not logging in correctly, cancelling the payment etc.?

**Comment by gutschik** [comment]
In my case the error always was thrown if the total amount was lower than 50 euros and therefor the shipping rate would be greater than 0. 
I did not once get the error if the issued amount was greater than 50.

**Comment by fjbender** [comment]
@gutschik that's interesting. Has this behavior also been fixed with #303? If not, I'd be glad if you could open a new issue.

**Comment by gutschik** [comment]
@fjbender it surely has been fixed in #303 with `if (is_null($response->getPayData())) {` - I was just asking myself why paypal would hold back that data. 
And maybe there is a way to fix this error with a more user friendly approach. I will look into it and PR if I succeed.
