### ISSUE TITLE
Array to string conversion on TransactionStatus View

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#308]
If I open a specific transaction status (`/admin/payonecore_protocol_transactionStatus/view/id/123/`), I get the following notice:

    Notice: Array to string conversion  in /var/www/shop/app/design/adminhtml/default/default/template/payone/core/protocol/transactionstatus/view/tab/general.phtml on line 46

The issue is that the following fields are of type array:

- de
- id
- no
- pr
- ti
- va

Since this is mostly a debugging screen, maybe showing the value in a JSON encoded form is enough? Something like this:

    echo is_array($value)? Mage::helper('core')->jsonEncode($value) : $value

**Comment by fjbender** [comment]
@T-Kuchel Can you validate this, then test and review my PR #309?
