### ISSUE TITLE
Ratepay Integrationsprobleme

### ISSUE THREAD

**Issue by rkconsulting** [PAYONE-GmbH/magento-1#310]
Hi, wir haben immer noch ein paar Probleme mit der Implementierung von Ratepay in dieser Erweiterung.  Die Erweiterung wurde in diesem Magento 1.8.1 System installiert, die Referenzen zu jQuery aus den Ratepay- und Kreditkarten-Templates entfernt bzw. ersetzt durch entsprechende Prototype-Befehle.  Leider wird in keinen der von uns getesteten Szenarien die VAT_id korrekt an die API uebergeben (ist laut Log immer auf "null").  Ausserdem hat uns Payone mitgeteilt, dass der Geburtstag des Kunden sowohl im B2B-Modus als auch fuer private Kunden mit uebergeben werden muss (Kunde muss >= 18J alt sein).  Die Erweiterung fragt diesen scheinbar aber nur fuer private Kunden ab (und uebertraegt laut Payone Log fuer B2B-Kunden ohne hinterlegten Bday ebenfalls nur "null").  Koennt ihr diese Beobachtungen durch eure Tests bestaetigen oder liegt der Fehler in unserer Integration?  Danke!

**Comment by fjbender** [comment]
Moin,

ich kann das so nicht bestätigen. Ich habe in einem Stock-Magento 1.9.3.10 (die 1.8er Reihe haben wir hier leider nicht mehr im Testsystem) und dem aktuellen Modul (also ohne js-Modifikationen) getestet. die VAT-ID wird durchgereicht, ein Geburtsdatum ist nicht nötig.

**Comment by rkconsulting** [comment]
Danke fuer die Pruefung.  Ich zitiere mal den Tech Support von Payone:

"In Ihrem Account ist die Zahlungsart Ratepay Invoicing (RPV) freigeschaltet, das bedeutet Kauf auf Rechnung, nicht Ratenzahlung auf Rechnung, auch wenn es anders klingt.
Für Ratepay ist laut Dokumentation (Seite 6) das Geburtsdatum Pflicht."

Im Anhang die von Payone weitergeleitete Doku.  Unterstuetzt dieses Modul wirklich die Zahlart Ratepay Invoicing (RPV)?

[PAYONE_Platform_Ratepay_Addon_Complete_EN_2018-07-19.pdf](https://github.com/PAYONE-GmbH/magento-1/files/2807513/PAYONE_Platform_Ratepay_Addon_Complete_EN_2018-07-19.pdf)

**Comment by fjbender** [comment]
Ja, RPV wird definitiv unterstützt, z.B. mit dieser Konfiguration:

![image](https://user-images.githubusercontent.com/7370694/51908145-44222d80-23c9-11e9-814b-02d024a036ea.png)

**Comment by rkconsulting** [comment]
Ok, danke nochmals.  Dann gehen wir jetzt einfach davon aus, dass die Support-Leute bei Payone keinen Plan haben und suchen den Fehler bei uns bzw. bei Magento 1.8.
