### ISSUE TITLE
Notice: Undefined index: type in creditcard.phtml on line 218

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#314]
I get the following notice, when I order as a guest, select "shipping address same as billing address" and save the billing address:

    Notice: Undefined index: type  in /var/www/shop/app/design/frontend/base/default/template/payone/core/payment/method/form/creditcard.phtml on line 218

Please fix.

When fixing this, the unchecked usage of `$selectedCreditCartType['name']` should probably also be checked and fixed.

**Comment by fjbender** [comment]
Could reproduce, will issue a fix.

**Comment by sprankhub** [comment]
Fixed in https://github.com/PAYONE-GmbH/magento-1/pull/315.
