### ISSUE TITLE
Parameter {state} faulty or missing

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#321]
I often see the above mentioned error in the logs. It occurs every time a customer enters a region in a text field (no dropdown) and he does not use ISO 3166-2. Examples from a stock Magento 1.9.4.0:

- Indonesia / "Jawa barat"
- Indonesia / "East Java"
- Indonesia / "Bekasi"
- Japan / "HYOGO"
- Japan / "Hy?go"
- Japan / "hyg"
- Brasil / "Minas Gerais"

The issue is that by default, Magento only shows a text field for the region in certain countries like Indonesia, Japan or Brasil. Hence, the user enters his region in any format. Now the PAYONE API only takes ISO 3166-2 values, which of course fails.

I already had contact with the technical support and they suggested to insert regions for these countries in the DB like this:

    INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) values ('JP', 'JP-05', 'Akita');

In this case, the text input automagically changes to a dropdown. This probably works (untested), but is not really a nice solution. If this is the only way, this should at least be documented somewhere with all regions from all problematic countries.
But I see two general issues here, which should be checked by PAYONE IMHO:

1. The region is only mandatory for some payment methods and some countries (like PayPal and Japan). Hence, the PAYONE API should only require the region for these payment methods and these countries. Not for all payment methods / all countries.
2. The PAYONE API should accept the region in various formats and not only ISO 3166-2 if the respective payment method accepts it as well. For instance, PayPal requires a region for the above mentioned countries, but it does not care about the format.

Could you please check that?

**Comment by hreinberger** [comment]
Hi @sprankhub 
we recently documented this in our latest revision of the documentation, see https://github.com/PAYONE-GmbH/docs/commit/84bae06761ed70e23e7f725509f00b27271f6374 (Chapter "configuration of state codes for international shops"), the lists with codes can be found in Chapter 5.10 of our server API documentation. The "state" parameter is only mandatory in the following countries: US, CA, MX, AR, BR, CN, ID, IN, JP and TH.

I agree that this is pretty clunky. The nicest way would be to deliver the needed codes in our plugin, though this could interfere with other plugins, which could rely on other codes. I'll address this internally with our core API team to see if there's anything we can streamline, but I'm afraid there won't be any quick solutions on this issue :(

**Comment by sprankhub** [comment]
Thanks for updating the documentation!

Yeah it seems that in either case, there is no nice solution for the topic.

IMHO, you should add the following information to the documentation as well:

> The "state" parameter is only mandatory in the following countries: US, CA, MX, AR, BR, CN, ID, IN, JP and TH.

**Comment by hreinberger** [comment]
consider it done! 👍
