### ISSUE TITLE
Problem with Amazon pay data

### ISSUE THREAD

**Issue by ikorlevic** [PAYONE-GmbH/magento-1#326]
Hi,
we have a problem with the data received from Amazon pay. Since our customers like to use the packing stations they also enter their post number in the address fields during Amazon Pay checkout. The problem is that the fillAddressFields function has a hard coded map of fields that are saved in the database. The other problem is that we cannot easily extend it because this function is private. Can you please try to make a version that saves ALL data received from Amazon to address fields or at least make the function extendable by making it protected instead of private. Here is how I solved the problem for the time being, but I think there could be a better solution to this. The function in question is in Payone/Core/Model/Service/Amazon/Pay/Checkout.php
in original it is private. 

`
protected function fillAddressFields($type, $address, $data)
    {

        $mapping = [
            'firstname'       => 'firstname',
            'lastname'        => 'lastname',
            'email'           => 'email',
            'telephonenumber' => 'telephone',
            'company'         => 'company',
            'street'          => 'street',
            'zip'             => 'postcode',
            'city'            => 'city',
            'state'           => 'region',
            'country'         => 'country_id',
        ];
        foreach ($data as $key => $value) {
            $key = array_key_exists($key, $mapping) ?
                $key : str_replace("{$type}_", "", $key);
            if (array_key_exists($key, $mapping) && !empty($value)) {
                $address->setData($mapping[$key], $value);
            }
        }

        // ikorlevic: part for adding the po box data as new street line
        if (isset($data[$type . '_pobox'])) {
            if ($data[$type . '_pobox']) {
                $street   = $address->getStreet();
                $street[] = $data[$type . '_pobox'];
                $address->setStreet($street);
            }
        }

        if (strlen($data[$type . '_street']) <= 3 || is_int($data[$type . '_street'])) {
            $nr     = $address->getStreet();
            $street = [
                $data[$type . '_company'],
                $nr
            ];
            $address->setStreet($street);
        }

        return $address;
    }`

Thanks.

**Comment by T-Kuchel** [comment]
Hello @ikorlevic ,

at first thank you for this information. We will investigate on this.
Maybe there is a smarter way to handle / determine "Packstation" - addresses.
Therefore we have to talk with amazon.

If we have any  feedback or solution we will notify you.

regards
Timo

**Comment by ikorlevic** [comment]
Hi Timo.thanx
