### ISSUE TITLE
Ratepay: Payment Method not available when tx_limit_invoice_min / tx_limit_invoice_max is NULL

### ISSUE THREAD

**Issue by JEreth** [PAYONE-GmbH/magento-1#327]
Somehow our Ratepay config that comes from the backend does not contain min/max values. Thereby the config values from tx_limit_invoice_min  and tx_limit_invoice_min  are null.

This causes the issue that the payment method is not available as the available query in _Payone_Core_Model_Payment_Method_Ratepay_ and _Payone_Core_Model_Payment_Method_RatepayDirectDebit_ contains the following part:
` {$oQuote->getGrandTotal()} BETWEEN tx_limit_invoice_min AND tx_limit_invoice_max AND`

Maybe we can make this constraint conditional or set large default values.

**Comment by fjbender** [comment]
According to the specification from Ratepay given to us prior to implementation this shouldn't occur. I'd like to investigate further before introducing any changes to the plugin. Please send the Merchant ID (mid) and ideally a timestamp of a Ratepay "profile" request (occurs when saving the Ratepay payment config to the database) to integrations@bspayone.com.

Thanks
Florian

**Comment by JEreth** [comment]
Thanks for the feedback, so we assume this is a configuration mistake on ratepay/payone side. We created a ticket for this.
