### ISSUE TITLE
Apple Pay Support

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#330]
Do you support Apple Pay or plan to support it soonish?

**Comment by hreinberger** [comment]
Hi @sprankhub 
yes, we plan to support apple pay in the future, though the payment method is still in development on our platform. So we have to wait until this is more or less done to start developing the integration. 

Our current planning is that magento would certainly be one of the first integrations to get Apple Pay support, but at this point we can't give you a timeline on this.

So to answer your questions: Yes we will support Apple Pay, but not yet and probably not as soonish as we would like ;)
