### ISSUE TITLE
Transmit Order Number Instead of Transaction Number to PayPal

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#332]
In the PayPal backend, you can get monthly reports under Berichte > Kontoauszüge > Monatliche Kontoauszüge. These reports are important for the bookkeeping department. When using the Magento PayPal module, the column "Rechnungsnummer" is filled with the Magento order number. However, when using PayPal via PAYONE, this column is filled with the txid. This leads to issues in the bookkeeping department. Could you transmit the order number instead of the transaction number to PayPal?

**Comment by hreinberger** [comment]
Hi @sprankhub 
the field "Rechnungsnummer" is filled with the txid by our platform, so there's unfortunately no easy way for the plugin to fill this one with the magento invoice number.

However, there is a per-merchant configuration on our platform, which can overwrite the txid with the content of the parameter narrative_text, so if it's absolutely necessary you could let our service enable this configuration and then send the magento invoice number in the narrative_text parameter (configurable in the payment method configuration in magento). This way you could potentially display the magento invoice- or order number in the paypal reports.

Keep in mind that this is a per-merchant config, so this will always be a highly individual solution.

**Comment by sprankhub** [comment]
Thanks for the quick answer @hreinberger!
