### ISSUE TITLE
Fehlerhafte Berechnung von Steuern in Magento 1.9.4.1

### ISSUE THREAD

**Issue by dbachmann** [PAYONE-GmbH/magento-1#336]
Es wird zur Zeit die aktuellste Version von Magento und Payone genutzt. Allerdings wird die Steuer falsch berechnet. Die Preise, die im Shop angegeben sind enthalten bereits die MwSt. allerdings wird hier durch Payone nochmals eine Steuer draufgerechnet. Wenn ich die Extension deaktiviere, stimmt es wieder. Im Anhang dazu ein Screenshot mit aktivierter Payone-Extension und einmal ohne. 
![payone](https://user-images.githubusercontent.com/1921769/56506173-f592b400-651d-11e9-93e9-546eb14dee65.JPG)
![payone2](https://user-images.githubusercontent.com/1921769/56506174-f62b4a80-651d-11e9-93d0-c8725513778a.JPG)

Alle anderen Extensions habe ich bereits komplett deaktiviert. Das Problem taucht tatsächlich nur auf, wenn Payone aktiviert ist.

**Comment by hreinberger** [comment]
Hi @dbachmann 
ich habe gerade mal versucht, das mit einem 1.9.4.1 Testshop nachzuspielen, kann das hier ad hoc aber nicht reproduzieren. Das Thema scheint irgendwie mit der Konfiguration des Shops zusammenhängen. Der beste Weg wäre hier, wenn du einmal die Kollegen vom Tech Support (tech.support[at]bspayone.com) anschreibst. Am besten mit einem Export der Konfiguration (über PAYONE --> Konfiguration --> Konfiguration exportieren). Die Kollegen können dann besser auf das Thema eingehen und eventuelle Bugs im Plugin aufdecken.

**Comment by hreinberger** [comment]
geschlossen wegen Inaktivität.
