### ISSUE TITLE
Transmit Order Number Instead of Transaction Number to PayPal - Creditmemos

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#337]
This is a follow-up of issue #332.

If the per-merchant configuration on the PAYONE platform, which can overwrite the txid with the content of the parameter narrative_text as described in #332, is activated, PayPal gets the order number correctly if an authorization is executed. However, this does not work for creditmemos. For creditmemos, the narrative_text is not transmitted to PayPal. As the PAYONE Tech Support told me, the issue is that the narrative_text is not submitted by the PAYONE extension for creditmemo requests. Could you implement that?

**Comment by hreinberger** [comment]
yep, seems reasonable. We'll look into that.

**Comment by sprankhub** [comment]
Any update? :)

**Comment by fjbender** [comment]
This is currently in the development pipeline. However, currently there are higher prioritized issues.
