### ISSUE TITLE
Wrong IP Submitted to PAYONE

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#339]
One of my customers started to use some fraud checks based on the IP, which is transmitted from Magento to PAYONE. Now we got a whole lot of errors like this:

> Payment denied after Velocity IP check

After talking to the technical support, they told us that we always transmit local IPs (either `127.0.0.1` or `::1`). After checking the `x_forwarded_for` value stored in the orders, I see the following format:

    123.456.789.123, 127.0.0.1

So the real IP is the first entry, the local IP is the last entry. In https://github.com/PAYONE-GmbH/magento-1/pull/112 @phizab changed `array_shift` to `array_pop`, which is obviously wrong in our case. To be honest, I am not totally sure how the order of the IPs is defined. Maybe it is a better idea to take the array of IPs, filter the local IPs `127.0.0.1` and `::1` and then take the first one? This approach is probably more robust than the current one.

What do you think?

If this helps: We use Apache as a backend server plus Varnish with an nginx SSL offloader.

**Comment by fjbender** [comment]
Well, this is tricky. I suppose we can never know, which IP in the array is the true one. The way I see it, we receive it from `Mage_Sales_Model_Order` directly, using either `getRemoteIp()` or (in your case, as you have "Proxy Mode" enabled, I suppose) `getXForwardedFor()`. It would probably be smart to eliminate any IP that doesn't make sense and then take the first one that remains, but this won't be problem-free either.

Is there any way to predict the order of the IPs coming from `getXForwardedFor()`?

**Comment by fjbender** [comment]
Makes sense! It seems, though, that not all clients adhere to the specification, or @phizab's change wouldn't have worked in their case.

We should probably revert this to follow RFC 7239, and additionally make sure that no nonsense-IPs are included in order to not confuse any API-side checks.

**Comment by fjbender** [comment]
I created a PR for this issue, but would like a second opinion by any user affected from this change, i.e. by @phizab

**Comment by phizab** [comment]
I think MDN and RFC win, so it should match with them. The PR needs to be reverted. Sorry for the missing research in my request.

**Comment by fjbender** [comment]
Thanks for your feedback, and don't worry! We'll review and merge #342. Is there any explanation why it's different in your setup?

**Comment by phizab** [comment]
To be honest I can't remember the exact reason for the PR, since we are not using the address check. In the worst case I only read the comment above the referenced line and thought that were a special reason for using the last IP. I will check our setup next week, when I'm back in office.

**Comment by milansimek** [comment]
> It seems, though, that not all clients adhere to the specification, or @phizab's change wouldn't have worked in their case.

The extra IPs are usually added on the server side when proxying to upstream servers. I can confirm the first IP is the client IP when using the following set-ups:

- CloudFlare > Nginx > Varnish > Apache
- Nginx > Varnish > Apache
- Nginx > Apache

I hope this helps!
