### ISSUE TITLE
Nachnahmegebühr verschwunden

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#343]
Bei uns ist plötzlich die Nachnahmegebühr verschwunden.

Im `shipping.phtml` findet sich folgender Code:

```php

<?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
// bzw.
<?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
```

Diese landen hier:
```php

// app/code/core/Mage/Tax/Block/Checkout/Shipping.php
public function getShippingIncludeTax()
{
    return $this->getTotal()->getAddress()->getShippingInclTax();
}
public function getShippingExcludeTax()
{
    return $this->getTotal()->getAddress()->getShippingAmount();
}
```

Dummerweise werden nur die Base Amounts gefüllt

```php
protected function _setNewPayonePaymentAmount($oQuote, $oAddress, $dPaymentFee) 
{
    // [...]
    $oAddress->setBaseShippingAmount($dNewShippingAmount);
    $oAddress->setShippingAmount(
        $oQuote->getStore()->convertPrice($dNewShippingAmount, false)
    );
}
```

Ich habe aktuell KEINE AHNUNG warum das früher funktioniert hat. Ich finde weder im Magento noch im Payone Modul einen Hinweis, dass es jemals anders war.

Ich schicke gleich mal einen PR, der aber nicht generisch genug ist. Die Steuerwerte werden nicht berechnet, aber für meinen Fall reicht das, evtl. ist das ein guter Anfang für andere.

**Comment by fjbender** [comment]
Da du "plötzlich" schreibst, gehe ich davon aus, dass ich die Antwort auf die Frage schon kenne, aber dennoch: Kannst du jeglichen Zusammenhang mit Updates oder anderen Änderungen ausschließen?

So richtig reproduziert bekomme ich das nämlich auch nicht. Ich gebe dir aber recht, im Code sieht das fishy aus.

**Comment by Schrank** [comment]
Ich dachte ich hätte das Problem gefunden, aber nein. IRGENDEIN Update wird es gewesen sein. Ich habe nur das Problem noch nicht gefunden ,daher ist der PR auch wieder zu.
