### ISSUE TITLE
Crash update from 3.7.8 to 4.3.0

### ISSUE THREAD

**Issue by Yerokhov** [PAYONE-GmbH/magento-1#351]
Hi! When we trued update module from 3.7.8 to 4.3.0 (previously delete old files,clear cache ), we get errror
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'payone_payment_ban' doesn't exist, query was: SELECT `main_table`.* FROM `payone_payment_ban` AS `main_table` WHERE (`customer_id` = '')

Trace:
#0 lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 lib/Varien/Data/Collection/Db.php(572): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 app/code/community/Payone/Core/Model/Domain/PaymentBan.php(50): Varien_Data_Collection_Db->load()
#10 app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php(100): Payone_Core_Model_Domain_PaymentBan->loadByCustomerId(NULL)
#11 app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php(77): Payone_Core_Block_Checkout_Onepage_Payment_Methods->getRestrictedMethods()
#12 app/code/core/Mage/Payment/Block/Form/Container.php(46): Payone_Core_Block_Checkout_Onepage_Payment_Methods->getMethods()
#13 app/code/core/Mage/Core/Block/Abstract.php(297): Mage_Payment_Block_Form_Container->_prepareLayout()
#14 app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#15 app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('checkout/onepag...', 'checkout.paymen...')
#16 app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('checkout/onepag...', 'checkout.paymen...')
#17 app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#18 app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#19 app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#20 app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#21 app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#22 app/code/local/Amasty/Scheckout/controllers/Rewrite/OnepageController.php(44): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#23 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amasty_Scheckout_Rewrite_OnepageController->indexAction()
#24 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#25 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#26 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#27 app/Mage.php(686): Mage_Core_Model_App->run(Array)
#28 index.php(83): Mage::run('', 'store')
#29 {main}` 
magento 1.9.4.1, php - 7.3.0
Help, pls!

**Comment by fjbender** [comment]
Looks like the database upgrades were not (completely) executed. Can you make sure all the updates from https://github.com/PAYONE-GmbH/magento-1/tree/master/app/code/community/Payone/Core/sql/payone_core_setup habe been run?
