### ISSUE TITLE
Paypal express - nicht erlaubtes Lieferland

### ISSUE THREAD

**Issue by axe1987** [PAYONE-GmbH/magento-1#352]
Hallo.

Wir haben folgendes Phänomen:

Es kam eine Bestellung in unser Magento (1.9.4.1) über PayPal Express (vermutlich Express Checkout) bei dem ein Lieferland übergeben wurde das in unserem Magento System nicht erlaubt ist.

Unsere Vermutung ist das im PayPal die Adresse hinterlegt war und durch die Zahlungsart an Magento weitergereicht wurde.

Ist so ein Problem bekannt, kann das passieren, oder liegen wir da falsch?

Kann sowas auch bei Amazon Pay passieren?

Payone Plugin Version: 4.2.1

Mit freundlichen Grüßen
axe1987

**Comment by riconeitzel** [comment]
Wir haben ein solches Problem auch schon mit PayPal beobachtet.

**Comment by T-Kuchel** [comment]
Hallo @axe1987 ,
hallo @riconeitzel ,

wir lassen da einmal detailliert in den Code schauen und melden uns bei Neuigkeiten bzw. fixen dies, wenn nötig.

Beste Grüße aus Kiel

**Comment by gndk** [comment]
Kann ich bestätigen, kommt bei mir auch öfters mal vor. Auch bei Amazon Pay.

**Comment by axe1987** [comment]
Gibt es hier schon neue Erkenntnisse??

Grüße
axe1987

**Comment by hreinberger** [comment]
Hi @axe1987 
wir haben das Thema für die Entwicklung eingeplant. PR mit fix folgt hoffentlich zeitnah.

**Comment by T-Kuchel** [comment]
Hallo @axe1987 , @gndk , @riconeitzel ,
wir haben nun ein wenig Zeit gehabt an dieser Stelle tiefer zu graben.
Das Problem ist hier nicht das erlaubte Rechnungs-Land. Es muss explizit in der Versandart definiert sein in welche Länder geliefert werden kann.
Das Verhalten ist auch unabhängig von der Zahlungsart bzw. dem Zahlartenanbieter. Ob nun also PAYONE oder Vanilla-Magento, das Verhalten ist immer gleich.

Hilft das weiter?

Beste Grüße aus Kiel
Timo

**Comment by hreinberger** [comment]
Ich schließe hier mal wegen Inaktivität.

**Comment by riconeitzel** [comment]
👍 danke
