### ISSUE TITLE
credit card expiry date not saved properly (hosted iFrame)

### ISSUE THREAD

**Issue by phoenix-schwarz** [PAYONE-GmbH/magento-1#355]
If you are using the hosted iFrame for CC payments, the expiration date is not saved properly in the sales_flat_order_payment table.

<img width="312" alt="Screenshot 2019-07-24 at 09 02 48" src="https://user-images.githubusercontent.com/10234000/61772424-85345100-adf2-11e9-8aa5-ae4408fa2ac2.png">

**Comment by phoenix-schwarz** [comment]
This one is a duplicate: https://github.com/PAYONE-GmbH/magento-1/issues/354 posted with the wrong user.

**Comment by alexanderbug** [comment]
Any update for this topic?

**Comment by fjbender** [comment]
I was unable to reproduce this on a fresh Magento.

For debugging, one would have to work their way up from \Payone_Core_Model_Payment_Method_Creditcard::assignData, where the expiry date is saved to the table.

**Comment by alexanderbug** [comment]
@hreinberger this is just the representation in the order. the information is available in the request. @igloominusx has an idea for a workaround. we will test it and report
