### ISSUE TITLE
Remove Old Licensemanager Stuff

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#365]
If I saw correctly, the Licensemanager module was removed. There are still files present, which should probably be removed as well:

* https://github.com/PAYONE-GmbH/magento-1/blob/master/app/locale/de_DE/Payone_Licensemanager.csv
* https://github.com/PAYONE-GmbH/magento-1/blob/master/app/locale/en_US/Payone_Licensemanager.csv
* https://github.com/PAYONE-GmbH/magento-1/tree/master/app/design/adminhtml/default/default/template/payone/licensemanager

**Comment by hreinberger** [comment]
thanks, I created a PR for that. We'll test this and merge later
