### ISSUE TITLE
Better Handling of Issues During Transaction Status Processing

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#370]
Sometimes, there are issues with the transaction status processing. Hence, invoices are not created or invoices are not captured. I saw the following root causes:

* Deadlock issues during invoice creation.
* Wrong payment config ID issues during invoice creation (known PAYONE bug as seen in other issues).

An example entry from `payone_cron.log` for a deadlock issue:

    payone_cron.log:2019-09-02T12:23:10+00:00 INFO (6): ID: 12345 - Process - Trigger event payone_core_transactionstatus_appointed
    payone_cron.log:2019-09-02T12:23:14+00:00 INFO (6): ID: 12345 - Execute - Error during service execution, set status to error with message SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: SELECT `eav_entity_store`.* FROM `eav_entity_store` WHERE (entity_type_id = :entity_type_id) AND (store_id = :store_id) FOR UPDATE
    payone_cron.log:2019-09-02T12:23:14+00:00 INFO (6): ID: 12345 - Execute - Finished

I know that deadlocks need to be solved on client side. However, the handling of such issues could be much better in the PAYONE extension. Currently, the following happens:

* Transaction status processing of appointed status fails with an error. Hence, no invoice is created. There is no information about that and the processing is not re-tried at all.
* Transaction status processing of paid status fails / is shown as running forever, if the invoice has not been created during the appointed transaction status processing. The invoice is not found and hence, cannot be marked as paid.

I would love to see a better handling of such issues:

1. Provide the possibility to send a mail if transaction status processing fails.
2. Re-try transaction status processing X times before letting it fail completely.
3. Wait for the execution of the paid transaction status until the appointed transaction status has been processed successfully.

**Comment by sprankhub** [comment]
Any feedback would be highly appreciated :)

**Comment by fjbender** [comment]
Hi Simon,

This somehow went through my inbox, sorry.

@T-Kuchel can you maybe walk @Anton-Levitsky through this and see, if he'll be able to do something about this?

**Comment by sprankhub** [comment]
#375 seems to be related. Any new status?

**Comment by sprankhub** [comment]
What is the current status here? Thanks!

**Comment by fjbender** [comment]
This somehow got stuck in QA, because it is difficult to test. :/ I'll see how we can move this forward.

**Comment by sprankhub** [comment]
Any progress @fjbender? Sorry to bug again, but this would make things so much easier...

**Comment by fjbender** [comment]
#375 is now in active testing but still has some bugs. It went back to the developer, who is working on it.

**Comment by T-Kuchel** [comment]
#415 is merged into master.
