### ISSUE TITLE
Amazon Checkout Address/Payment lädt nicht

### ISSUE THREAD

**Issue by axe1987** [PAYONE-GmbH/magento-1#372]
Hi,

ich habe ein Problem das in meinem Testsystem die IFrames für die Adress-/ und Bezahlmethoden nicht lädt.

Woran kann das liegen. Die Javascript origins etc ... habe ich geprüft.

Gibt es hier einen Tipp wonach ich schauen kann?

Grüße Axe

**Comment by fjbender** [comment]
Ein häufiger Fehler ist auch, dass der Testshop kein https einsetzt. Muss kein offizielles Zertifikat sein, self-signed reicht.
