### ISSUE TITLE
Ratepay: Warning: explode() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by phoenix-schwarz** [PAYONE-GmbH/magento-1#379]
This line of codes expects to get a comma separated string of countries:

https://github.com/PAYONE-GmbH/magento-1/blob/c78bddf76ae6502abe2f55aaa511702c06827753/app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php#L692

but:
$config->getRatepayDirectDebitSpecificCountry()

which is here:
https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Config/Payment/Method.php#L1468

returns an array - this won't work properly

**Comment by fjbender** [comment]
Thanks for pointing this out. We're currently refactoring Ratepay in #371 - I'll check if we can fix it there (if it's not fixed already).

**Comment by fjbender** [comment]
This has been resolved with #371.
