### ISSUE TITLE
Question - Payment with Sofortüberweisung

### ISSUE THREAD

**Issue by jaashy89** [PAYONE-GmbH/magento-1#382]
According to our business logic we process orders which are paid-sucessfully, for that we use transactional status of Payone. 
But we are facing issue with Payment with Sofortüberweisung
STEPS
1.when user uses this method it redirects to klarna and status is 'REDIRECT'
2. If user successfully made the transaction status remains 'REDIRECT'
3. if user didn't pay and close the klarna window or go back directly to our shop, status remains 'REDIRECT'

we want some how we can differentiate whether tranction is successful or not , how we can achieve this goal

**Comment by fjbender** [comment]
These type of questions are best answered by our technical support team, as they might depend on your system and settings and require in-depth discussion.

The general approach would be to look for the appointed transaction status, assuming you have configured the transaction status URL in the Merchant Interface.

If this proves to be an issue in the module itself, feel free to reopen this issue or create a new one.
