### ISSUE TITLE
Chrome/Safari private mode - unable to order in private mode

### ISSUE THREAD

**Issue by phoenix-schwarz** [PAYONE-GmbH/magento-1#384]
On an iPad, it is not possible to order in Safari and Chrome in private mode.

1.     Open Safari or Chrome in private mode
2.     navigate to catalog
3.     add a product to the shopping cart
4.     go to the shopping cart
5.     click on "Checkout"

We're getting the error: "ReferenceError: Can't find variable: payoneSwitchOnlineBankTransfer"

**Comment by hreinberger** [comment]
I only have an iPhone with iOS 13.1.3 on hand, but tried it anyway. Screencast here: https://imgur.com/a/DGgEUF6 
I could proceed to the checkout, but the whole site was glitchy. This could be due to iOS 13 still being a dumpster fire. @fjbender will check this one out on an iPad.

**Comment by fjbender** [comment]
No issues on iPad with iOS 12.4 and stock Magento

**Comment by phoenix-schwarz** [comment]
Have you used the "private mode"?

**Comment by fjbender** [comment]
Updated to iPad OS 13.1, tested again on stock Magento, couldn‘t reproduce your issue. However, there was an issue with the credit card iFrames @hreinberger 

Maybe this only occurs in a specific configuration. Could you send a config export to magento@bspayone.com referring to this issue?

**Comment by alexanderbug** [comment]
I have sent you the configuration and a screencast

**Comment by hreinberger** [comment]
Thanks for the Screencast!
My iPhone updated to iOS 13.2, but I still couldn't reproduce this issue on your website. I'll try again with my girlfriend's iPad tonight. In the meantime It'd be great if you could somehow access the safari dev console on the iPad. You seem to need a mac and a cable connection: https://www.lifewire.com/activate-the-debug-console-in-safari-445798 

I also found this app that gives you a dev console without a nearby mac: https://apps.apple.com/de/app/mihtool-basic-web-debugger/id584739126 maybe that's worth a try. It comes with its own in App Browser though, so maybe the issue won't be reproducable in this.

**Comment by hreinberger** [comment]
So my girlfriend let me use her iPad non-pro 2018 with iPadOS 13.2 and while I saw some glitches like jumping "add to cart" button, I could get into the checkout without any error messages. I've uploaded a screencast: https://imgur.com/a/PlPH9KS

So in this case it would be really helpful if you could connect a mac to the iPad and inspect the behavior there. Also, does this issue still occur with iPadOS 13.2?
