### ISSUE TITLE
[1095: Parameter {wallettype} faulty or missing]

### ISSUE THREAD

**Issue by chrispooh15** [PAYONE-GmbH/magento-1#387]
Hallo,

ich habe diese Fehlermeldung mit die letzte Version. Was kann ich zu tun?

Viele Grüße,
Krisztian

**Comment by T-Kuchel** [comment]
Hallo @chrispooh15 ,

leider fehlt hier ein wenig der Kontext.
Für Details zu dem Fehler empfehle ich aber mal auf https://docs.payone.com vorbeizuschauen.
Folgende Seiten sollten am hilfreichsten sein: [PreAuthorization](https://docs.payone.com/pages/releaseview.action?pageId=1213939) und [Error Messages](https://docs.payone.com/display/public/PLATFORM/Error+messages)

Ansonsten kontaktiere gerne direkt unseren Technical - Support (tech.support@bspayone.com), der Dir in solchen Fragen gut weiterhelfen kann.

Grüße aus Kiel
Timo
