### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#388]
You probably want to add translation wrappers here and handle the translation correctly:

https://github.com/PAYONE-GmbH/magento-1/blob/63718e6d22059ef44b7105ad346724cc1986ce15/app/code/community/Payone/Core/Block/Adminhtml/System/Config/Payment.php#L121

https://github.com/PAYONE-GmbH/magento-1/blob/63718e6d22059ef44b7105ad346724cc1986ce15/app/code/community/Payone/Core/Block/Adminhtml/System/Config/Payment.php#L124

**Comment by T-Kuchel** [comment]
Hi @sprankhub ,

we will take care of this.

Regards from Kiel
Timo

**Comment by T-Kuchel** [comment]
fixed with #391
