### ISSUE TITLE
Credit card year four digits - and error doesn't help

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#390]
Many customers are used to type the month / year as 12/20 - therefore we have many customers which complain that they get an error which says "Verfallsdatum ungültig".

Is it possible to change either the year format or at least add a hint, that the year needs to be four digits to the error? Or can I change the translation of the error somewhere?

**Comment by sprankhub** [comment]
System > Configuration > PAYONE > General > Kreditkarte - hosted-Iframe Übersetzungen > Übersetzung der Fehlermeldungen

**Comment by hreinberger** [comment]
As @sprankhub already wrote: You can configure the error messages in the hosted iFrame config to show messages that are more in line with your CI. In there, you can also make the date fields dropdowns, which I prefer on desktop, but can be finicky on mobile.
