### ISSUE TITLE
Mage registry key "payone_core_config_1" already exists

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#392]
Since the latest update to 4.5.0 (from 4.4.0), I get this error from time to time:

    Cron error while executing payone_core_cronjob_transactionstatus_process:

    Mage_Core_Exception: Mage registry key "payone_core_config_1" already exists in /var/www/share/shop.de/htdocs/app/Mage.php:598
    Stack trace:
    #0 /var/www/share/shop.de/htdocs/app/Mage.php(226): Mage::throwException('Mage registry k...')
    #1 /var/www/share/shop.de/htdocs/app/code/community/Payone/Core/Helper/Registry.php(62): Mage::register('payone_core_con...', Object(Payone_Core_Model_Config), false)
    #2 /var/www/share/shop.de/htdocs/app/code/community/Payone/Core/Model/Service/InitializeConfig.php(75): Payone_Core_Helper_Registry->register('payone_core_con...', Object(Payone_Core_Model_Config))
    #3 /var/www/share/shop.de/htdocs/app/code/community/Payone/Core/Helper/Config.php(46): Payone_Core_Model_Service_InitializeConfig->execute('1', true)
    #4 /var/www/share/shop.de/htdocs/app/code/community/Payone/Core/Helper/Config.php(74): Payone_Core_Helper_Config->getConfigStore('1')
    #5 /var/www/share/shop.de/htdocs/app/code/community/Payone/Core/Helper/Data.php(197): Payone_Core_Helper_Config->getConfigMisc('1')
    #6 /var/www/share/shop.de/htdocs/app/code/community/Payone/Core/Model/Service/TransactionStatus/Execute.php(116): Payone_Core_Helper_Data->logCronjobMessage('ID: 542283 - Ex...', '1')
    #7 /var/www/share/shop.de/htdocs/app/code/community/Payone/Core/Model/Service/TransactionStatus/Execute.php(63): Payone_Core_Model_Service_TransactionStatus_Execute->execute(Object(Payone_Core_Model_Domain_Protocol_TransactionStatus))
    #8 /var/www/share/shop.de/htdocs/app/code/community/Payone/Core/Model/Cronjob/TransactionStatus/Worker.php(49): Payone_Core_Model_Service_TransactionStatus_Execute->executePending()
    #9 /var/www/share/shop.de/htdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Payone_Core_Model_Cronjob_TransactionStatus_Worker->execute(Object(Aoe_Scheduler_Model_Schedule))
    #10 /var/www/share/shop.de/htdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
    #11 /var/www/share/shop.de/htdocs/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
    #12 /var/www/share/shop.de/htdocs/app/code/local/Xtento/OrderExport/Model/Observer/Cron/Config.php(24): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
    #13 /var/www/share/shop.de/htdocs/app/code/core/Mage/Core/Model/App.php(1374): Xtento_OrderExport_Model_Observer_Cron_Config->addCronjobsToConfig(Object(Varien_Event_Observer))
    #14 /var/www/share/shop.de/htdocs/app/code/core/Mage/Core/Model/App.php(1347): Mage_Core_Model_App->_callObserverMethod(Object(Xtento_OrderExport_Model_Observer_Cron_Config), 'addCronjobsToCo...', Object(Varien_Event_Observer))
    #15 /var/www/share/shop.de/htdocs/app/Mage.php(451): Mage_Core_Model_App->dispatchEvent('default', Array)
    #16 /var/www/share/shop.de/htdocs/cron.php(83): Mage::dispatchEvent('default')
    #17 {main}

**Comment by T-Kuchel** [comment]
Hi @sprankhub ,

we will investigate on this and come back to you with information or a fix.

Regards Timo

**Comment by Schrank** [comment]
This happens 4-10 times a day for us and each time a customer can't checkout but gets an error instead and hopefully clicks the error away and tries again.

Any update on this?

**Comment by sprankhub** [comment]
@Schrank I think #393 contains the fix.

**Comment by Schrank** [comment]
Thanks @sprankhub. I'm pretty sure, this removes the sign, but whatever creates the bug should be investigated as well.

**Comment by Schrank** [comment]
@fjbender @T-Kuchel Any chance, this fix will be officially release soon? :-)

**Comment by hreinberger** [comment]
We have another feature in the works we'd like to see in the next release and quite frankly I don't want to encourage merchants to update their shop during the holiday sale season. Therefore we're aiming for an early January release.

**Comment by oneserv-heuser** [comment]
@hreinberger  How is it going? We're also having the error in our checkout process sometimes. When will the release including this bugfix be?

**Comment by hreinberger** [comment]
Hi, unfortunately we won't release this January (as you may have guessed). We want to pack one more feature into this release which will make Amazon payments much more robust, so we decided to push back the release window by about 4 weeks.
