### ISSUE TITLE
Hosted iFrame Translation for swedish doesn't work

### ISSUE THREAD

**Issue by rofthedeep** [PAYONE-GmbH/magento-1#394]
We are using the hosted iframe solution for credit card payment.

It works for every language we tried, except for swedish.

For example for french (working):
<img width="842" alt="Bildschirmfoto 2019-11-25 um 10 11 05" src="https://user-images.githubusercontent.com/2420176/69527161-000da400-0f6c-11ea-9cd7-b8b74c898f6f.png">

Swedish with errors:
<img width="862" alt="Bildschirmfoto 2019-11-25 um 10 11 37" src="https://user-images.githubusercontent.com/2420176/69527184-0f8ced00-0f6c-11ea-8fd9-0a99e88b7cd1.png">

If the error occurs all the input fields are not loaded.

**Comment by fjbender** [comment]
Unfortunately, Swedish is not supported. Only German, English, French, Italian, Spanish, Portugese, and Dutch are available.

However, it should be possible to define own languages by following this structure

```
        en: {
            months: {
                month1: "1",
                month2: "2",
                month3: "3",
                month4: "4",
                month5: "5",
                month6: "6",
                month7: "7",
                month8: "8",
                month9: "9",
                month10: "10",
                month11: "11",
                month12: "12"
            },
            invalidCardpan: "Invalid card number. Please verify your card data.",
            invalidCvc: "Invalid Card Verification Value. Please verify your card data.",
            invalidPanForCardtype: "Card type does not match card number. Please verify your card data.",
            invalidCardtype: "Card type invalid. Please verify your card data.",
            invalidExpireDate: "Expiry date invalid. Please verify your card data.",
            invalidIssueNumber: "Invalid Issue-Number (card sequence number). Please verify your card data.",
            transactionRejected: "Transaction has been rejected. Please verify your data.",
            pleaseSelectCardType: "Select cardtype",
            placeholders: {
                cardpan: '',
                cvc: '',
                expireMonth: '',
                expireYear: '',
                issueNumber: ''
            }
        }
``` 

As this is not a part of the module, please contact the Merchant Service with any issues regarding to this.
