### ISSUE TITLE
Name should be changed for modman

### ISSUE THREAD

**Issue by Elfen-Service** [PAYONE-GmbH/magento-1#40]
Should be Changed from magento-1 to Payone_Magento1 or similar because its too general.

**Comment by fjbender** [comment]
As I see it, we would need to change the repository name for that. We can't do that, for a variety of reasons.

However, I see that this repo's name is quite general (in a composer context it's not much of a problem as there are namespaces). If there are any collisions or problems you run into, I suggest you fork this repo to Elfen-Service/Payone-Magento1 and use modman from there.
