### ISSUE TITLE
Delete Stored Customer Payment Data

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#404]
We had a customer, who asked us to delete his stored payment data (credit card).

1. Is it correct that this can neither be done via the admin panel nor via the customer account?
2. Is it enough to delete the entry from the `payone_customer` table or is there more data, which needs to be removed?

Thanks!

**Comment by fjbender** [comment]
I'll make this quick ;)

1. Yes
2. Yes*

*as far as our plugin is concerned

**Comment by sprankhub** [comment]
Thanks!

I am not that into GDPR-stuff, but I could imagine that there is a requirement that this data can easily be deleted... So maybe this is something, which should be added?

**Comment by fjbender** [comment]
Nothing about "easy" in GDPR ;)

We'll see what we can do, a full-featured "manage my payment methods" panel within the customer profile would be nice, but also seems like a lot of work.
