### ISSUE TITLE
Mail compatibility with ASchroeder SMTP Plugin

### ISSUE THREAD

**Issue by template-provider** [PAYONE-GmbH/magento-1#41]
Hi,
how does the payone extension send its mails?
We are using the aschroeder smtp extension for that pupose. Is this compatible?
Our customer does not seems to get the order mails with the credit card orders over payone.

If so ... is there a workaround for that?
Greetings Jan

**Comment by template-provider** [comment]
https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension

**Comment by fjbender** [comment]
As I see it, we're sending the order confirmation e-mail just from the `Mage_Sales_Model_Order` passed to `Payone_Core_Model_Service_Sales_OrderConfirmation`: https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Service/Sales/OrderConfirmation.php#L47

I don't know if aschroeder's extension has any special requirements regarding the sending of emails. We will rely on the core Magento methods, though.

**Comment by fjbender** [comment]
This just hit me: Maybe the transaction status is not received? See `Payone_Core_Model_Observer_TransactionStatus_OrderConfirmation`

**Comment by template-provider** [comment]
Hi, thanks for the info ... I will log into that ;-)

**Comment by template-provider** [comment]
ahhh I think it hits me ... we have a new domain since last week.
could be that the problem? no api communication since, but odering is not a problem.
the server correctly gives a 301 to the new url, but I dont think that the payone api follows this from a POST request.

**Comment by template-provider** [comment]
correct:
{ "time": "2017-02-24T14:28:51+01:00", "remote_addr": "xxxxxxx", "body_bytes_sent": "194", "request_time": "0.000", "status": "301", "request": "POST /de/payone/processing/status HTTP/1.1", "request_method": "POST", "http_referrer": "-", "http_user_agent": "PAYONE FinanceGate" }

ok, this issue has nothing to do with mailing ... will close it
