### ISSUE TITLE
Needless Payone_Core_Checkout_CartController 

### ISSUE THREAD

**Issue by phizab** [PAYONE-GmbH/magento-1#413]
What is the reason for Payone_Core_Checkout_CartController? No method is overwritten from parent and there is no inheritence. Am I missing anything or is this class needless?

Because this class can lead to rewrite conflicts it should be removed, if there is no functionality behind this.

**Comment by fjbender** [comment]
Sorry for getting back to you so late. 

As far as I can see, this class should still be around for the "reactivate quote after something went bad externally" functionality. It hasn't been touched for a while, and I am not completely sure it is used, though.

However, I am a bit hesitant to touch this, as the mentioned functionality is somewhat crucial to some of our customers.
