### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#418]
Now that #370 is implemented, I would **love** to have a new release :) Thanks!

**Comment by fjbender** [comment]
We're currently working on a new release.

**Comment by T-Kuchel** [comment]
Hi @sprankhub ,

the new release is deployed > [v4.6.0](https://github.com/PAYONE-GmbH/magento-1/releases/tag/v4.6.0)

Greetings from Kiel
Timo

**Comment by sprankhub** [comment]
Thanks!
