### ISSUE TITLE
Skin Images are missing in composer.json

### ISSUE THREAD

**Issue by christophmassmann** [PAYONE-GmbH/magento-1#426]
The path `skin/frontend/base/default/images/payone/` is missing in `composer.json` (see also #175).

BTW: I don't see any benefit from not using the `modman` file in combination with `composer.json` because otherwise you have to maintain the mappings in 2 different files which leads to issues like this one.

**Comment by fjbender** [comment]
Thanks for noticing, will fix with #427 

Coexistence of composer.json and modman files follows a "to each their own" thought. Users seem to have different preferences.
