### ISSUE TITLE
Credit-Card-Payment in Sandbox Mode - Transaction not changed

### ISSUE THREAD

**Issue by wilfriedwolf** [PAYONE-GmbH/magento-1#444]
Hi there,

while payments work perfectly in production mode, we can not test anything correctly in sandbox mode, since the URL 

`/index.php/payone_core/transactionStatus `

is never accessed, it does not appear in the logs, so the transaction status is not changed.
I suppose it being a configuration problem, but I can not figure out, where this URL is transmitted to PayOne, to check if it is correctly given.

Could you please help?

Best regards and thanks in advance,

Willi

**Comment by hreinberger** [comment]
Hi @wilfriedwolf 
these kinds of errors can have multiple causes. Mostly, it's just a misconfiguration in your merchant backend or any system that receives the txstatus callback and doesn't forward it correctly. The best way of troubleshooting would be if you contacted our technical support at tech[dot]support[at]payone.com with your merchant ID and a link to this issue. Our colleagues can then dive deeper into the API communication and your specific merchant configuration.

If the issue doesn't clear up, feel free to re-open!
cheers
