### ISSUE TITLE
payone_sales_order_grid_massactionJsObject is not defined in Order grid

### ISSUE THREAD

**Issue by dbachmann** [PAYONE-GmbH/magento-1#458]
Hey there, 

with the latest extension version my customer gets the following error in the order grid when he change the number of the shown entries: Uncaught ReferenceError: payone_sales_order_grid_massactionJsObject is not defined. This error apears in the js console and in the backend we see the magento loading mask and it is not possible to click anywhere. 

When I delete the loading mask div in dev tools, it is not possible to go to the next page or open an order.  

Is this a known bug?

**Comment by fjbender** [comment]
Hi @dbachmann ,

I haven't heard this bug before and am unable to reproduce the error. We did some JS fiddling recently (e.g. #499), but that should only affect the frontend
