### ISSUE TITLE
Massive Zeitverzögerung beim Checkout

### ISSUE THREAD

**Issue by OrtmaierDruck** [PAYONE-GmbH/magento-1#459]
Sehr geehrte Damen und Herren,
 
wir verwenden seit 2016 ein Magento 1 Shopsystem mit Payone Plugin  (Zahlungsarten Bankeinzug und Kreditkarte)
Es gab hier keinerlei Probleme.  Am 14.12. wurde von unserem Hoster  (CloudLab)  ein Update für das Payone Plugin (Version 5.1.0.) eingespielt.
Seitdem gibt es hier ein seltsames Verhalten bei Kundenkonten mit vielen Adressen.
Sobald man vom Warenkorb in den Checkout möchte wird dies teilweise bis zu 2 Minuten verzögert.
Unser Hoster nannte uns hier das Payone Plugin als Übeltäter.
 
Anbei die Infos dazu:
----------------------------------
das berichtete Verhalten hängt mit dem jüngst aufgespielten Update des Payment-Moduls zusammen.

Beim Wechsel vom Warenkorb in den Checkout setzt dieses einen Trigger, die Kundendaten neu zu speichern.

Dieses erneute Speichern überträgt sich infolge auch auf die epace-Anbindung und bei Accounts mit sehr vielen Adressen führt dies in Konsequenz zu den berichteten Performance-Einbußen.

hier nun die Details zum Fall.
Die folgende Extension-Datei triggert das Speichern der Kundendaten, was zu den berichteten Einschränkungen hier führt (Zeile 56): https://github.com/PAYONE-GmbH/magento-1/blob/be9c7d26244925cf45897843196c429241a21596/app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/Payment/Methods.php#L52-L69

Der Support von Payone  hat uns hierher verwiesen:

Sehr geehrter Herr Klostermann,

die Kollegen meinen, Sie sollten das Problem über die Github Seite melden, dort sind die Kollegen auch direkt erreichbar, also ohne den Umweg über den Support.
https://github.com/PAYONE-GmbH/magento-1/issues

Mit freundlichen Grüßen / Best regards

Technical Support Engineer

----------------------------------------

Ich bitte Sie daher auf diesem Wege um Unterstützung.
Vielen Dank im Voraus für Ihre Bemühungen.

Mit freundlichen Grüßen
Benjamin Klostermann

**Comment by fjbender** [comment]
Moin,

mit #460 versuchen wir, die betroffene Codestelle so umzugestalten, dass das Problem nicht mehr auftritt.

Aktuell ist der Fix noch nicht getestet. Möglicherweise bietet es sich an, den Fix schon einmal auf einem Stage-System auszuprobieren, während er durch unsere QA läuft.
