### ISSUE TITLE
method = payone_wallet_paypal_express but payone_config_payment_method_id references ratepay_invoicing

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#472]
We have the phenomena, that in `sales_flat_order_payment` the informations in the field `method` and `payone_config_payment_method_id` are contradictory.

I have no idea were to start hunting for this bug, but a colleague said, that he experiences the same and they have to fix 10-50 orders every couple of months.

I'm happy to dig for the bug, and happy for every idea or direction where this behaviour can be originated.

**Comment by sprankhub** [comment]
That was me :hand: 

This may be related to #35.

**Comment by Schrank** [comment]
Ah, important info, we are running 5.1.0 - I couldn't find a reason on the changelog to update yet.

**Comment by Schrank** [comment]
@hreinberger sorry to bug you, but is there any hope, Payone will invest into this plugin? Because if not (which is expected) we need to take care of it of our own.

**Comment by hreinberger** [comment]
Hi there,

first of all, I've given this case to our devs for evaluation. We'll see what we can do.
Secondly, though the plugin is late in its product cycle and likely won't see major feature drops anymore, we don't want this plugin to end as abandonware. I'm sorry for responding so late to issues lately. We're working hard on getting better at reacting to issues. (and fixing them of course 😄)

I'll circle back when we've had a chance to look at this issue.

**Comment by hreinberger** [comment]
Update: We're still unable to reproduce this 😵
