### ISSUE TITLE
Credit Rating: 'incrementCreditratingSampleCounter' produces unnecessary DB queries! 

### ISSUE THREAD

**Issue by pgrudina** [PAYONE-GmbH/magento-1#473]
When Credit rating disabled there is a method 'setCreditratingSampleCounter' that still doing 'saveConfig' and produces unnecessary DB queries on every order place after.

It could simply be improved if you check if Credit Rating is enabled:

> public function setCreditratingSampleCounter($count, $storeId)
    {
         $creditRating = $this->getConfigProtect($storeId)->getCreditrating();
          if ($creditRating->isEnabled()) {
              Mage::getConfig()->saveConfig(self::CONFIG_KEY_CREDITRATING_SAMPLE_COUNTER, $count, 'stores', $storeId);
          }
    }

**Comment by janteuber** [comment]
Hello,
We solved that issue with https://github.com/PAYONE-GmbH/magento-1/pull/474 I merged it today.
