### ISSUE TITLE
Article list faulty or incomplete (error code 1610)

### ISSUE THREAD

**Issue by pgrudina** [PAYONE-GmbH/magento-1#476]
Can someone please help with the error '1610 Article list faulty or incomplete'.
Magento 1 (OpenMage LTS 19.4.13)
Payone module version 5.2.0

Request log:
`INFO - add_paydata[action]=start_session
add_paydata[shipping_email]=my@email
add_paydata[shipping_telephonenumber]=123123123
add_paydata[shipping_title]=Mr
aid=31111
amount=559800
api_version=3.10
birthday=xxxxxxxx
city=Berlin
clearingtype=fnc
country=DK
currency=DKK
de[1]=Product name
ed[1]=
email=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
encoding=UTF-8
financingtype=KIV
firstname=xxxxx
id[1]=1111111
integrator_name=openmage
integrator_version=19.4.13
invoice_deliverydate=
invoice_deliveryenddate=
invoice_deliverymode=
invoiceappendix=
invoiceid=
it[1]=goods
key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
lastname=xxxx
mid=31111
mode=test
no[1]=1
portalid=2000000
pr[1]=500000
request=genericpayment
sd[1]=
shipping_addressaddition=
shipping_city=Berlin
shipping_company=
shipping_country=DK
shipping_firstname=xxxxx
shipping_lastname=xxxx
shipping_state=
shipping_street=xxxxxx
shipping_zip=213123
solution_name=fatchip
solution_version=5.2.0
street=xxxxxx
telephonenumber=xxxxxxxxx
va[1]=2000
zip=213123`

`INFO - status=ERROR
errorcode=1610
errormessage=Article list faulty or incomplete
customermessage=An error occurred while processing this transaction (wrong parameters).
rawResponse_status=ERROR
rawResponse_errorcode=1610
rawResponse_errormessage=Article list faulty or incomplete
rawResponse_customermessage=An error occurred while processing this transaction (wrong parameters).
`

What does this error means? How to debug what's wrong here?

**Comment by hreinberger** [comment]
Hi @pgrudina 

our platform checks if the sum of all prices in the cart data (`pr[n]`) match the total amount in `amount`. In this case, the cart data show one item with a price of 500000 and the amount shows a grand total of 559800. 

Could it be that you use a special plugin for additional fees, shipping cost etc.? If not, could you contact our tech support team at tech[dot]support[at]payone[dot]com with a link to this issue and the txid/timestamp in question?

**Comment by pgrudina** [comment]
thanks a lot :)
