### ISSUE TITLE
New VISA requirements for 3DS - Supported?

### ISSUE THREAD

**Issue by wilfriedwolf** [PAYONE-GmbH/magento-1#501]
According to writings i found, VISA will soon require more fields for 3DS:

> Effective 12 August 2024, Visa will require 5 data elements in the 3DS Authentication Request (AReq) message. Merchants must provide complete and accurate transaction data in their authentication request for accurate risk assessments and better performance.

Since I am not very deep into your code, I wanted to ask if this module will fulfill these requirements, and if so, which minimal version is required.

Best regards and thanks a lot in advance,

Willi

**Comment by jvarelmann** [comment]
hello Willi,

we investigated the changes and in the newest version of the plugin was nothing to do

LG Juergen

**Comment by wilfriedwolf** [comment]
Thanks a lot, for the quick answer..
