### ISSUE TITLE
Online Bank Transfer Dropdown

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#53]
If only SOFORT is activated and the customer selects "online bank transfer" in the checkout, a dropdown is shown with only SOFORT as an option. This is stupid. In the [wallet template](https://github.com/PAYONE-GmbH/magento-1/blob/master/app/design/frontend/base/default/template/payone/core/payment/method/form/wallet.phtml), the select/dropdown is only shown if more than one type is available. I think this should also be implemented for the [bank transfer template](https://github.com/PAYONE-GmbH/magento-1/blob/master/app/design/frontend/base/default/template/payone/core/payment/method/form/onlinebanktransfer.phtml). If there is only one type, it should be automatically selected and not shown as a select/dropdown.

**Comment by fjbender** [comment]
It's stupid, true. We're currently working on splitting up all payment methods, so there won't be any dropdowns in the future.

**Comment by fjbender** [comment]
Fixed with Release v3.7.8
