### ISSUE TITLE
Online Capture error in Backend

### ISSUE THREAD

**Issue by diglin** [PAYONE-GmbH/magento-1#56]
Hello,

When the merchant generate the Magento invoice from backend and the capture is defined for online, he receives the following errors: `There has been an error processing your payment`

Log shows the followings, any ideas which help me to know the source of the problem ?

```
INFO - status=ERROR|errorcode=950|errormessage=Desired status change not possible for this payment process|customermessage=An error occured while processing this transaction (wrong parameters).|rawResponse_status=ERROR|rawResponse_errorcode=950|rawResponse_errormessage=Desired status change not possible for this payment process|rawResponse_customermessage=An error occured while processing this transaction (wrong parameters).
```

Thanks in advances

**Comment by fjbender** [comment]
Hi,

This is most likely an error in your configuration or setup in general, not with the module itself. Please contact our Technical Support Team at +49 431 25968-500 or tech.support@payone.de

Thanks
Florian

**Comment by diglin** [comment]
ok thanks
