### ISSUE TITLE
Problem with switching payment method for logged in customer (maybe only in one step checkout)

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#57]
I'm using GoMage Lightcheckout with Payone 3.7.6.

For guest orders everything works perfectly. However for logged in customers when selecting a different payment method, it always switches back to the original one.

See video here: https://screencast.com/t/2nwIjWu64qVa

I dont think this issue only happens with Lightcheckout extension, as I also had this with the standard Magento checkout.

I paid Gomage to fix it and they found the issue in one of your files /app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php

See difference here: https://www.diffnow.com/?report=9n3qb

They added following function, which fixed it: https://screencast.com/t/Zz5VLS9Y8Uo

public function getSelectedMethodCode()
    {
        if ($codeMethod = parent::getSelectedMethodCode()) {
            $sessionCodeMethod = Mage::getModel('sales/quote')
                ->load(Mage::getSingleton('checkout/session')->getQuoteId())
                ->getPayment()
                ->getMethodInstance()
                ->getCode();
            if ($codeMethod != $sessionCodeMethod) {
                return $sessionCodeMethod;
            }
        }

        return parent::getSelectedMethodCode();

    }

**Comment by T-Kuchel** [comment]
Hi gndk,

we will have a look on that.

**Comment by T-Kuchel** [comment]
We merged your suggestion.

**Comment by gndk** [comment]
I just noticed a possible problem with this.

When no default payment method is selected in the Gomage Lightcheckout extension, there is an error on /onepage/checkout for logged-in customers. Guest checkouts are not affected.

Error:
The requested Payment Method is not available.

Trace:
#0 /home/cloudpanel/htdocs/www.petsecu.dev/app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('The requested P...')
#1 /home/cloudpanel/htdocs/www.petsecu.dev/app/code/core/Mage/Sales/Model/Quote/Payment.php(218): Mage_Payment_Model_Info->getMethodInstance()
#2 /home/cloudpanel/htdocs/www.petsecu.dev/app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php(152): Mage_Sales_Model_Quote_Payment->getMethodInstance()
#3 /home/cloudpanel/htdocs/www.petsecu.dev/app/design/frontend/petsecu/default/template/gomage/checkout/html/payment-method/methods.phtml(51): Payone_Core_Block_Checkout_Onepage_Payment_Methods->getSelectedMethodCode()

Setting a default payment method solves this, but is not ideal.

**Comment by T-Kuchel** [comment]
Hi gndk,
the problem right now is, that we dont have the gomage extension to reproduce this possible issue.
Maybe the developers from GoMage could give you/us a hint to solve this.

**Comment by rofthedeep** [comment]
We are getting the same problems in combination with the OneStepCheckout Plugin ... the checkout breaks from existing customers with the following message:

`a:5:{i:0;s:50:"Die angeforderte Zahlungsart ist nicht verfügbar.";i:1;s:5099:"#0 /var/www/web101/htdocs/releases/20171123151913/html/app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('Die angefordert...')`
