### ISSUE TITLE
Update sql not working when using table prefix

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#58]
I recently updated from 3.7.6 to the latest master branch commit.

When updating I get an error "1146 Table 'DBNAME.payone_config_payment_method' doesn't exist"

I am using a db prefix so the table is called myprefix_payone_config_payment_method

The table name for the sql upgrade files should be dynamic, including the table prefix from local.xml

**Comment by T-Kuchel** [comment]
Hi gndk,

we will take care of this.

**Comment by T-Kuchel** [comment]
Should work with the fix now.
