### ISSUE TITLE
Payment method configuration with id "0" not found.

### ISSUE THREAD

**Issue by jniebergall** [PAYONE-GmbH/magento-1#8]
Der Fehler tritt auf, wenn man mit Kreditkarte zahlen will:

Payment method configuration with id "0" not found.

```
> Trace:
> #0 /app/code/community/Payone/Core/Block/Payment/Method/Info/Abstract.php(59): Payone_Core_Helper_Config->getConfigPaymentMethodByQuote(Object(CHBilling_Model_Sales_Quote))
> #1 app/code/community/Payone/Core/Block/Payment/Method/Info/Abstract.php(76): Payone_Core_Block_Payment_Method_Info_Abstract->getPaymentConfig()
> #2 app/design/frontend/base/default/template/payone/core/payment/method/info/creditcard.phtml(26): Payone_Core_Block_Payment_Method_Info_Abstract->getMethodTitle()
> #3 app/code/core/Mage/Core/Block/Template.php(241): include('/ledbprup/preli...')
> #4 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
> #5 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
> #6 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
> #7 app/code/core/Mage/Checkout/Block/Onepage/Payment/Info.php(54): Mage_Core_Block_Abstract->toHtml()
> #8 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Checkout_Block_Onepage_Payment_Info->_toHtml()
> # 9app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
> #10 app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('payment_info', true)
> #11 app/code/core/Mage/Checkout/Block/Onepage/Progress.php(69): Mage_Core_Block_Abstract->getChildHtml('payment_info')
> #12 app/design/frontend/base/default/template/checkout/onepage/progress/payment.phtml(34): Mage_Checkout_Block_Onepage_Progress->getPaymentHtml()
> #13 app/code/core/Mage/Core/Block/Template.php(241): include('/ledbprup/preli...')
> #14 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
> # 15app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
> #16 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
> #17 app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
> #18 app/code/core/Mage/Checkout/controllers/OnepageController.php(243): Mage_Core_Model_Layout->getOutput()
> #19 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->progressAction()
> #20 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('progress')
> #21 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
> #22 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
> #23 app/Mage.php(684): Mage_Core_Model_App->run(Array)
> #24 index.php(87): Mage::run('', 'store')
> #25 {main}
```

Wir verwenden die aktuellste Version vom commit 9cd4d08.

**Comment by fjbender** [comment]
Moin @jniebergall, kannst du mir einen Konfigurationsexport schicken? In der Regel deutet das Problem auf eine unvollständige Konfiguration hin (ist manchmal nicht ganz leicht zu erkennen).

**Comment by Sp0ng3b0b** [comment]
@fjbender Bei mir existiert dasselbe Problem. Welche Konfiguration sollte man überprüfen?

**Comment by PAYONE-GmbH** [comment]
Hallo @Sp0ng3b0b ... grundsätzlich betrifft dies solche Felder wie Minmaler/Maximaler Warenkorb bei aktivierten Zahlungsarten, die gar nicht befüllt sind.
Ein Beispiel:
So sollte es im Konfigurationsexpport (Menü: PAYONE->Konfiguration->Konfiguration exportieren) aussehen:
`<cc>
	<title><![CDATA[PAYONE creditcard]]></title>
	<id>13</id>
	<mid>12345</mid>
	<aid>54321</aid>
	<portalid>2022951</portalid>
	<min_order_total>1</min_order_total>
	<max_order_total>100000</max_order_total>
	<cvc2>always</cvc2>
	<types>V,M,A</types>
	<active>1</active>
	<countries>DE</countries>
	<authorization>preauthorization</authorization>
	<mode>test</mode>
</cc>`


So nicht (es fehlen min_order_total und max_order_total weil nicht befüllt ):
`<cc>
	<title><![CDATA[PAYONE creditcard]]></title>
	<id>13</id>
	<mid>12345</mid>
	<aid>54321</aid>
	<portalid>2022951</portalid>
	<cvc2>always</cvc2>
	<types>V,M,A</types>
	<active>1</active>
	<countries>DE</countries>
	<authorization>preauthorization</authorization>
	<mode>test</mode>
</cc>`

**Comment by Sp0ng3b0b** [comment]
@PAYONE-GmbH Das hat mein Problem gelöst, vielen Dank :) :+1:

**Comment by Backenkoehler** [comment]
Wir haben leider das gleiche Problem trotz min_order_total mit 0 und max_order_total 10000

`      <cc>
        <title><![CDATA[Creditcard]]></title>
        <id>12</id>
        <mid>31302</mid>
        <aid>33250</aid>
        <portalid>2022345</portalid>
        <min_order_total>0</min_order_total>
        <max_order_total>10000</max_order_total>
        <cvc2>always</cvc2>
        <types>V,M,A,D,J,C,B</types>
        <active>0</active>
        <countries>AU</countries>
        <authorization>authorization</authorization>
        <mode>live</mode>
      </cc>`

Habe auch schon versucht nicht dir globalen Merchant-Daten nochmal direkt zu setzen anstatt die globalen zu nutzen.

**Comment by PAYONE-GmbH** [comment]
Hallo @Backenkoehler,

ich müsste mir einmal die komplette XML Datei anschauen, da sich leider nicht nur an den Warenkorbgrenzen der Fehlerteufel einschleichen kann.
Damit Ihre Daten geschützt werden / bleiben einfach die XML an integrations@payone.de senden.

Beste Grüße Timo Kuchel

**Comment by bragento** [comment]
Hallo @Backenkoehler,

ich habe ein ähnliches Problem. Keine Kreditkartenzahlung möglich.
exception 'Payone_Core_Exception_PaymentMethodConfigNotFound' with message 'Payment method configuration with id "" not found.' in .......

In der phtml creditcardiframe wird beim value vom hidden input nichts gesetzt. Nur für KK.

Eine Mail mit der der Config schicke ich an o.g. Mail.

Besten Gruß
Christian Werner

**Comment by Backenkoehler** [comment]
Hallo @bragento 

Wir haben bisher auch noch keine richtige Lösung dafür und das Problem ist auch nicht global, sondern immer nur in einer gewissen Store View. Wenn man Kreditkarte als Zahloption in den Payone-Einstellungen löscht und wieder hinzugefügt funktioniert es dann eben nach einigen Versuchen (und dann muss man wieder alle anderen Store Views testen). Auf jeden Fall ein sehr merkwürdiges Phänomen.


Gruß
Stephan Backenköhler

**Comment by fjbender** [comment]
Moin zusammen,

wir arbeiten aktuell an einem Umbau der gesamten Zahlartenstruktur, sodass Probleme dieser Art (und noch ganz viele andere nervige Dinge) nicht mehr auftauchen sollten. Da der Umbau wohl sehr umfangreich ausfallen wird, müssen wir hier noch um etwas Geduld bitten.

Während dieser Zeit helfen wir bei Problemen natürlich nach Kräften weiter über unseren Support.

Beste Grüße
Florian

**Comment by ernsto** [comment]
@PAYONE-GmbH Wir hatten das gleiche Problem. Wir konnten es aber dank folgendem Tipp lösen:
https://github.com/PAYONE-GmbH/magento-1/issues/8#issuecomment-236873671

Vielen Dank :+1:

**Comment by tniebergall** [comment]
Bei diesem Problem kann es auch helfen, sofern vorhanden die jQuery Integration zu prüfen. Wenn der noconflict Mode nicht direkt auf die jQuery Source folgt, kann es ebenfalls zu diesem Problem kommen, da das Payone JS fehlerhaft verarbeitet wird.

**Comment by fjbender** [comment]
Maybe 48937d3304bd61f587b3f7635d89100d5f141db5 fixed the issue. Can anyone confirm?

**Comment by KaiBroenstrup** [comment]
Hallo,
dieser Fehler scheint nicht behoben. Taucht jetzt in unserem DEV Shop jedesmal auf. Min/Max Values habe ich schon vergeben. Gibt es irgendwelche News wie man den Fehler fixen kann?

Danke

**Comment by fjbender** [comment]
Moin @KaiBroenstrup,

bisher gibt es noch keine definitive Lösung. Vielleicht hilft es, die Konfiguration einmal mithilfe unseres Technical Support prüfen zu lassen: +49 431 25968-500 oder tech.support@payone.de

**Comment by KaiBroenstrup** [comment]
Hi,

durch löschen aller Zahlungsarten und neu anlegen scheint es erstmal wieder zu gehen.

Danke vorerst

**Comment by KaiBroenstrup** [comment]
Hi @fjbender - doch kein Erfolg. Problem ist wieder da. Das löschen aller Zahlungsarten und neu anlegen hat auch nicht funktioniert. Sobald ich mehr als 1 Payone Zahlungsart habe bekomme ich im Checkout den Fehler.
Wie kann ich das lösen?

danke

**Comment by fjbender** [comment]
@KaiBroenstrup das Problem trat leider vorher auch schon auf - einen kausalen Zusammenhang mit dem letzten Update schließen wir aus.

Wir würden den Fall trotzdem gerne mal näher betrachten, bitte unter Verweis auf diesen Vorgang hier einmal Kontakt mit dem Technical Support, Kontaktdaten siehe oben, aufnehmen, dann können wir die Konfiguration nochmal im Detail durchsehen.

Danke
Florian

**Comment by mediaimprove** [comment]
Ich schließe mich hier @KaiBroenstrup an. Problem existiert auch bei uns seit Version 3.7.8 mit Magento 1.9.3.3. Testumgebung wurde mehrfach komplett neu mit Version 3.7.6 installiert, hier tritt das Problem nicht auf. Technical Support ist informiert.

**Comment by fjbender** [comment]
Moin zusammen,

kann jemand bitte einmal schauen, ob das Problem auch auftritt, wenn die "payone_customer" Tabelle geleert wurde? Ich vermute, dass hieraus alte Daten zum Laden der Payment Method Config herangezogen werden.

**Comment by branb** [comment]
@fjbender 
Da ich die Extension frisch installiert habe, ist die Tabelle _payone_customer_ bei mir bereits leer.

Die Fehlermeldung mit dem neuesten Commit #87 lautet jetzt übrigens:

> Payment method configuration for method "payone_creditcard" not found.

**Comment by fjbender** [comment]
@branb alles klar, vielen Dank. Dann müssen wir in andere Richtung weiter suchen.

**Comment by KaiH1980** [comment]
Gibt es dazu eine Lösung? Wir haben in einem Testsystem das gleiche Problem (Payment method configuration with id "" not found.)
Trotz angegebenen Min/Max Wert sehe ich die Werte nicht im Konfigurationsexport - ist das das Problem? Wie kann ich diesen modifizieren?

**Comment by fjbender** [comment]
@KaiH1980 wir haben leider noch keine endgültige Lösung für das Problem. Vielleicht kann bei dem min/max Problem unser Tech Support weiterhelfen: 0431/25968-500 oder tech.support@bspayone.com

Danke und viele Grüße
Florian

**Comment by luckyduck** [comment]
Irgendwie ein Update dazu? Ich habe das gleiche Problem, aber mit der neueren Meldung "payone_creditcart" statt "0" nicht gefunden.

**Comment by fjbender** [comment]
Leider gibt es hier noch nichts neues.

**Comment by fjbender** [comment]
Es gibt einen möglichen Workaround. Ein Nutzer hat herausgefunden, dass möglicherweise die Cache-Schicht Schuld ist und dort falsche Daten vorgehalten werden. Wir wissen noch nicht, wie das zu Stande kommt, allerdings funktioniert alles stabil, wenn man den Cache einfach kurzschließt. In der Datei app/code/community/Payone/Core/Model/Service/InitializeConfig.php die Methode `loadFromCache()` so modifizieren:

```php
    protected function loadFromCache()
    {
        // @todo: Workaround to bypass cache
        return NULL;

        // Check cache and if its there, return stored config:
        if (Mage::app()->useCache('config')) {
            $cacheId = $this->getConfigCacheId();
            $data = Mage::app()->loadCache($cacheId);

            if ($data) {
                $config = unserialize($data);
                return $config;
            }
        }

        return NULL;
    }
```

Kann jemand diesen Ansatz bestätigen?

**Comment by fjbender** [comment]
In #286 is noch aufgekommen, dass dieses Problem u.U. schon am quote auftaucht.

**Comment by fjbender** [comment]
Wir haben jetzt mit #349 eine vielversprechende Lösung, die den Cache-Ansatz weiterverfolgt.

Gibt es einen Freiwilligen aus dieser Runde, der das ausprobieren kann? Wir haben ja, wie bekannt, Probleme das nachzustellen.

**Comment by mwr** [comment]
Ich bin mir nicht sicher ob dieses Problem hier damit gefixed ist, es wäre aber ggf. möglich den Cache zu umgehen mit dem Parameter useCache false.
Das Caching beim Config laden hatte ich auch schon im Verdacht, das war mir aber zu breit im System verteilt, als dass ich daran ohne Test Coverage Änderungen vornehmen wollte

**Comment by KaiH1980** [comment]
Und wieder mal bin ich in Ihrem internen Verteiler gelandet….mittlerweile das vierte Mal…

 justSelling
Full Service E-Commerce Agentur

Kai Helmerichs
Digital Account Manager

E  kai.helmerichs@justselling.de <mailto:kai.helmerichs@justselling.de> 
T  +49 (2802) 70795 25
M +49 (151) 23981488
F  +49 (2802) 70795 99
I   http://www.justselling.de <http://www.justselling.de> 
 
justSelling GmbH
Nordring 6
47495 Rheinberg 
Germany

Amtsgericht Kleve, HRB13216
Umsatzsteuer Identifikationsnummer DE 298457921
Geschäftsführer Michael Schäfer, Thomas Mannsky
Vorsitzender des Beirats Hartmut G. Korn

Der Beste Produkt Konfigurator für Ihren Webauftritt oder Webshop: http://www.product-configurator.biz <http://www.product-configurator.biz> 
The Best Product Configurator for your website or webshop: http://www.product-configurator.com <http://www.product-configurator.com> 


https://www.facebook.com/justSellingGmbH/

Am 28.06.2019 um 10:33 schrieb Matthias Walter <notifications@github.com <mailto:notifications@github.com> >:

Ich bin mir nicht sicher ob dieses Problem hier damit gefixed ist, es wäre aber ggf. möglich den Cache zu umgehen mit dem Parameter useCache false.
Das Caching beim Config laden hatte ich auch schon im Verdacht, das war mir aber zu breit im System verteilt, als dass ich daran ohne Test Coverage Änderungen vornehmen wollte

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

<http://schema.org>

**Comment by sprankhub** [comment]
@KaiH1980 das Prinzip nennt sich GitHub. Sie hatten hier einen [Kommentar](https://github.com/PAYONE-GmbH/magento-1/issues/8#issuecomment-354766389) hinterlassen und werden seitdem bei neuen Nachrichten zu diesem Issue informiert. Entweder Sie ändern Ihre GitHub Einstellungen oder Sie unsubscriben sich von diesem Issue.

**Comment by DavidLambauer** [comment]
lol

**Comment by riconeitzel** [comment]
😂 made my day! thanks @KaiH1980

**Comment by fjbender** [comment]
Wir haben #349 jetzt gemerged, vielleicht gibt es ja weiterhin mutige Freiwillige.

**Comment by mwr** [comment]
OK. Wir haben heute #349 produktiv genommen, nach ausgiebiger Testphase inkl. Upgrade auf die neuste PAYONE Modul Version

**Comment by branb** [comment]
> Wir haben #349 jetzt gemerged, vielleicht gibt es ja weiterhin mutige Freiwillige.

Wir nutzen PAYONE leider nicht mehr, daher kann ich da vorerst keine sinnvollen Daten zu beisteuern.

**Comment by fjbender** [comment]
Wir waren jetzt mutig und haben das mit v4.5.0 released.
