### ISSUE TITLE
credit card payment doesn't work

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#85]
Sorry for posting in german, it is too late to translate it :-/

Ich habe heute Payone auf die Version 3.7.7 in unserem Magento 1 aktualisiert. Seit dem funktioniert die Kreditkartenzahlung nicht mehr und wenn ich die Kreditkartendaten ausfülle werde ich, beim Abschicken des Payment-Steps, immer wieder auf die Warenkorbseite zurück geworfen.

Das Problem konnte ich einkreise, verstehe aber nicht wie es dazu kommt:

Wenn das Kreditkartenformular geladen wird, gibt es ein hidden-Field, mit dem Namen "payone_config_payment_method_id" und ohne Wert. Dieses Feld wird an Magento geschickt, wenn die Payment-Daten gespeichert werden sollen.

Wenn das Payment gespeichert wird, gibt es einen Observer der aufgerufen wird: \Payone_Core_Model_Observer_Checkout_Onepage_MultiplePaymentCheck::performChecks, dieser prüft zuerst, ob der Wert existiert und ob er gesetzt ist (https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/MultiplePaymentCheck.php#L269-L276). Dies ist, wenn überhaupt der Fall, wenn der Besucher eingeloggt ist.

Dieser Code ist schon alt, also ist er wohl nicht kaputt und ich verstehe nicht warum der Wert leer ist und die Exception fliegt.

Ich wäre um zügige Aufklärung dankbar.

Einen Guten Morgen
Fabian Blechschmidt

**Comment by fjbender** [comment]
Moin,

ich vermute hier ein Duplikat von #8. Kannst du das bestätigen?

**Comment by Schrank** [comment]
Die Stelle ist eine Andere.

Und leider fehlt die erste Zeile, keine Ahnung warum die nicht mit rauskommt, ich denke aber das ist sowas wie:

`Uncatched Payone_Core_Exception_PaymentMethodConfigNotFound on pub/app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/MultiplePaymentCheck.php:275`

```
#0 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/MultiplePaymentCheck.php(82): Payone_Core_Model_Observer_Checkout_Onepage_MultiplePaymentCheck->init(Object(Varien_Event_Observer))
#1 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Core/Model/App.php(1358): Payone_Core_Model_Observer_Checkout_Onepage_MultiplePaymentCheck->performChecks(Object(Varien_Event_Observer))
#2 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Payone_Core_Model_Observer_Checkout_Onepage_MultiplePaymentCheck), 'performChecks', Object(Varien_Event_Observer))
#3 /Volumes/Web/shop.ingo-maurer.com/pub/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#4 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Core/Controller/Varien/Action.php(531): Mage::dispatchEvent('controller_acti...', Array)
#5 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Core/Controller/Front/Action.php(69): Mage_Core_Controller_Varien_Action->preDispatch()
#6 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Checkout/controllers/OnepageController.php(59): Mage_Core_Controller_Front_Action->preDispatch()
#7 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/community/Payone/Core/controllers/Checkout/OnepageController.php(79): Mage_Checkout_OnepageController->preDispatch()
#8 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Payone_Core_Checkout_OnepageController->preDispatch()
#9 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('savePayment')
#10 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /Volumes/Web/shop.ingo-maurer.com/pub/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#12 /Volumes/Web/shop.ingo-maurer.com/pub/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /Volumes/Web/shop.ingo-maurer.com/pub/index.php(85): Mage::run('', 'store')
#14 {main}

**Comment by Schrank** [comment]
Aber ich halte das Problem für das gleiche oder sehr ähnlich.

Wenn mir jemand erklären mag, wie unter normalen Umständen, dieses Feld befüllt wird:
https://github.com/PAYONE-GmbH/magento-1/blob/master/app/design/frontend/base/default/template/payone/core/payment/method/form/creditcard.phtml#L139-L140

Wühle ich auch gern selbst, aber das kommt meiner Meinung nach aus 

    \Payone_Core_Block_Payment_Method_Form_Creditcard::getPayoneConfigPaymentMethodId
    \Payone_Core_Block_Payment_Method_Form_Abstract::getSavedCustomerData


https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Block/Payment/Method/Form/Creditcard.php#L126-L130
https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Block/Payment/Method/Form/Abstract.php#L288-L300

Das kann nicht klappen, denn die Methode gibt immer einen leeren String zurück, wenn der Besucher nicht eingeloggt ist.

**Comment by Schrank** [comment]
Fehler gefunden.

Falls das Problem jemals wieder jemand haben sollte, bei uns war das Tempalte überschrieben:

    pub/app/design/frontend/base/default/template/payone/core/checkout/onepage/init.phtml

Da fehlte der Part:

    document.observe('dom:loaded', function () {
        payone.form = payment.form;
        payment.save = payment.save.wrap(
                function (origMethod) {
                    payone.exec(origMethod);
                }
        );
    });

Was dafür sorgt, dass das validation JS nicht läuft, den oben erwähnten Wert nicht setzt und damit das ganze auf PHP Seite uns um die Ohren fliegt.
