### ISSUE TITLE
Errors for customers are not displayed and logged into exception.log

### ISSUE THREAD

**Issue by domeglic** [PAYONE-GmbH/magento-1#89]
The errors meant for the customer (ex. wrong IBAN) are not displayed to the customer. They just get a generic "Something is wrong" error. Is this the desired behavior?
[Here the response with an error message is received and will be thrown as an exception](https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Service/Payment/Abstract.php#L90)
 [Here the response is ignored and instead a default message is returned](https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Payment/Method/Abstract.php#L566)

Additionally, since this is thrown as **Mage_Core_Exception** this is logged into exception.log. Since it is not a real exception it just spams the log whenever somebody makes a mistake. Throwing as **Mage_Payment_Model_Info_Exception** would be more appropriate perhaps.

**Comment by T-Kuchel** [comment]
We have decided to use a generic errormessage, because of the fact that not every errormessage is for the eyes of the customer.
i.e. 'creditcard payment declined, because of fraud.'

This message openes the door for everyone who wants to 'cheat'.

To answer your question:
>  Is this the desired behavior?

Yes, it is...

**Comment by fjbender** [comment]
However, one could argue that messages like this should be `Mage_Payment_Model_Info_Exception` instances to avoid spamming the exception log.

**Comment by domeglic** [comment]
I see, thank you.
