### ISSUE TITLE
Can't create creditmemos for advance payment

### ISSUE THREAD

**Issue by domeglic** [PAYONE-GmbH/magento-1#91]
I am using a test account to test advance payment and there seems to be a problem with refunds.
When trying to create a creditmemo it will throw an exception. 
API log says: 907 - Sequence no incorrect

I was told by tech support that the problem is because sequencenumber should be 2 instead of 1 if Authorization is used (Instead of Pre-Auth). This seems like a bug to me.

Magento: 1.9.2.4 (empty, no customizations)
Extension version: 3.7.8

**Comment by T-Kuchel** [comment]
Hi domeglic,

please write us to integrations@payone.de.
To investigate on this issue in the right and proper way we need informations like your MID (merchant id).
I am really sure that you don't want to share this with the whole community ;) 

best regards
