### ISSUE TITLE
Massive Number Of Payone_Core_Exception_OrderNotFound

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#95]
When Magento is not your only source of PAYONE transactions, the `exception.log` gets filled with entries like this:

    2017-07-30T20:00:07+00:00 ERR (3): 
    Payone_Core_Exception_OrderNotFound in /var/www/share/shop/htdocs/app/code/community/Payone/Core/controllers/TransactionStatusController.php:63
    Stack trace:
    #0 /var/www/share/shop/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Payone_Core_TransactionStatusController->indexAction()
    #1 /var/www/share/shop/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
    #2 /var/www/share/shop/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #3 /var/www/share/shop/htdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #4 /var/www/share/shop/htdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
    #5 /var/www/share/shop/htdocs/index.php(83): Mage::run('', 'store')
    #6 {main}

I think the reason is that transaction statuses are sent to Magento, which reference non-Magento orders. This can happen if you use Shopgate. Is it really necessary to throw an exception in this case? Or could you also check for Shopgate order references, so that these orders do not trigger an exception?

**Comment by fjbender** [comment]
I guess it'd probably be easier to not throw an OrderNotFound exception everytime. However, these can be quite useful when finding configuration problems, so I'd rather not remove it.

Probably it'd be best to circumvent this issue somehow, e.g. by using transaction status forwarding mechanisms in either Shopgate or Magento. Or you could write an interceptor receiving the transaction status notification from us and distribute it accordingly to the right system. Is there any way of circumventing this issue in your setup?

**Comment by sprankhub** [comment]
Of course I could "hack" the extension for this project to ignore these issues, but I do not think this is a good solution. And as said, all customers using PAYONE and Shopgate have this issue.

Interesting idea with the transaction status forwarding, but how could that look like?

**Comment by fjbender** [comment]
For this to work Shopgate needed to have the transaction status forwarding feature as well - which they unfortunately don't afaik - and be more tolerant about which order the tx status message refer to, so this won't work.

As this is quite a minor issue I won't be able to assign anybody to it right now. As I see it, there are three options to fix this issue:
1) You build a tx status interceptor script hosted somewhere, deciding which system receives which status notification (probably quite some work).
2) You disable this exception manually for this project (not desirable for obvious reasons).
3) A toggle is implemented that disables this exception if desired (should be turned on by default so tech support can see if there's something wrong; PRs welcome, as I don't think we could start very soon on this).

I'd love to go with the third option, however, this would most likely go into the backlog for quite some time. :confused:

**Comment by sprankhub** [comment]
As a first step, I extended the exception message - see #97.

In a second step, I consider creating a PR for handling this issue. But I would simply check if there is a Shopgate order with the given reference and would not throw an exception then. Does that sound good? I would of course check whether the Shopgate extension is installed.

**Comment by fjbender** [comment]
Thanks for #97.

Your plan sounds good to me :)
